### ISSUE TITLE
Excon 0.13.3, connection reset uploading to aws with fog

### ISSUE THREAD

**Issue by psschroeter** [excon/excon#121]
Hello, don't know if this belongs in fog or here, but when doing fog upload to aws s3, getting:

Getting error:
/usr/lib/ruby/1.8/openssl/buffering.rb:179:in `syswrite': Connection reset by peer (Excon::Errors::SocketError)
    from /usr/lib/ruby/1.8/openssl/buffering.rb:179:in`do_write'
    from /usr/lib/ruby/1.8/openssl/buffering.rb:193:in `write'
    from /usr/lib64/ruby/gems/1.8/gems/excon-0.13.3/lib/excon/connection.rb:239:in`request_kernel'
    from /usr/lib64/ruby/gems/1.8/gems/excon-0.13.3/lib/excon/connection.rb:97:in `request'
    from /usr/lib64/ruby/gems/1.8/gems/fog-1.3.1/lib/fog/core/connection.rb:20:in`request'
    from /usr/lib64/ruby/gems/1.8/gems/fog-1.3.1/lib/fog/aws/storage.rb:359:in `request'
    from /usr/lib64/ruby/gems/1.8/gems/fog-1.3.1/lib/fog/aws/requests/storage/put_object.rb:43:in`put_object'
    from /usr/lib64/ruby/gems/1.8/gems/fog-1.3.1/lib/fog/aws/models/storage/file.rb:133:in `save'
    from /usr/lib64/ruby/gems/1.8/gems/fog-1.3.1/lib/fog/core/collection.rb:50:in`create'
    from upload_temp.rb:27

uploading to us-west-1 based bucket in S3. using code
bucket.files.create(
  :key    => s3_file,
  :body   => ::File.open(file),
  :public => true
)

or if the file is small enough, it may upload but the etag is wrong

System should be a fairly standard centos 6.2 install/xen kernel, thought I think the code works on other systems (centos 5.6, ubuntu 10.04)

Also note that Excon 0.13.2 -> 0.13.0 seem to work fine.  Using latest Fog version (1.3.1) and ruby version:
ruby 1.8.7 (2011-06-30 patchlevel 352) [x86_64-linux], 
-Pete

**Comment by tacnoman** [comment]
I made downgrade to version 1.36 and worked for me.
