### ISSUE TITLE
Provide a way to get a full URI from the individual request params

### ISSUE THREAD

**Issue by myronmarston** [excon/excon#208]
(Continuing our discussion from vcr/vcr/#276)

In VCR's excon middleware, I need to construct a full URI from the individual request params.  The logic is kinda complex:

https://github.com/vcr/vcr/blob/3ab91c9db5e6c372fe7ae6aa51d357ebc9d360c3/lib/vcr/middleware/excon.rb#L181-L206

Given that excon is the source of these individual params (and presumably needs to do some similar URI construction internally), can this logic be put into something that can be exposed as a public API?

**Comment by geemus** [comment]
I believe this is now covered by Excon::Utils.connection_uri, see: https://github.com/excon/excon/blob/master/lib/excon/utils.rb#L19
