### ISSUE TITLE
Unable to verify certificate (SSL)

### ISSUE THREAD

**Issue by amdprophet** [excon/excon#239]
Since the 0.25.0 update yesterday, SSL certificate verification hasn't been working in conjunction with the Fog gem. When trying to connect to S3 I've been seeing the following error:

```
Excon::Errors::SocketError: cloud_remote_file[/usr/src/autofs4.tgz] (autofs::module_hack line 10) had an error: Excon::Errors::SocketError: Unable to verify certificate, please set `Excon.defaults[:ssl_ca_path] = path_to_certs`, `Excon.d
efaults[:ssl_ca_file] = path_to_file`, or `Excon.defaults[:ssl_verify_peer] = false` (less secure).
```

Downgrading to Excon 0.24.0 fixed the issue.

**Comment by ssoroka-se** [comment]
It's worth mentioning that `Excon.defaults[:ssl_verify_peer] = false` is _**insecure**_ and should _not_ be used in production.

Sorry to raise this from the dead, but it's the top result for google `excon defaults ssl_ca_file`, and we've got to set a good example. :)

**Comment by geemus** [comment]
@ssoroka-se yeah, I definitely agree that it should NOT be used in production. It can be helpful in some test environments, but should only be used as such (and likely with caution even then).

**Comment by betam4x** [comment]
FYI I HAVE THE SSL_CERT_FILE environment variable set, but I'm still getting this error.  SSL works fine for other libraries, any idea what this is about?

**Comment by geemus** [comment]
Not off hand. I don't have much experience troubleshooting this on windows unfortunately. Have you had luck/experience getting the same to work with net/http based stuff?

**Comment by fabianrios** [comment]
troya2 can you explain further, how do you get rid off SSL_CERT_FILE shell variable

**Comment by ktaragorn** [comment]
Hi sorry to necro, but I am facing this issue in my project. I am trying to upgrade from 1.9.3 ruby to 2.3, and in the process I had to upgrade Excon from 0.33.0 to 0.45.4. 

    pry(main)> ENV["SSL_CERT_FILE"]
    => "/etc/pki/tls/certs/ca-bundlae.crt"

For both ruby versions. I am on OSX el capitan using RVM. That file or even `/usr/local/<that file>` does not exist. However excon had no issues on 1.9.3 but fails with that error on 2.3. Does anyone know why? Is this a bug on 0.33.0?

**Comment by ktaragorn** [comment]
Hmm, 0.45.4 on 1.9.3 works...

**Comment by ktaragorn** [comment]
And on 2.3 fixing the ENV var to `/usr/local/etc/openssl/cert.pem` which is valid doesnt help...

**Comment by ktaragorn** [comment]
Deleting the env var fixes the issue on 2.3.. odd.
Actually discovered that that path is hardcoded in my app code..

**Comment by ktaragorn** [comment]
Hi sorry to necro, but I am facing this issue in my project. I am trying to upgrade from 1.9.3 ruby to 2.3, and in the process I had to upgrade Excon from 0.33.0 to 0.45.4. 

After lots of digging, this is what I come up with
What I know so far. My test setup 
- Run `pry`
- Set `ENV["SSL_CERT_FILE"]` to giberish
- `Excon.head "http://www.google.com"`

This works on ruby 1.9.3 and not on 2.3

**Comment by geemus** [comment]
Not sure. I wouldn't expect setting that to giberish to work anyway, is there a reason that it would need to? Otherwise I'm not certain (and haven't had many reports yet).

**Comment by ktaragorn** [comment]
@geemus Yeah I guess it is odd that it would at all.. Anyway I am still new to the project, so I ended up "fixing" or breaking it consistently in both ruby versions based on my sidekiq setting (i believe these tests that were failing were in jobs) So i am satisfied. I am going to remove these comments, not sure if they are helping anybody
