### ISSUE TITLE
excon 0.25.3 fails deployment on Heroku with asset_sync to S3

### ISSUE THREAD

**Issue by Hungor** [excon/excon#258]
Excon 0.25.3 (dependency in asset_sync 1.0.0) throws error SSL path etc. I missed to catch the log. But it was something with "Unable to verify certificate, please set Excon.defaults[:ssl_ca_path]"

When I specify 0.25.1 then everything works again.

I think that someone might face the same error.

**Comment by morwin10** [comment]
Hey, I hava the same problem on Windows with a CLI Heroku command :
`heroku logs --app myAppName`
I'm using with self certificate for connection, and i added it to "Trusted Root Certificate Authority", 
and i get this error:

Is from `error.log`:

> Heroku client internal error.
> SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (OpenSSL::SSL::SSLError) Unable to verify certificate. This may be an issue with the remote host or with Excon. Excon has certificates bundled, but these can be customized:
> 
>             `Excon.defaults[:ssl_ca_path] = path_to_certs`
>             `ENV['SSL_CERT_DIR'] = path_to_certs`
>             `Excon.defaults[:ssl_ca_file] = path_to_file`
>             `ENV['SSL_CERT_FILE'] = path_to_file'
>             `Excon.defaults[:ssl_verify_callback] = callback`
>                 (see OpenSSL::SSL::SSLContext#verify_callback)
> or:
>             `Excon.defaults[:ssl_verify_peer] = false` (less secure).
> 
> C:/Program Files (x86)/Heroku/vendor/gems/excon-0.51.0/lib/excon/ssl_socket.rb:127:in `connect'
> C:/Program Files (x86)/Heroku/vendor/gems/excon-0.51.0/lib/excon/ssl_socket.rb:127:in `initialize'
> C:/Program Files (x86)/Heroku/vendor/gems/excon-0.51.0/lib/excon/connection.rb:404:in `new'
> C:/Program Files (x86)/Heroku/vendor/gems/excon-0.51.0/lib/excon/connection.rb:404:in `socket'
> C:/Program Files (x86)/Heroku/vendor/gems/excon-0.51.0/lib/excon/connection.rb:106:in `request_call'
> C:/Program Files (x86)/Heroku/vendor/gems/excon-0.51.0/lib/excon/middlewares/base.rb:15:in `request_call'
> C:/Program Files (x86)/Heroku/vendor/gems/excon-0.51.0/lib/excon/middlewares/mock.rb:47:in `request_call'
> C:/Program Files (x86)/Heroku/vendor/gems/excon-0.51.0/lib/excon/middlewares/instrumentor.rb:25:in `request_call'
> C:/Program Files (x86)/Heroku/vendor/gems/excon-0.51.0/lib/excon/middlewares/base.rb:15:in `request_call'
> C:/Program Files (x86)/Heroku/vendor/gems/excon-0.51.0/lib/excon/middlewares/base.rb:15:in `request_call'
> C:/Program Files (x86)/Heroku/vendor/gems/excon-0.51.0/lib/excon/middlewares/base.rb:15:in `request_call'
> C:/Program Files (x86)/Heroku/vendor/gems/excon-0.51.0/lib/excon/connection.rb:250:in `request'
> C:/Program Files (x86)/Heroku/vendor/gems/excon-0.51.0/lib/excon.rb:238:in `get'
> C:/Program Files (x86)/Heroku/lib/heroku/updater.rb:35:in `http_get'
> C:/Program Files (x86)/Heroku/lib/heroku/updater.rb:160:in `block in download_file'
> C:/Program Files (x86)/Heroku/lib/heroku/updater.rb:159:in `open'
> C:/Program Files (x86)/Heroku/lib/heroku/updater.rb:159:in `download_file'
> C:/Program Files (x86)/Heroku/lib/heroku/updater.rb:133:in `block (2 levels) in update'
> C:/Program Files (x86)/Heroku/ruby-2.1.7/lib/ruby/2.1.0/tmpdir.rb:88:in `mktmpdir'
> C:/Program Files (x86)/Heroku/lib/heroku/updater.rb:125:in `block in update'
> C:/Program Files (x86)/Heroku/lib/heroku/updater.rb:92:in `wait_for_lock'
> C:/Program Files (x86)/Heroku/lib/heroku/updater.rb:121:in `update'
> C:/Program Files (x86)/Heroku/lib/heroku/updater.rb:109:in `rescue in autoupdate'
> C:/Program Files (x86)/Heroku/lib/heroku/updater.rb:105:in `autoupdate'
> C:/Program Files (x86)/Heroku/lib/heroku/cli.rb:35:in `start'
> C:/Program Files (x86)/Heroku/bin/heroku:29:in `<main>'

**Comment by geemus** [comment]
Excon tries to use system certs, but it doesn't always work (depends on ruby/openssl versions among other things). You can set a particular cert to use though (as per the customization instructions above). It looks like it was unable to find/use the system certs here, so specifying them in one of the described ways there should help (via ENV is probably the easiest to test and/or change if needed).
