### ISSUE TITLE
utf-8 encoding issue when uploading a string 

### ISSUE THREAD

**Issue by schorsch** [excon/excon#266]
i am reading a file content an put it as string into the reuqest body and get UTF-8 and ASCII-8BIT (Encoding::CompatibilityError)

In connection.rb https://github.com/geemus/excon/blob/master/lib/excon/connection.rb#L176

    if datum[:body].is_a?(String) # write out string body
      socket.write(request << datum[:body]) # write out request + headers + body

you concat the request string (encoded probably utf-8) with whatever encoding comes in from the body, in my case binary and this probably throws the error.

I think making two calls to socket.write could solve the problem. For now i'am saving the string to a tempfile and pass the file handle to excon .. not very elegant

**Comment by geemus** [comment]
I think this was fixed, but do let me know if you are still seeing issues.

**Comment by schorsch** [comment]
Just recently re-checked my hack and removed it, so the issue is resolved for me, thanks for closing

**Comment by geemus** [comment]
Great, thanks for confirming.
