### ISSUE TITLE
middleware validations

### ISSUE THREAD

**Issue by geemus** [excon/excon#289]
Add `valid_connection_keys` and `valid_request_keys` to middleware base class (and override in children). The params validation in connection should then collect these to do validations, so that the list of valid keys can match the configured middlewares instead of matching just default middlewares.

**Comment by andrew-stripe** [comment]
@geemus: are you still interested in this idea? This would be valuable for me since it would allow for writing middleware that accepts custom parameters. 

I think using this to permit new keys is easy but for it would break backwards compatibility to only accept existing keys that are valid for the configured middleware.

**Comment by geemus** [comment]
@andrew-stripe I'd be open to figuring out something here, though we should perhaps discuss specifics a bit more before you get too far in. I'd prefer not to break backwards compatibility, but I'm not entirely opposed to doing so to progress things. Anyway, happy to discuss further.

**Comment by andrew-stripe** [comment]
Along the lines of your original proposal I'd imagine adding `valid_connection_keys` and `valid_request_keys` to the middleware base class. I would then change the logic in `validate_params` to accept the following keys:
  1. Keys returned by the `valid_*_keys` middleware methods for all the provided middleware that respond to these methods.
  2. Keys referenced by Connection itself (stored in a constant somewhere).

I would also add logic to display a warning for keys that are accepted by the current logic but not actually valid for provided middleware explaining the change and how to fix the warnings.

One question is what to do with the existing `VALID_*_KEYS` constants. Do you consider those part of the public interface such that changing or removing them would be a breaking change?

Overall I think this would be a pretty small change.

**Comment by andrew-stripe** [comment]
Mmm, one wrinkle is the fact that the Idempotent middleware references VALID_REQUEST_KEYS:
https://github.com/excon/excon/blob/8fd633e62a5d305ff76ad1f22f10bf015f4ca1c2/lib/excon/middlewares/idempotent.rb#L32

Couple ideas:
* Provide a different way for middleware to trigger retries (e.g. by raising a specific exception or returning a specific value in the datum). This is nice because it would allow custom middleware to implement retries without duplicating the logic in Idempotent (I'm doing this right now).
* Pass `valid_request_keys` down through the datum so it can be read by Idempotent. This is nice because it's very simple.

**Comment by geemus** [comment]
Thanks for the detailed response (and apologies for my delay in responding).

Your described approach sounds reasonable. I wouldn't really consider those constants to be part of the public interface (certainly not purposefully part of it anyway), so changing it should be ok.

Perhaps we could have the calculated full list (defaults + middleware) as a method on connection. Then in idempotent, it could just refer to `datum[:connection].valid_request_keys` or something like that (since connection is already in the datum). What do you think?

**Comment by andrew-stripe** [comment]
Is there something we should do to ensure that middleware only access the keys they declare? For example, if middleware implements `valid_request_keys` it would get called with a wrapped version of the datum hash that only allows access to the specified keys.

**Comment by geemus** [comment]
Sorry for the delay in response (work-travel last week).

Are there particular cases you are concerned about and/or trying to guard against? I think maybe an example or two would help me grok what you mean (unfortunately I don't think I'm quite imagining it otherwise). Thanks!

**Comment by andrew-stripe** [comment]
For example, imagine two pieces of middleware make use of `:retry_interval`, both are in the default middleware stack but only one correctly declares it as a dependency. If someone removes the piece of middleware that declares the dependency, they'll start getting unexpected issues. Similarly, if a piece of middleware over-declares a dependency a middleware stack could break when that, seemingly innocuous, oversight is fixed.

Does that make sense? Is it worth preventing those sorts issues or not worth the complexity?

**Comment by geemus** [comment]
Yes, I think that does make sense. It might also point to a best practice (though I'm not sure it is worth enforcing), in which you would nest middleware params to provide your own namespace. Presumably that could also avoid this issue.

My inclination would be to wait and see. We can improve this part without explicit handling of this initially and if it turns out to be problematic we can add protections. Conversely, adding them now we might not yet know enough to do it properly and it could be difficult to change or remove in the future.

What do you think?

**Comment by andrew-stripe** [comment]
I think I'm on board with skipping this for now. I noticed that some middleware access parameters that still only make sense when a different middleware is in the stack (e.g. `Instrumentor` accesses `retry_limit` but you still shouldn't pass `retry_limit` unless `Idempotent` is in the stack).

**Comment by andrew-stripe** [comment]
Note that PRs for this will come from @metcalf, my personal account since that's was the easiest place to fork into.

**Comment by geemus** [comment]
Sounds reasonable, cool and thanks for the heads up.

**Comment by geemus** [comment]
I believe this has happened elsewhere.
