### ISSUE TITLE
Release version 1.0.0

### ISSUE THREAD

**Issue by sferik** [excon/excon#295]
Excon turn 4 years old at the end of this month. Many popular gems (notably `fog`) depend on Excon. Seems like it's about time to declare a stable, public API.

From the [SemVer](http://semver.org/) FAQ:

> _How do I know when to release 1.0.0?_
> 
> If your software is being used in production, it should probably already be 1.0.0. If you have a stable API on which users have come to depend, you should be 1.0.0. If you're worrying a lot about backwards compatibility, you should probably already be 1.0.0.

**Comment by geemus** [comment]
@sandstrom good call (looks like the copy didn't work though). Thanks!

**Comment by geemus** [comment]
@sandstrom now I see the rest of the comment. Yes, dropping earlier ruby support makes a ton of sense. I've added the `pinned` tag to a few things that are also candidates for inclusion, but haven't made an explicit 1.0 plan quite yet.

**Comment by pallav-jakhotiya** [comment]
[geemus](https://github.com/geemus) - This is causing an issue based on historical usage of the excon gem in docker-api - https://github.com/upserve/docker-api/pull/589/files - Is there a workaround you could suggest that helps us fix this

**Comment by geemus** [comment]
@pallav-jakhotiya thanks for the heads up. I'll comment over there.
