### ISSUE TITLE
Excon.defaults[:ssl_verify_peer] = false is still verifying local cert

### ISSUE THREAD

**Issue by JoshMcKin** [excon/excon#296]
I have to work with a HTTPS service that has a wack ssl cert. HTTPClient I have to turn off ssl verify for things to work and they do. However in Excon when I turn ssl_verify_peer i still get an SSL error often associated with cert issues. Am i missing something on the setup?

Excon

<pre>
:010 > Excon.defaults[:ssl_verify_peer] = false
 => false 
:011 > opts = {:instrumentor => Excon::StandardInstrumentor}
 => {:instrumentor=>Excon::StandardInstrumentor} 
:012 > client = Excon.new("https://somewackIISwebservice.net/service.aspx", opts)
:013 > client.get()
excon.request  {:chunk_size=>1048576, :ciphers=>"HIGH:!SSLv2:!aNULL:!eNULL:!3DES", :connect_timeout=>60, :debug_request=>false, :debug_response=>false, :headers=>{"User-Agent"=>"excon/0.27.6", "Host"=>"somewackIISwebservice.net:443"}, :idempotent=>false, :instrumentor_name=>"excon", :middlewares=>[Excon::Middleware::ResponseParser, Excon::Middleware::Expects, Excon::Middleware::Idempotent, Excon::Middleware::Instrumentor, Excon::Middleware::Mock], :mock=>false, :nonblock=>true, :omit_default_port=>false, :read_timeout=>60, :retry_limit=>4, :ssl_verify_peer=>false, :tcp_nodelay=>false, :uri_parser=>URI, :write_timeout=>60, :host=>"somewackIISwebservice.net", :path=>"/service.aspx", :port=>443, :query=>nil, :scheme=>"https", :user=>nil, :password=>"REDACTED", :instrumentor=>Excon::StandardInstrumentor, :method=>:get, :retries_remaining=>4, :connection=>#<Excon::Connection:7fe6c591ed90 @data={:chunk_size=>1048576, :ciphers=>"HIGH:!SSLv2:!aNULL:!eNULL:!3DES", :connect_timeout=>60, :debug_request=>false, :debug_response=>false, :headers=>{"User-Agent"=>"excon/0.27.6"}, :idempotent=>false, :instrumentor_name=>"excon", :middlewares=>[Excon::Middleware::ResponseParser, Excon::Middleware::Expects, Excon::Middleware::Idempotent, Excon::Middleware::Instrumentor, Excon::Middleware::Mock], :mock=>false, :nonblock=>true, :omit_default_port=>false, :read_timeout=>60, :retry_limit=>4, :ssl_verify_peer=>false, :tcp_nodelay=>false, :uri_parser=>URI, :write_timeout=>60, :host=>"mspservice.secureconduit.net", :path=>"/loanlookup.aspx", :port=>443, :query=>nil, :scheme=>"https", :user=>nil, :password=>nil, :instrumentor=>Excon::StandardInstrumentor} @socket_key="https://somewackIISwebservice.ne:443">, :stack=>#<Excon::Middleware::ResponseParser:0x007fe6c59227d8 @stack=#<Excon::Middleware::Expects:0x007fe6c5922828 @stack=#<Excon::Middleware::Idempotent:0x007fe6c5922850 @stack=#<Excon::Middleware::Instrumentor:0x007fe6c5922878 @stack=#<Excon::Middleware::Mock:0x007fe6c59228a0 @stack=#<Excon::Connection:7fe6c591ed90 @data={:chunk_size=>1048576, :ciphers=>"HIGH:!SSLv2:!aNULL:!eNULL:!3DES", :connect_timeout=>60, :debug_request=>false, :debug_response=>false, :headers=>{"User-Agent"=>"excon/0.27.6"}, :idempotent=>false, :instrumentor_name=>"excon", :middlewares=>[Excon::Middleware::ResponseParser, Excon::Middleware::Expects, Excon::Middleware::Idempotent, Excon::Middleware::Instrumentor, Excon::Middleware::Mock], :mock=>false, :nonblock=>true, :omit_default_port=>false, :read_timeout=>60, :retry_limit=>4, :ssl_verify_peer=>false, :tcp_nodelay=>false, :uri_parser=>URI, :write_timeout=>60, :host=>"mspservice.secureconduit.net", :path=>"/loanlookup.aspx", :port=>443, :query=>nil, :scheme=>"https", :user=>nil, :password=>nil, :instrumentor=>Excon::StandardInstrumentor} @socket_key="https://mspservice.secureconduit.net:443">>>>>>}
excon.error  {:error=>#<Excon::Errors::SocketError: SSL_connect SYSCALL returned=5 errno=0 state=SSLv2/v3 read server hello A (OpenSSL::SSL::SSLError)>}
Excon::Errors::SocketError: SSL_connect SYSCALL returned=5 errno=0 state=SSLv2/v3 read server hello A (OpenSSL::SSL::SSLError)
</pre>

HTTPCLient successful

<pre>
:007 > pool = HTTPClient.new
:008 > pool.ssl_config.verify_mode = OpenSSL::SSL::VERIFY_NONE
:009 > pool.get("https://somewackIISwebservice.aspx")
at depth 0 - 20: unable to get local issuer certificate
 => # Some valid response </pre>

**Comment by bjm88** [comment]
For anyone researching while using Savon SOAP client that using Excon as http adapter, I found I had to set Savon config ssl_verify_mode: :none  and the Excon config Excon.defaults[:ssl_verify_peer] = false for host verification to actually not happen.
