### ISSUE TITLE
connection pooling?

### ISSUE THREAD

**Issue by geemus** [excon/excon#330]
This has come up a few times as something that might be desirable for us to own/manage. That said it might make more sense to create an additional excon-pool gem (or something) where this additional stuff could live, instead of having those concerns mixed in here. Just wanted to dump this from my brain for comment.

**Comment by geemus** [comment]
This came back up, see also: https://github.com/aceofsales/faraday_persistent_excon

**Comment by rainerborene** [comment]
Any progress on this? That would be useful specially that `fog-aws` gem uses `excon` under the hood. Take sending mass e-mails (via SES) for example having a pool of persistent connections would improve performance.

**Comment by JoshMcKin** [comment]
@rainerborene see  https://github.com/excon/excon/pull/446

I've been running it in production for while with [HotTub](https://github.com/JoshMcKin/hot_tub) on some Rails apps that make a ton of different API call without issue.

**Comment by colin-jack** [comment]
I wondered if there had been any progress on this as it seems like it would be useful.

**Comment by geemus** [comment]
Afraid there is none that I'm aware of.

**Comment by JoshMcKin** [comment]
@colin-jack what more where you looking for?
