### ISSUE TITLE
session/cookies

### ISSUE THREAD

**Issue by geemus** [excon/excon#332]
I feel like this is a bit more of a stretch, especially given that most usage is for API (that I'm aware of at least). That said, if you are doing other things with it, perhaps doing some basic cookie stuff is of high value. This might still belong in a separate excon-sessions gem or something.

**Comment by geemus** [comment]
Not going to worry about sessions. May merge some stuff for cookies though (see #550)

**Comment by adam-koblentz** [comment]
I wish you were right and no APIs used cookies, but here I am looking for a better rest/net gem and stuck using an API that uses cookies.

**Comment by geemus** [comment]
I've never really implemented cookie-handling, what features would you be looking for to support this use case? (presumably nothing already here precludes using the cookies, it just wouldn't work without additional, manual effort). Thanks!
