### ISSUE TITLE
Provide support for multipart/form-data and multipart/x-www-form-urlencoded

### ISSUE THREAD

**Issue by geemus** [excon/excon#353]

**Comment by JoshMcKin** [comment]
I'm not providing anything useful here other than to say I would really like this too.

**Comment by croeck** [comment]
I would love to see that feature in Excon.

@geemus The interface could consist of multiple alternative approaches:

1. Auto-detect file contents (by class / behavior) and submit those requests as multipart content
2. Force to send the message as multipart content when a `multipart: true` option is explicitly provided
3. Allow to set a custom `boundary` in the options
4. A dedicated class, similar to the `UploadIO` class of [multipart-post](https://github.com/nicksieger/multipart-post) to specify the request contents in detail

As far as I am concerned, this could cover most scenarios.

**Comment by geemus** [comment]
Hmm, yeah. I would be a little reticent about the auto-detect stuff (seems easy to break/mess up), or at least I would prefer to have it opt-in at first and we can switch to auto if we grow comfortable with it.

At least as a first pass I guess I would lean toward opting in (like 2). We could maybe do 3 eventually, but I probably wouldn't worry about it at first. Similarly, I'm not sure how much we would gain from 4, but am open to discussing.

P.S. Here is a gist I wrote a while back that does multipart (or at least used to work once-upon-a-time): https://gist.github.com/geemus/8198572 should be a decent starting point and/or workaround should anybody need it.

**Comment by andrewfader** [comment]
+1

**Comment by geemus** [comment]
I would still be happy to support work on this, if someone is interested. But given the relative lack of activity, guessing we can safely close for now. Thanks!

**Comment by thiagotrentin** [comment]
Hey @geemus, is there a way to upload a file in form-data using Excon?

**Comment by geemus** [comment]
@thiagotrentin it's possible, but you have to do your own encoding. This gist was how I did it (once upon a time, but the encoding method shouldn't be different): https://gist.github.com/geemus/8198572

**Comment by andrewfader** [comment]
I'd be interested to pair with someone on doing it. I wouldn't know how to get started, but I think I understand what it is supposed to do, if I knew where it was supposed to go and how to write a test for it working properly. I have always had trouble stubbing out things like multipart file upload or SMTP attachments or whatever.

**Comment by geemus** [comment]
@andrewfader I'm happy to support you through the process. I think. I'll reopen this issue so we can discuss. I think a great starting point would be for you to outline what you think a good interface for using this feature might look like. Once we settle on that, we can ascertain where it might fit well and how to build testing around it also. What do you think?

**Comment by thiagotrentin** [comment]
> @thiagotrentin it's possible, but you have to do your own encoding. This gist was how I did it (once upon a time, but the encoding method shouldn't be different): https://gist.github.com/geemus/8198572

Hi @geemus, I followed your suggestion and it seems to work until I had to send a xlsx file and got different kinds of conversion errors.

I tried to do another workaround but it didn't worked for me.

Do you still have any plans for this feature?

I tried to use the multipart-post (https://github.com/socketry/multipart-post) gem and I think it works, what do you think about it?

**Comment by geemus** [comment]
Sorry to hear you ran into issues. What sort of conversion errors were you seeing?

I don't have any explicit and/or near term plans on this, due to time constraints. But I'm happy to support/review if someone else wanted to work on something here.

I don't have any experience with multipart-post, but if it's working for you that sounds great!

**Comment by davispuh** [comment]
For now I just did it manually

```ruby
def build_formdata(filename, file, content_type, fields = {})
    boundary = '-' * 30 + SecureRandom.hex(15)

    body = ''
    fields.each do |name, value|
        body = "--#{boundary}" + Excon::CR_NL
        body << %{Content-Disposition: form-data; name="#{name}"} << Excon::CR_NL << Excon::CR_NL
        body << value << Excon::CR_NL
    end

    body << "--#{boundary}" << Excon::CR_NL
    body << %{Content-Disposition: form-data; name="filename"; filename="#{filename}"} << Excon::CR_NL
    body << "Content-Type: " << content_type << Excon::CR_NL << Excon::CR_NL
    body << file.read << Excon::CR_NL
    body << "--#{boundary}--" << Excon::CR_NL

    [body, %{multipart/form-data; boundary=#{boundary}}]
end
```

Note that RFC 2046 allows to quote `boundary` in `Content-Type` header but server I was uploading file to didn't support that and didn't work.

**Comment by geemus** [comment]
@davispuh Thanks for sharing and sorry it wasn't already available. It hasn't been something I needed directly, and seemed like it might have a lot of caveats (ie folks interpreting/implementing the spec differently). Plus I hadn't heard a lot of demand from others for it, so it wasn't something I'd really prioritized.

I'd be open to supporting someone that had the need and wanted to work on an implementation, otherwise it's probably still going to be hard for me to find time and energy for at present.

**Comment by davispuh** [comment]
No worries it's been over 10 years lmaoo and yeah looks like not that many people need something like this.
