### ISSUE TITLE
stack level too deep when using RedirectFollower

### ISSUE THREAD

**Issue by eljojo** [excon/excon#354]
Hi,
when running (with Excon 0.31.0)

``` ruby
middlewares = Excon.defaults[:middlewares] + [Excon::Middleware::RedirectFollower]
url = "http://partners.webmasterplan.com/click.asp?ref=620249&site=7163&type=text&tnb=7&diurl=http://www.buerostuhl24.com/topstar-sitzball-hocker-sitness-half-ball-netz-silber-blau.33360.html"
Excon.get(url, middlewares: middlewares)
```

I get a `SystemStackError: stack level too deep` error message.

The url works fine with `curl -I -L` and with a patched `open-uri` using `open(url).read` gem.

I'm not really sure what might be the cause, but I'm posting it here in case it can help the developers.

Maybe worth noting that I have the `newrelic_rpm` gem installed, which adds the middleware `Excon::Middleware::NewRelicCrossAppTracing`

**Comment by greysteil** [comment]
I'm seeing this with another URL: https://heynemann.github.com/pyvows

**Comment by geemus** [comment]
When I (finally) get around to cutting a v1.0.0, I'll almost assuredly change `:omit_default_port` to be true by default (instead of false by default as it is presently), which will likely avoid this and some related issues. Not sure on my timeline for that exactly, have not had much luck finding time to focus on getting that done.

**Comment by greysteil** [comment]
👍 in this case I have that set, so something else is going on.

Really appreciate everything you do on Excon! If you have an idea for a strategy for a general fix here (presumably passing previous redirects around and checking for circularity) let me know and I can take a look at a fix.

**Comment by geemus** [comment]
Good question. Circularity checking feels like it might be complex, and maybe more trouble than it would be worth (especially given that this doesn't seem to come up super frequently). A simpler approach might be to adopt something similar to the idempotent middleware, where we would count how many times we have passed through the middleware and bail once we reach a configurable limit. It should be less complex, but probably work more or less as-well if configured properly. What do you think?

**Comment by greysteil** [comment]
Sounds perfect - I'll put together a PR.
