### ISSUE TITLE
Excon::Utils#query_string should convert array parameter properly

### ISSUE THREAD

**Issue by omikronn** [excon/excon#360]
Say, I need to do some request to some API, where some query parameters look like `param[]=value1&param[]=value2`. If I send a hash of the form `{ param: [value1, value2] }`, `Excon::Utils#query_string` will convert this to `&param=value1&param=value2` where effectively only `value2` will be taken into consideration.

I have a tested patch for this (really, just a couple of lines of code).
What do you guys think? Would this make a nice addition?

**Comment by sodabrew** [comment]
Would you be amenable to importing this module from HTTParty?
https://github.com/jnunemaker/httparty/blob/master/lib/httparty/hash_conversions.rb
http://www.rubydoc.info/github/jnunemaker/httparty/HTTParty/HashConversions.to_params

**Comment by geemus** [comment]
Hmm. I think the bigger question we had above wasn't how to get it working (it could be done in the current codebase with maybe 2 lines changed), but more if that should be the default behavior and/or if it should be configurable/toggleable. Unfortunately, I suspect it would take a good deal more code (and complexity) to support the more flexible version of this.

Perhaps we should just do it this way though, it seems a quite common pattern, but I wouldn't say it is universal. Similarly as an end user, I think you can already get this behavior by just naming the key that you know has an array as `key[]`, if I'm not mistaken. So in that sense it should already be workable, assuming it is straightforward to know which values will be arrays. Does that help/make sense?

**Comment by sodabrew** [comment]
The module from HTTParty also encodes `{:foo => { :bar => 'val', :qux => 'val' } }` as `foo[bar]=val&foo[qux]=val`, which is typical of HTTP form encoding. Let me try out `{ 'foo[]' => ['val1', 'val2'] }` though. I'll look into a PR to add tests for these to https://github.com/excon/excon/blob/master/tests/query_string_tests.rb

**Comment by geemus** [comment]
Yeah. I think my hesitation is just that it is a de facto standard (not from an RFC), so it may be common, but I don't think it is official and I'm not at all certain it is universal. So forcing it as the default might be bad (and is probably a breaking change). If specifying it explicitly works as we suspect and we added tests, it seems like that might be a nice compromise for now anyway. Thanks!

**Comment by sodabrew** [comment]
PR for array elements. Hash elements are not handled at all, so that's certainly a deficiency of the current code. Included a test for such mangling.

**Comment by geemus** [comment]
True, I guess I hadn't run into nested hashes as much.
