### ISSUE TITLE
Process hangs on SSL connection

### ISSUE THREAD

**Issue by alexgpg** [excon/excon#364]
Hi. I have a problem with connect using SSL.

Sometimes hangs process on connect to http server with SSL.

Using strace i found:
strace output:
last syscall(no return)
>
> ppoll([{fd=27, events=POLLIN}], 1, NULL, NULL, 8
>

In this state process wait 3 days.

Code with ppoll call from OpenSSL::SSL::SSLSocket#connect in https://github.com/geemus/excon/blob/master/lib/excon/ssl_socket.rb#L77

Excon::SSLSocket use blocking connect and sometimes(on network failure) process hangs.

Timeouts for connect and request (@data[:*_timeout]) not using for this call.

**Comment by geemus** [comment]
I think this may have just been fixed on master (if not some time in between when this was reported and now). So you may want to update/try again if it is relevant. In any event, going to close this due to inactivity. Please let me know if you have questions.
