### ISSUE TITLE
Excon doesn't work with :uri_parser  => Addressable::URI

### ISSUE THREAD

**Issue by dentarg** [excon/excon#384]
Just wanted to let you know about this (and help others who stumble upon the same error).

Excon doesn't work with `:uri_parser  => Addressable::URI`, here's the error:

``` ruby
[1] pry(main)> require 'excon'
=> true
[2] pry(main)> require 'addressable/uri'
=> true
[3] pry(main)>
[4] pry(main)> url = "http://www.google.com"
=> "http://www.google.com"
[5] pry(main)>
[6] pry(main)> connection = Excon.new(
[6] pry(main)*   url,
[6] pry(main)*   :uri_parser  => Addressable::URI,
[6] pry(main)* )
=> #<Excon::Connection:7fe7e1ca2850 @data={:chunk_size=>1048576, :ciphers=>"HIGH:!SSLv2:!aNULL:!eNULL:!3DES", :connect_timeout=>60, :debug_request=>false, :debug_response=>false, :headers=>{"User-Agent"=>"excon/0.33.0"}, :idempotent=>false, :instrumentor_name=>"excon", :middlewares=>[Excon::Middleware::ResponseParser, Excon::Middleware::Expects, Excon::Middleware::Idempotent, Excon::Middleware::Instrumentor, Excon::Middleware::Mock], :mock=>false, :nonblock=>true, :omit_default_port=>false, :persistent=>false, :read_timeout=>60, :retry_limit=>4, :ssl_verify_peer=>true, :tcp_nodelay=>false, :uri_parser=>Addressable::URI, :write_timeout=>60, :host=>"www.google.com", :path=>"", :port=>nil, :query=>nil, :scheme=>"http", :user=>nil, :password=>nil} @socket_key="http://www.google.com">
[7] pry(main)> connection.get
Excon::Errors::SocketError: Can't assign requested address - connect(2) (Errno::EADDRNOTAVAIL)
from /Users/dentarg/.gem/ruby/2.0.0/gems/excon-0.33.0/lib/excon/socket.rb:202:in `connect_nonblock'
```

It's becuase `Addressable::URI.parse` doesn't return the port number as `URI.parse` does.

``` ruby
[9] pry(main)> URI.parse(url).port
=> 80
[10] pry(main)>
[11] pry(main)> Addressable::URI.parse(url).port
=> nil
```

This was deliberately choice by addressable, see https://github.com/sporkmonger/addressable/issues/90. Faraday seems to have the same problem: https://github.com/lostisland/faraday/issues/318

**Comment by sandstrom** [comment]
Just wanted to chime in and say that Excon is a dream to use, so in general I'm super-happy with it :smile: 

But I also hit this issue just now. The fix is easy of course, but Excon would be even more pleasant to use if this would work smoother :)

**Comment by geemus** [comment]
@sandstrom glad you like it. Definitely would be nice if this wasn't the case. I think at some point I want to change it to handle ports a bit differently anyway (ie leave them out by default for inferred, similar to what Addressable::URI already does). But swapping that default feels like it falls into the breaking change category, so has given me some pause so far.

**Comment by sandstrom** [comment]
@geemus understand, this isn't a biggie. Excon is awesome overall!

**Comment by djberg96** [comment]
@geemus Ran into this today while tinkering. Would like to see it addressed. :)

**Comment by geemus** [comment]
I think [this](https://github.com/excon/excon/commit/44a4268f8ddc800fa4b70feb220255e4b6bfa187) will fix it, would love some testing before I release it though. Should be safe, but one never knows.

**Comment by djberg96** [comment]
@geemus 👍

**Comment by sandstrom** [comment]
@geemus Works! 🏅

**Comment by geemus** [comment]
@sandstrom thanks for confirming!
