### ISSUE TITLE
Timeout in lib/excon/socket.rb:207

### ISSUE THREAD

**Issue by kaluznyo** [excon/excon#407]
Hi, 

Don't know why, since yesterday, we get a lot of 'Connection timed out - connect(2) for 178.236.4.224:443 (Errno::ETIMEDOUT)' with any kind of request (delete, post, copy..)
We use paperclip (4.2). And we try with excon 0.37 and 0.38). We upload on S3 (europe)

I know this issue is very large. But any idea to see more information. S3 seems OK, and we change nothing in our code.

I try to add this : 

Excon.defaults = Excon.defaults.merge(write_timeout: 10.minutes) But no effect.

The log : https://gist.github.com/kaluznyo/2ee6de7a5253932b3146

**Comment by geemus** [comment]
closing as old/inactive, please let me know if this is still an issue.
