### ISSUE TITLE
Unknown protocol (OpenSSL::SSL::SSLError) after redirect to SSL

### ISSUE THREAD

**Issue by jarthod** [excon/excon#453]
Hi,

While comparing `em-http-request`, `excon` and `typhoeus` for my project, I think I found a bug related to redirection following & SSL.

Here is how to reproduce it:
```ruby
require 'excon'
Excon.defaults[:middlewares] << Excon::Middleware::RedirectFollower
response = Excon.head('http://relaterocket.co')
puts "complete #{response.status}"
```

And here is the exception I got:
```
excon-0.42.1/lib/excon/ssl_socket.rb:121:in `connect_nonblock': SSL_connect returned=1 errno=0 state=unknown state: unknown protocol (OpenSSL::SSL::SSLError) (Excon::Errors::SocketError) (Excon::Errors::SocketError)
  from excon-0.42.1/lib/excon/ssl_socket.rb:121:in `block in initialize'
  from timeout.rb:91:in `block in timeout'
  from timeout.rb:35:in `block in catch'
  from timeout.rb:35:in `catch'
  from timeout.rb:35:in `catch'
  from timeout.rb:106:in `timeout'
  from excon-0.42.1/lib/excon/ssl_socket.rb:117:in `initialize'
  from excon-0.42.1/lib/excon/connection.rb:380:in `new'
  from excon-0.42.1/lib/excon/connection.rb:380:in `socket'
  from excon-0.42.1/lib/excon/connection.rb:105:in `request_call'
  from excon-0.42.1/lib/excon/middlewares/base.rb:15:in `request_call'
  from excon-0.42.1/lib/excon/middlewares/mock.rb:47:in `request_call'
  from excon-0.42.1/lib/excon/middlewares/instrumentor.rb:22:in `request_call'
  from excon-0.42.1/lib/excon/middlewares/base.rb:15:in `request_call'
  from excon-0.42.1/lib/excon/middlewares/base.rb:15:in `request_call'
  from excon-0.42.1/lib/excon/middlewares/base.rb:15:in `request_call'
  from excon-0.42.1/lib/excon/connection.rb:232:in `request'
  from excon-0.42.1/lib/excon/middlewares/redirect_follower.rb:37:in `response_call'
  from excon-0.42.1/lib/excon/middlewares/base.rb:19:in `response_call'
  from excon-0.42.1/lib/excon/middlewares/instrumentor.rb:30:in `response_call'
  from excon-0.42.1/lib/excon/middlewares/base.rb:19:in `response_call'
  from excon-0.42.1/lib/excon/middlewares/expects.rb:13:in `response_call'
  from excon-0.42.1/lib/excon/middlewares/response_parser.rb:8:in `response_call'
  from excon-0.42.1/lib/excon/connection.rb:365:in `response'
  from excon-0.42.1/lib/excon/connection.rb:235:in `request'
  from excon-0.42.1/lib/excon.rb:226:in `head'
  from ./excon_bug.rb:3:in `<main>'
```

This it working fine with `typhoeus/curl`, here is the curl output:
```
$> curl -LI http://relaterocket.co
HTTP/1.1 302 Found
Cache-Control: no-cache
Content-length: 0
Location: https://relaterocket.co/
Connection: close

HTTP/1.1 200 OK
Server: nginx
Date: Sat, 27 Dec 2014 14:13:14 GMT
Content-Type: text/html
Content-Length: 4147
Last-Modified: Tue, 02 Dec 2014 04:40:10 GMT
Vary: Accept-Encoding
ETag: "547d42aa-1033"
Accept-Ranges: bytes
Strict-Transport-Security: max-age=31536000; includeSubDomains

```
The HEAD request with `excon` works fine to `https://relaterocket.co` directly though, that's why I think the issue is related to the redirection following middleware.

Anyway thanks for your work on `excon`, very nice library.
:christmas_tree: Merry Christmas

**Comment by geemus** [comment]
Hmm. If I do the head WITHOUT redirect follower I get a bit different data, in particular it appears the location header shows up as "https://relaterocket.co:80/". I suspect the port 80 there is the culprit, but I'm not sure why curl wouldn't report this also. I don't think it should be inserting it if it were not already there, but I could be wrong. Could the server be misconfigured in such a way that it might be erroneously including this?

**Comment by jarthod** [comment]
Indeed the :80 doesn't look good, but it is definitely not returned by the server:
```
> echo -e "HEAD / HTTP/1.1\r\nHost: relaterocket.co\r\n" | nc relaterocket.co 80
HTTP/1.1 302 Found
Cache-Control: no-cache
Content-length: 0
Location: https://relaterocket.co/
Connection: close
```

**Comment by geemus** [comment]
ah, BUT:

```
 ❯ echo -e "HEAD / HTTP/1.1\r\nHost: relaterocket.co:80\r\n" | nc relaterocket.co 80
HTTP/1.1 302 Found
Cache-Control: no-cache
Content-length: 0
Location: https://relaterocket.co:80/
Connection: close
```

So, I'm somewhat in the wrong including the port in the initial request and the server is somewhat wrong including it in the response. I think you should be able to workaround this via setting `omit_default_port => true` in the options (or defaults). I suspect this will be the default in the future, but backwards compatibility concerns have made that transition slow. Sorry for the confusion, this choice from long ago continues to haunt me, so I'll be glad to be done with it. Thanks!

**Comment by jarthod** [comment]
I see, this should definitely be the default.
And yes, the server response is quite stupid ;)

**Comment by geemus** [comment]
Yeah, hopefully we can change that default soon. According to specs it is supposed to be safe to include (or not), so I thought at the time it would be nice to keep it simple and just always include it. Unfortunately, lots of servers behave differently when it is present (or not), among other things, which ended up being a big pain...

**Comment by jarthod** [comment]
Yep, I Know how fucked up servers are, as I'm working on https://updown.io ;)

**Comment by geemus** [comment]
Haha, yeah that would do it. Very finicky servers, I'm sometimes amazed the internet works half as well as it does...
