### ISSUE TITLE
RedirectFollower redirect limit

### ISSUE THREAD

**Issue by Paxa** [excon/excon#454]
What is a right way to limit redirect count?

I could make it only by making other middleware:

``` ruby
# config/initializers/excon.rb

require "excon/middlewares/redirect_follower"

Excon::VALID_REQUEST_KEYS     << :redirect_request_number
Excon::VALID_CONNECTION_KEYS  << :redirect_request_number

Excon::VALID_REQUEST_KEYS     << :redirect_count_limit
Excon::VALID_CONNECTION_KEYS  << :redirect_count_limit

class Excon::RedirectLimitExceed < Exception
end

class Excon::Middleware::RedirectFollowerLimited < Excon::Middleware::RedirectFollower
  def response_call(datum)
    _, location = datum[:response][:headers].detect do |key, value|
      key.casecmp('Location') == 0
    end

    if location
      Rails.logger.info "Following redirect: #{location}"
    end

    datum[:redirect_request_number] ||= 0
    datum[:redirect_request_number] += 1
    if datum[:redirect_count_limit] && datum[:redirect_request_number] > datum[:redirect_count_limit]
      message = "Redirect limit reached. Request count: #{datum[:redirect_request_number]}, redirect url: #{location}"
      raise Excon::RedirectLimitExceed, message
    end
    super(datum)
  end
end

# run as:
Excon.post("http://google.com", middlewares: Excon.defaults[:middlewares] + [Excon::Middleware::RedirectFollowerLimited])
```

**Comment by geemus** [comment]
Good question. It hadn't really come up before, but I suspect we could/should add something similar to how retries work with idempotent (and perhaps also default to something like 3). What do you think?

**Comment by Paxa** [comment]
If it were up to me, I would add this feature to `Excon::Middleware::RedirectFollower`.
But it feels not so right to add `redirect_request_number` in valid keys, because it's not suppose to be configured. Or may be it could be useful in some cases to access it in response object.

**Comment by geemus** [comment]
@Paxa hmm. I don't know, I feel like there might be valid reasons to configure it. ie if we choose 3 as the default, there might be a case where it was 4 and a person wanted to make a special exception or something. In any event I wouldn't think it would be harmful to make it configurable. What do you think?

**Comment by Paxa** [comment]
Can be... anyway I think it's harder to make it not configurable.

**Comment by geemus** [comment]
There hasn't been much demand, so not going to worry about this for now, especially as it's easy enough to just use a custom middleware for this purpose if needed.
