### ISSUE TITLE
Excon warning when creating connection with :debug => true

### ISSUE THREAD

**Issue by mikegrassotti** [excon/excon#458]
Following instructions in the README ran into the following: 

    $ irb
    > require 'excon'
    true
    > RUBY_VERSION
    "2.1.3"
    > Excon::VERSION
    "0.43.0"    
    > connection = Excon.new('http://geemus.com/', :debug => true)
    [excon][WARNING] Invalid Excon connection keys: "debug"
    ....

FWIW I'm able to use ENV['EXCON_DEBUG'] as an alternative.

**Comment by geemus** [comment]
Ah, yeah. We actually split up debugging to allow you to specify either request or response debugging (or both). So when you use that ENV_VAR it happens to set both. Unfortunately it seems we failed to update docs when we did that. Perhaps we should include both options here to emulate that same behavior. You can see what the ENV_VAR does here: https://github.com/excon/excon/blob/ace8be1a35a203ae4dcee2f87ac837403809d64e/lib/excon/connection.rb#L67

Would you be up for a quick patch to help us out on the doc front? Thanks!
