### ISSUE TITLE
Unable to verify certificate (Windows 7) - where to specify path to certificates?

### ISSUE THREAD

**Issue by smashind** [excon/excon#470]
Hi,

I just updated my certificates on Windows 7 following these instructions here: https://gist.github.com/fnichol/867550

And now my SSL_CERT_FILE is at C:\RailsInstaller\cacert.pem

Now I"m getting the dreaded:

Unable to verify certificate, please set `Excon.defaults[:ssl_ca_path] = path_to_certs`, `ENV['SSL_CERT_DIR'] = path_to_certs`, `Excon.defaults[:ssl_ca_file] = path_to_file`, `ENV['SSL_CERT_FILE'] = path_to_file` or `Excon.defaults[:ssl_verify_peer] = false` (less secure).

When trying to do an update method with images (carrierwave). 

I've tried to change the defaults like the error message recommends above but nothing seems to work (maybe I'm doing it in the wrong place?)

I've edited excon\constants.rb

- tried adding Excon.defaults['SSL_CERT_FILE'] = 'C:\RailsInstaller\cacert.pem'
- tried adding :ssl_ca_path to the defaults 
- tried changing :ssl_verify_peer to false

None of those things worked. 

I tried adding Excon.defaults['SSL_CERT_FILE'] = 'C:\RailsInstaller\cacert.pem' to my app's config\environment\test.rb and config\environment\development.rb 

That didn't work either. 

My question would be where specifically do I add :ssl_verify_peer to false or the Excon.defaults in an app? I am clearly adding them in the wrong places but I'm out of ideas. 

This only happens locally by the way. Thanks for your help.

**Comment by smashind** [comment]
I managed to resolve this by adding:

Excon.defaults[:ssl_verify_peer] = false

to the controller that was having trouble.

**Comment by geemus** [comment]
Yeah, the ENV var values are UPPERCASE_UNDERSCORED, but the default values are :lowercase_symbols. If you mix them up I can see how it might not work. Setting `Excon.defaults[:ssl_ca_file]` is preferred to `Excon.defaults[:ssl_verify_peer] = false`, as turning off peer verification allows for man-in-the-middle attacks to occur.
