### ISSUE TITLE
Memory leak when used in EventMachine defer

### ISSUE THREAD

**Issue by philayres** [excon/excon#477]
I created an issue for the Fog gem which uses Excon under the covers, as I thought it was leaking memory when used in EventMachine within a defer block. But now I'm tracing things down deeper I seem to find that Excon is really where something odd is happening. Or at least the way its working within EventMachine threads. Or my incorrect usage maybe?

To show the problem, take a look at the gist here (you only need the em_server_excon.rb and Gemfile files): https://gist.github.com/philayres/2af8f67edbaf4470744a

The EventMachine server just handles a TCP request on port 9999. On startup it calls Excon to connect to a website. For every TCP request it gets a page from the Excon connected website. This replicates what the Fog gem is doing when it calls a cloud service.

Playing with the EM.threadpool_size in EM.run has a profound effect on how fast memory grows. Therefore I think that EventMachine threads and Excon are not playing fair.

With a threadpool of 20 (the default), using one thread at a time seems to leak memory heavily. Hammering the server, so that all threads are active seems to cause the memory to top out after a while. With a threadpool of 5 (low concurrency), we get a higher top end to the memory.

It is easy to demonstrate: browse to http://localhost:9999/

 - wait for it to return (not found, as the response is not real HTTP) then repeat, etc, a few times
 - then hold F5 to force tons of refreshes. Memory limits (drops even)
 - Then repeat by some slow refreshes, one at a time and the memory grows again 

(note - the browser actually makes more than one request sometimes, I think when it attempts to pull things like the site icon, etc)

In my case, with a threadpool of 20, after 5 refreshes I get memory usage of about 48M. After a while I get to well over a 100M. With a threadpool of 5, after 5 refreshes I get a memory usage of about 32M, and it grows more slowly.

So I understand that having multiple threads has an impact on resources, but it seems that something (Excon or my poor use of it following the Fog model) is not clearing up, and perhaps is only releasing memory from a previous request when the same thread is reused again in the future. I have tried to force a GC.start after every request and this seems to have no effect. Just having the server sitting inactive doesn't reduce memory, so I'm not thinking its a GC issue.

What could be causing Excon + EventMachine to work together in such a way? I'm happy to help with more testing, I'm just at a loss as to where to look next.

**Comment by philayres** [comment]
Oops - it seems that my debugging was actually causing the issue. 
Doing an `.inspect` on a large Excon result causes the amount of memory consumed to explode. My apologies for the spam. Please ignore this issue.

BTW - Excon is great! Thanks for your hard work on this gem.

**Comment by geemus** [comment]
You are quite welcome, sorry to hear about the difficulty and glad you were able to narrow down causes. I haven't heard about many event machine related issues, but I also don't use it myself in this way, so it may just be anecdotally ok.
