### ISSUE TITLE
sslv3 alert handshake failure

### ISSUE THREAD

**Issue by mahemoff** [excon/excon#478]
I'm seeing this new SSL issue:

```
> Excon.new('https://www.joelosteen.com').get
Excon::Errors::SocketError: SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: sslv3 alert handshake failure (OpenSSL::SSL::SSLError) from /Users/rb/.rvm/gems/ruby-2.2.0-preview1/gems/excon-0.44.2/lib/excon/ssl_socket.rb:121:in `connect_nonblock'
```

I noticed the same URL works okay in curl. `Excon.defaults[:ssl_verify_peer] = false` has no effect.

I was able to fix it by switching to the non-http URL, but wondering if there's a general fix.

**Comment by geemus** [comment]
I'm not sure off hand. Do you know if it was introduced by updating excon or perhaps openssl? I know some other folks are having issues with particular versions of openssl that a downgrade fixed, though it manifested differently so it may be unrelated, still might be worth a peek: https://github.com/excon/excon/issues/467

**Comment by mahemoff** [comment]
Gemfile history indicates 0.40 was being used, which had the same error, so I don't think it's a recent Excon update. I don't believe openssl was updated on the machines I've tested this on. I guess it was a change in the remote server that triggered this.

**Comment by geemus** [comment]
I suppose the remote server might be set to do TLS only or something, I've had a rather hard time getting the ssl version negotiation to play nice in all cases. You may need to explicitly set the version instead of relying on negotiation in this case. At a guess anyway...

**Comment by mahemoff** [comment]
I see, thanks. How to set it explicitly?

**Comment by geemus** [comment]
You can set :ssl_version on a particular request (or in the defaults).

**Comment by troy** [comment]
If it helps anyone else who runs into this OpenSSL exception, I've seen this with SNI endpoints (where the cert doesn't present any CNs in its in initial reply). [This](http://stackoverflow.com/questions/4685736/openssl-server-name-indication-support-in-nethttp) may be relevant, though I stopped when I found the problem.

**Comment by geemus** [comment]
@troy cool, thanks for the heads up!

**Comment by yoshdog** [comment]
Im getting the same error when using fakes3... did you manage to find the cause @mahemoff ?

**Comment by mahemoff** [comment]
I didn't @yoshdog

**Comment by yoshdog** [comment]
So I have tried setting the following Excon.defaults[:ssl_version]

## SSLv23

```
Excon.defaults[:ssl_version] = :SSLv23
Excon::Errors::SocketError: SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: unknown protocol (OpenSSL::SSL::SSLError)
from /Users/yoshi/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/excon-0.45.3/lib/excon/ssl_socket.rb:120:in `connect_nonblock'
```

### SSLv3, TLSv1, TLSv1_2, TLSv1_1
```
Excon.defaults[:ssl_version] = :SSLv3
Excon::Errors::SocketError: SSL_connect returned=1 errno=0 state=SSLv3 read server hello A: wrong version number (OpenSSL::SSL::SSLError)
from /Users/yoshi/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/excon-0.45.3/lib/excon/ssl_socket.rb:120:in `connect_nonblock'
```

**Comment by ParthBarot-BoTreeConsulting** [comment]
Regarding this - http://stackoverflow.com/questions/29656452/aws-s3-disabling-sslv3-support - If I want to disable SSLv3 and use only TLS1/1.1 etc for Amazon AWS, How can we do that?

I assume we can't set it as default value, for all the requests. Because that may break many other requests.

Please suggest.

**Comment by geemus** [comment]
fog connections accept a `:connection_options` key with a hash value, any data for that should get passed into just that connection. This should allow for only fog to use a particular setting, such as this. I don't think you'll need to explicitly disable SSLv3, if you specify a particular version I believe it will only allow that particular version to be used.

**Comment by bmishkin** [comment]
I was able to resolve this error by updating excon (0.16.1 -> 0.45.3)

**Comment by geemus** [comment]
@bmishkin thanks for the update!

**Comment by mahemoff** [comment]
After seeing same issue with curl (), I see this issue seems to be related to the available ciphers and may be fixed by restricting the available ciphers. Something like `conn = Excon.new url, ciphers: 'something something'. I haven't figured out the details though.

Based on https://bugs.launchpad.net/ubuntu/+source/openssl/+bug/861137/comments/6 and the page it links to, http://blog.techstacks.com/2008/09/securing-ssl-in-tomcat-part-two.html

**Comment by geemus** [comment]
Our default for ciphers is `'HIGH:!SSLv2:!aNULL:!eNULL:!3DES'` fwiw, so something in there may be off.

**Comment by mahemoff** [comment]
I eventually figured this out. It came down to OpenSSL on Ubuntu missing TLS 1.2, so required rebuilding OpenSSL.

https://stackoverflow.com/questions/32360487/how-to-fetch-this-url-getting-ssl-handshake-error
https://askubuntu.com/questions/475670/how-to-build-curl-with-the-latest-openssl/582104#comment966406_582104

**Comment by geemus** [comment]
Ah, that would do it. Thanks for the detailed updates!
