### ISSUE TITLE
Unable to verify certificate

### ISSUE THREAD

**Issue by errm** [excon/excon#479]
/usr/lib/ruby/gems/2.1.0/gems/excon-0.42.1/lib/excon/ssl_socket.rb:121:in `connect_nonblock': Unable to verify certificate, please set `Excon.defaults[:ssl_ca_path] = path_to_certs`, `ENV['SSL_CERT_DIR'] = path_to_certs`, `Excon.defaults[:ssl_ca_file] = path_to_file`, `ENV['SSL_CERT_FILE'] = path_to_file`, `Excon.defaults[:ssl_verify_callback] = callback` (see OpenSSL::SSL::SSLContext#verify_callback), or `Excon.defaults[:ssl_verify_peer] = false` (less secure). (Excon::Errors::SocketError)

I am getting this error when using fog to update elb settings on aws.

excon version 0.42.0 works ok but 0.42.1 - 0.44.2 are broken in the same way.

Seems to be some regression introduced in 0.42.1.

Using a somewhat weird environment of ruby 2.1.5 on  alpine linux.

**Comment by geemus** [comment]
Hmm. 0.42.1 updated the bundled certs, seems a likely culprit.

**Comment by geemus** [comment]
I just updated the certs on master again, could you try with those and see if you have any better luck? Thanks!

**Comment by StealthyGecko** [comment]
I too am suffering from the same issue using 0.44.3 and 0.44.4 is there any update on a fix for this?

**Comment by geemus** [comment]
I'm not sure, not many reports of issues. You could try grabbing your own copy of certs to use, we bundle the ones from: http://curl.haxx.se/ca/cacert.pem

**Comment by StealthyGecko** [comment]
@geemus I found what the issue was, I'm using RVM in development and it seems that RVM manages your ssl certs so doing the following seemed to do the trick:

`rvm osx-ssl-certs status all`
`rvm osx-ssl-certs update all`

Hopefully this will help anyone else who is faced with the same issue in the future.

**Comment by geemus** [comment]
Ah ha. Thanks for the update!

**Comment by raravena-coupa** [comment]
@geemus looks the cert chain might be broken. I'm seeing the issue while trying to connect to AWS using fog.  This issue has more insights: https://github.com/mitchellh/vagrant/issues/5001

**Comment by geemus** [comment]
Hmm. Looks like the certs we have bundled haven't been updated on the curl side (but that the certs there might be off). I looked at that thread but didn't manage to translate it into something clearly actionable for myself. Would welcome advise on next steps to improve the situation.

**Comment by raravena-coupa** [comment]
@geemus so I put in a workaround in our scripts to just use:

```
Excon.defaults[:ssl_ca_file] = '/etc/ssl/certs/ca-bundle.crt'
```

This is what we are using the generate our cert bundle:

```
##
## Bundle of CA Root Certificates
##
## Certificate data from Mozilla downloaded on: Wed Sep  3 03:12:03 2014
##
## This is a bundle of X.509 certificates of public Certificate Authorities
## (CA). These were automatically extracted from Mozilla's root certificates
## file (certdata.txt).  This file can be found in the mozilla source tree:
## http://hg.mozilla.org/releases/mozilla-release/raw-file/default/security/nss/lib/ckfw/builtins/certdata.txt
##
## It contains the certificates in PEM format and therefore
## can be directly used with curl / libcurl / php_curl, or with
## an Apache+mod_ssl webserver for SSL client authentication.
## Just configure this file as the SSLCACertificateFile.
##
## Conversion done with mk-ca-bundle.pl verison 1.22.
## SHA1: c4540021427a6fa29e5f50db9f12d48c97d33889
##
```

**Comment by geemus** [comment]
@raravena-coupa hmm. So would switching from the curl certs to mozilla ones fix the issue?

**Comment by raravena-coupa** [comment]
@geemus yep, pretty much

**Comment by geemus** [comment]
@raravena-coupa er, rather switching from the cacert.pem to ca-bundle.crt? ie this page lists both: http://curl.haxx.se/docs/caextract.html and we would switch from one to the other. Seem legit?

**Comment by raravena-coupa** [comment]
@geemus sounds good to me.

**Comment by geemus** [comment]
If I diff the two I just get this:

```diff
diff --git a/cacert.pem b/ca-bundle.crt
index 1ff34f9..759a4d6 100644
--- a/cacert.pem
+++ b/ca-bundle.crt
@@ -1,7 +1,7 @@
 ##
 ## Bundle of CA Root Certificates
 ##
-## Certificate data from Mozilla as of: Wed Sep  2 18:30:34 2015
+## Certificate data from Mozilla as of: Mon Apr 27 08:58:04 2015
 ##
 ## This is a bundle of X.509 certificates of public Certificate Authorities
 ## (CA). These were automatically extracted from Mozilla's root certificates
```

Which doesn't seem like enough to cause this issue, but is the date that significant? Am I missing something else?

**Comment by raravena-coupa** [comment]
hmm, I think the issue just maybe with AWS handling the new cabundle.  We are using one generated last year.

**Comment by geemus** [comment]
Ah, perhaps that falls into this clause from that page:

```
RSA-1024 removed

Around early September 2014, Mozilla removed the trust bits from the certs in their CA bundle that were still using RSA 1024 bit keys. This may lead to TLS libraries having a hard time to verify some sites if the library in question doesn't properly support "path discovery" as per RFC 4158. (That includes OpenSSL and GnuTLS.)

The last CA bundle we converted from before that cleanup: https://github.com/bagder/ca-bundle/blob/e9175fec5d0c4d42de24ed6d84a06d504d5e5a09/ca-bundle.crt
```

So perhaps that is the one people running into this would want (but that technically we have a more up to date/accurate one now, just there are a few outlier servers that don't play nice).

**Comment by raravena-coupa** [comment]
That's right sounds like an issue we have to bring up with those 'outliers' (i.e. AWS)

**Comment by geemus** [comment]
I guess maybe it's an OpenSSL issue instead if the comment above is read carefully. So maybe version updates there will fix it client side? I dunno this stuff always seems a bit like black magic to me.

**Comment by raravena-coupa** [comment]
I think it's just some providers using 'older' certs that require an older CA to be validated. Since we updated to a newer CA bundle that doesn't have the older CA certs then some of them (older certs) cannot be verified/validated.  That's why setting `Excon.defaults[:ssl_verify_peer] = false` works. That's pretty much it.

**Comment by geemus** [comment]
Fair enough. Seems like there isn't really additional action for us to take presently then. Hopefully this issue can provide some insight/guidance for anyone that runs into this in the future.
