### ISSUE TITLE
Missing first character in some responses leading to improperly parsed HTTP status

### ISSUE THREAD

**Issue by drcraig** [excon/excon#484]
Found this when using Vagrant (1.7.2) and AWS through the vagrant-aws plugin. When running a Vagrant command that makes an AWS API call (easiest is `vagrant ssh-config` once you have an instance up and running), about half the time I get an error saying that it received a status code of 0 instead of the expected 200.

After some investigation we found that this was because sometimes the first character of the response was missing in the line returned by `socket.readline` in `response.rb`, i.e. it was getting "TTP/1.1 200 OK" instead of "HTTP/1.1 200 OK". I could only reproduce this behavior with AWS API calls, but I'm wondering if it's due to the fact that their responses are chunked, since there was a previous bug, #399, related to missing characters in chunked responses. The status code of 0 was because of this character shift. `response.rb` uses character position to split the status line, instead of splitting by spaces. It assumes the 9th-11th characters are the response code and the remaining are the reason phrase. With the missing H up front, everything shifted to the left, so the status code was read as `"00 "`, which was cast as an integer 0.

We were able to reproduce outside of Vagrant by just making an Excon connection and posting to the AWS API. Debugging was complicated by the fact that what mattered to us was using the embedded Ruby and gems inside Vagrant, not the system Ruby. Vagrant uses Ruby 2.0.0, but my Ubuntu 12.04 machine's system Ruby is 1.8.7. The problem only happened when running Vagrant's Ruby. I didn't realize for a long time that you can install arbitrary gems through Vagrant's plugin install command. After that, we were able to stop the problem by `vagrant plugin install excon --plugin-version 0.43.0.`. All of the 0.44.x releases had the problem, but not earlier. Looks like there was a pretty substantial rewrite of `socket.rb` in 0.44.0, so presumably the bug is somewhere in there.

I don't know enough about Ruby or sockets to suggest a fix for the missing character, but one change that might make it a little less mysterious of an error would be to split the status line by spaces instead of counting characters. It would be less brittle and it would be a more proper implementation of the spec in https://tools.ietf.org/html/rfc7230#section-3.1.2.

**Comment by geemus** [comment]
Thanks for the detailed report, hoping to dig in soon, but just haven't quite gotten to it yet.

**Comment by tokengeek** [comment]
We have started to see similar errors but related to parsing *headers* on our CI server. This runs the live fog tests against our (Brightbox) staging environment. Updating from `0.42.0` to `0.44.2` seemed to be the trigger.

Our stack traces are being triggered at https://github.com/excon/excon/blob/master/lib/excon/response.rb#L163

```
Excon::Errors::SocketError: malformed header (Excon::Errors::ResponseParseError)
from /home/paul/.gem/ruby/2.2.1/gems/excon-0.44.4/lib/excon/response.rb:163:in `parse_headers'
```

The error is also intermittent. Some CI runs can complete successfully whilst others see one or two failures.

So I agree it likely that the `socket.rb` changes in #455 have introduced an issue.

More importantly it doesn't seem restricted to Vagrant's Ruby or AWS.

Reproducable with `ruby 2.2.1p85` and `ruby-1.9.3-p484` against the Brightbox API.

**Comment by geemus** [comment]
@tokengeek thanks for the extra details.

@starbelly could you take a look and see if you have any ideas? I hope to dig in some more soon, but as you did some of the original changes where it looks like this may have snuck in, I thought you might have additional insight. Thanks!

**Comment by starbelly** [comment]
Yup, I'll take a look this evening.

**Comment by geemus** [comment]
Thanks!

**Comment by starbelly** [comment]
@drcraig could I see the code that's your using so I can try to reproduce on my end?

**Comment by drcraig** [comment]
@starbelly here you go. It doesn't happen every time, but you can tell when you get a "0" instead of a "400" response. As @tokengeek pointed out, you'll need to run ruby 2.2.1 or 1.9.3. I wasn't able to reproduce with 1.8.7.

```
require 'rubygems'
require 'excon'

url = 'https://ec2.us-gov-west-1.amazonaws.com'

connection = Excon.new(url)
for i in 1..50
    response = connection.post(:body => "Action=DescribeInstances&Version=2014-10-01", :headers => { "Content-Type" => "application/x-www-form-urlencoded; charset=UTF-8", "Authorization" => "not-authorized", "SignedHeaders" => "host;x-amz-date,Signature=notsigned"})
    puts response[:status]
end
```

**Comment by starbelly** [comment]
Able to reproduce, more to come...

**Comment by starbelly** [comment]
Got it.  It has nothing to do with the socket changes exactly, and more stupidity on my part. buffer is scoped within the begin/end block.  Sometimes between reading in data, an exception is raised (OpenSSL, IO, etc. ), which is usually a false positive. None the less, the beginning of the buffer is lost and we start off reading in what's left. This fixes it : https://github.com/excon/excon/pull/494
Need to add a regression test for this, will do as soon as possible.

**Comment by tokengeek** [comment]
@starbelly Cool. Thanks.

**Comment by geemus** [comment]
Fixed in #494 and released in 0.45.1. Testing around it would be great, but I'm not sure how to force the case where it occurs, certainly open to suggestions.

**Comment by drcraig** [comment]
Looks like #494 did the trick for the cases I was hitting. Thanks everyone!

**Comment by starbelly** [comment]
Yeah, I was plenty tired when I thinking about a regression test for this. The best thing to do is simply put in a validation test, where we just make sure all headers are coming out properly.

**Comment by geemus** [comment]
Sounds like a plan, thanks!
