### ISSUE TITLE
Redirect follower reuses basic auth options

### ISSUE THREAD

**Issue by atombender** [excon/excon#486]
If you try to fetch a resource, providing username/password, and it responds with a redirect, the redirect follower then tries to supply the same basic auth credentials to the new location.

Maybe some servers ignore the auth header if inappropriate, but some servers — Amazon S3, in particular — will consider this a bad request and respond with 400.

The correct behaviour is to provide basic auth credentials _only_ if the remote endpoint responds with a 401. Excon should not send credentials to just any host.

This is a regression. We were using 0.33, which does not have this problem.

Example debug output:

```
excon.request
  :chunk_size          => 1048576
  :ciphers             => "HIGH:!SSLv2:!aNULL:!eNULL:!3DES"
  :connect_timeout     => 60
  :debug_request       => true
  :debug_response      => true
  :headers             => {
    "Authorization" => "REDACTED"
  }
  :host                => "example.com"
  :hostname            => "example.com"
  :idempotent          => false
  :instrumentor        => Excon::StandardInstrumentor
  :instrumentor_name   => "excon"
  :method              => "GET"
  :middlewares         => [
    Excon::Middleware::ResponseParser
    Excon::Middleware::Expects
    Excon::Middleware::Idempotent
    Excon::Middleware::Instrumentor
    Excon::Middleware::Mock
    Excon::Middleware::RedirectFollower
  ]
  :mock                => false
  :nonblock            => true
  :omit_default_port   => true
  :password            => "REDACTED"
  :path                => "/somefile"
  :persistent          => false
  :port                => 443
  :query               => nil
  :read_timeout        => 60
  :retries_remaining   => 4
  :retry_limit         => 4
  :scheme              => "https"
  :ssl_verify_peer     => true
  :tcp_nodelay         => false
  :thread_safe_sockets => true
  :uri_parser          => URI
  :user                => "someuser"
  :versions            => "excon/0.44.4 (x86_64-darwin14.0.0) ruby/1.9.3"
  :write_timeout       => 60
excon.response
  :body          => ""
  :headers       => {
    "Connection"     => "keep-alive"
    "Content-Length" => "0"
    "Content-Type"   => "application/x-gzip"
    "Date"           => "Sat, 21 Mar 2015 01:52:36 GMT"
    "Location"       => "http://someotherserver.com/"
  }
  :reason_phrase => "Found"
  :status        => 302
excon.request
  :chunk_size          => 1048576
  :ciphers             => "HIGH:!SSLv2:!aNULL:!eNULL:!3DES"
  :connect_timeout     => 60
  :debug_request       => true
  :debug_response      => true
  :headers             => {
    "Authorization" => "REDACTED"
  }
  :host                => "someotherserver.com"
  :hostname            => "someotherserver.com"
  :idempotent          => false
  :instrumentor        => Excon::StandardInstrumentor
  :instrumentor_name   => "excon"
  :method              => :get
  :middlewares         => [
    Excon::Middleware::ResponseParser
    Excon::Middleware::Expects
    Excon::Middleware::Idempotent
    Excon::Middleware::Instrumentor
    Excon::Middleware::Mock
    Excon::Middleware::RedirectFollower
  ]
  :mock                => false
  :nonblock            => true
  :omit_default_port   => true
  :password            => "REDACTED"
  :path                => "/somefile"
  :persistent          => false
  :port                => 80
  :query               => ""
  :read_timeout        => 60
  :retries_remaining   => 4
  :retry_limit         => 4
  :scheme              => "http"
  :ssl_verify_peer     => true
  :tcp_nodelay         => false
  :thread_safe_sockets => true
  :uri_parser          => URI
  :user                => "someuser"
  :versions            => "excon/0.44.4 (x86_64-darwin14.0.0) ruby/1.9.3"
  :write_timeout       => 60
```

**Comment by geemus** [comment]
We [strip](https://github.com/excon/excon/blob/master/lib/excon/middlewares/redirect_follower.rb#L26) the `Authorization` header. But I think because you have user/password set, they must be getting added back in again. We should probably also delete user/pass from the hash in the same place. What do you think? Would you be up for a quick pull to try that? Thanks!

**Comment by atombender** [comment]
But the redirect could be to a location that also requires auth, assuming the same domain (and realm?). The only way to know for sure is to try without auth first, then if you get 401, retry with auth if it's secure. I believe all browsers work like that.

**Comment by geemus** [comment]
I think I lean a bit toward always stripping as it prevents accidentally leaking credentials (which I think may be why we are careful to strip creds in other cases). I think passing along creds should probably be an exception, rather than a rule. So in those cases it would be better for the user to implement their own redirect follower/behavior. I think this should keep the code pretty simple also and accommodate your usage. What do you think?

**Comment by atombender** [comment]
It’s not ideal (or particularly correct), but better than what we have now, at least.

**Comment by geemus** [comment]
@atombender I tried to find references about correct behavior, but was unable to find any mention of authentication in the related RFCs. Do you have insight into where I could read up on it a bit more?

**Comment by atombender** [comment]
Basic auth is [RFC 2617](http://tools.ietf.org/html/rfc2617). Some extracts, my emphasis:

> The `realm` directive (case-insensitive) is required for all authentication schemes that issue a challenge. **The realm value (case-sensitive), in combination with the canonical root URL [...] of the server being accessed, defines the protection space**. [...] The **protection space determines the domain over which credentials can be automatically applied. If a prior request has been authorized, the same credentials MAY be reused for all other requests within that protection space** for a period of time determined by the authentication scheme, parameters, and/or user preference. Unless otherwise defined by the authentication scheme, **a single protection space cannot extend outside the scope of its server**. [...] A user agent that wishes to authenticate itself with an origin server--**usually, but not necessarily, after receiving a 401 (Unauthorized)**--MAY do so by including an Authorization header field with the request.
>
> [...]
>
> A client SHOULD assume that all paths at or deeper than the depth of the last symbolic element in the path field of the Request-URI also are within the protection space specified by the Basic realm value of the current challenge. **A client MAY preemptively send the corresponding Authorization header with requests for resources in that space without receipt of another challenge from the server.**

The important part is that a client should never automatically offer the previously negotiated credentials when it crosses to another "protection space" (ie., realm + domain).

The _correct_ behaviour for Excon is, in other words, to not just have a username/password pair, but in fact have a mapping of domains to username/password pairs, and only offer these credentials if the target server returns 401.

But a starting step is to remove the username/password from the session once a redirect passes to a new domain (but only then).

(The realm isn't honoured by the browsers, in my experience, and I've never seen it actually used for anything serious.)

**Comment by geemus** [comment]
Got it. I'm just going to strip it out for the moment (as a step in the right direction hopefully and to concretely fix your issue). Would you be interested in further discussing and working on a PR for us with the behavior you describe?

**Comment by atombender** [comment]
I'd like to, but I don't think I have any time these days.

**Comment by geemus** [comment]
Fair enough. I may try to revisit, but I fear I'm in a pretty similar situation time-wise.

**Comment by geemus** [comment]
We added stripping, considering that as good-enough for now.
