### ISSUE TITLE
CPU spin wait during SSL connect on non-blocking sockets

### ISSUE THREAD

**Issue by jcsalem** [excon/excon#493]
When nonblocking sockets are used, Excon::SSLSocket.new spin-waits while establishing the connection.  This is an inefficient use of CPU.  

This can be shown by running strace on a process opening an SSL connection. You'll see a dozen or more consecutive calls in quick succession to read returning the EAGAIN error.

Our application (which uses excon via Fog to write to Amazon S3) showed a 20% performance improvement when the fix (see below) was made to insert an IO.select in-between calls to OpenSSL.connect_nonblock.

Here is a PR for my proposed fix: https://github.com/excon/excon/pull/492

**Comment by townie** [comment]
@jcsalem private repo

**Comment by jcsalem** [comment]
Yes, oops. I updated the link to point to the PR I created in the excon repo: https://github.com/excon/excon/pull/492

**Comment by geemus** [comment]
Yep, I think that is now fixed, working through a couple other PRs but can probably cut a release shortly.
