### ISSUE TITLE
ruby 2.2.1, ssl, [BUG] object allocation during garbage collection phase 

### ISSUE THREAD

**Issue by francisli** [excon/excon#495]
I'm frequently, but nondeterministically, getting the following hard crash of the ruby interpreter in ssl related code of excon when using ruby 2.2.1 (which fixed symbol garbage collection).

/app/vendor/bundle/ruby/2.2.0/gems/excon-0.44.4/lib/excon/ssl_socket.rb:121: [BUG] object allocation during garbage collection phase
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]

-- Control frame information -----------------------------------------------
c:0080 p:---- s:0381 e:000380 CFUNC  :connect_nonblock
c:0079 p:0011 s:0378 e:000377 BLOCK  /app/vendor/bundle/ruby/2.2.0/gems/excon-0.44.4/lib/excon/ssl_socket.rb:121 [FINISH]
c:0078 p:---- s:0375 e:000374 CFUNC  :loop
c:0077 p:1122 s:0372 e:000371 METHOD /app/vendor/bundle/ruby/2.2.0/gems/excon-0.44.4/lib/excon/ssl_socket.rb:119 [FINISH]
c:0076 p:---- s:0356 e:000355 CFUNC  :new
c:0075 p:0130 s:0352 e:000348 METHOD /app/vendor/bundle/ruby/2.2.0/gems/excon-0.44.4/lib/excon/connection.rb:387
c:0074 p:0031 s:0345 e:000344 METHOD /app/vendor/bundle/ruby/2.2.0/gems/excon-0.44.4/lib/excon/connection.rb:106
c:0073 p:0155 s:0337 e:000336 METHOD /app/vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.10.0.279/lib/new_relic/agent/instrumentation/excon/middleware.rb:30
c:0072 p:0365 s:0328 e:000327 METHOD /app/vendor/bundle/ruby/2.2.0/gems/excon-0.44.4/lib/excon/middlewares/mock.rb:47
c:0071 p:0087 s:0321 e:000320 METHOD /app/vendor/bundle/ruby/2.2.0/gems/excon-0.44.4/lib/excon/middlewares/instrumentor.rb:22
c:0070 p:0011 s:0316 e:000315 METHOD /app/vendor/bundle/ruby/2.2.0/gems/excon-0.44.4/lib/excon/middlewares/base.rb:15
c:0069 p:0011 s:0312 e:000311 METHOD /app/vendor/bundle/ruby/2.2.0/gems/excon-0.44.4/lib/excon/middlewares/base.rb:15
c:0068 p:0011 s:0308 e:000307 METHOD /app/vendor/bundle/ruby/2.2.0/gems/excon-0.44.4/lib/excon/middlewares/base.rb:15
c:0067 p:0306 s:0304 E:0005a8 METHOD /app/vendor/bundle/ruby/2.2.0/gems/excon-0.44.4/lib/excon/connection.rb:233
c:0066 p:0016 s:0296 e:000295 METHOD /app/vendor/bundle/ruby/2.2.0/gems/fog-core-1.29.0/lib/fog/core/connection.rb:81
c:0065 p:0037 s:0291 e:000290 METHOD /app/vendor/bundle/ruby/2.2.0/gems/fog-xml-0.1.1/lib/fog/xml/connection.rb:9
c:0064 p:0019 s:0285 e:000284 METHOD /app/vendor/bundle/ruby/2.2.0/gems/fog-aws-0.1.1/lib/fog/aws/storage.rb:587
c:0063 p:0531 s:0269 e:000268 METHOD /app/vendor/bundle/ruby/2.2.0/gems/fog-aws-0.1.1/lib/fog/aws/storage.rb:582
c:0062 p:0078 s:0255 e:000254 METHOD /app/vendor/bundle/ruby/2.2.0/gems/fog-aws-0.1.1/lib/fog/aws/requests/storage/put_object.rb:43
c:0061 p:0273 s:0247 e:000246 METHOD /app/vendor/bundle/ruby/2.2.0/gems/fog-aws-0.1.1/lib/fog/aws/models/storage/file.rb:209
c:0060 p:0021 s:0242 e:000241 METHOD /app/vendor/bundle/ruby/2.2.0/gems/fog-core-1.29.0/lib/fog/core/collection.rb:51
c:0059 p:0084 s:0237 e:000236 METHOD /app/vendor/bundle/ruby/2.2.0/gems/carrierwave-0.10.0/lib/carrierwave/storage/fog.rb:261
c:0058 p:0038 s:0232 e:000231 METHOD /app/vendor/bundle/ruby/2.2.0/gems/carrierwave-0.10.0/lib/carrierwave/storage/fog.rb:80
c:0057 p:0012 s:0227 e:000226 BLOCK  /app/vendor/bundle/ruby/2.2.0/gems/carrierwave-0.10.0/lib/carrierwave/uploader/store.rb:59
c:0056 p:0020 s:0225 e:000224 METHOD /app/vendor/bundle/ruby/2.2.0/gems/carrierwave-0.10.0/lib/carrierwave/uploader/callbacks.rb:17
c:0055 p:0056 s:0220 e:000219 METHOD /app/vendor/bundle/ruby/2.2.0/gems/carrierwave-0.10.0/lib/carrierwave/uploader/store.rb:58
c:0054 p:0040 s:0216 e:000215 METHOD /app/vendor/bundle/ruby/2.2.0/gems/carrierwave-0.10.0/lib/carrierwave/mount.rb:375
c:0053 p:0011 s:0213 e:000212 METHOD /app/vendor/bundle/ruby/2.2.0/gems/carrierwave-0.10.0/lib/carrierwave/mount.rb:207
c:0052 p:0012 s:0210 e:000209 LAMBDA /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:427 [FINISH]
c:0051 p:---- s:0205 e:000204 CFUNC  :call
c:0050 p:0060 s:0200 e:000199 LAMBDA /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:225 [FINISH]
c:0049 p:---- s:0194 e:000193 CFUNC  :call
c:0048 p:0010 s:0190 e:000189 LAMBDA /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:219 [FINISH]
c:0047 p:---- s:0184 e:000183 CFUNC  :call
...

**Comment by geemus** [comment]
We recently fixed some things around connect nonblock for ssl that I suspect may have fixed this also. Could you bump up to the latest and let us ping us if you are still having the issue? (I'll close in the mean time, but just let me know and I'll be happy to reopen if needed). Thanks!
