### ISSUE TITLE
undefined local variable or method `error' 

### ISSUE THREAD

**Issue by bjm88** [excon/excon#502]
Hi
  With Savon 2.11.0 and Excon 0.45.1 latest versions when making a call to an endpoint that does SSL client auth we are seeing an error.  The cert and key params are passed, and we check the same using UNIX WGET to get WSDL and it works, however passing keys into Savon/Excon we see a weird error that we think is preventing us seeing the actual SSL Handshake error..

Excon::Errors::SocketError: undefined local variable or method `error' for #<Excon::SSLSocket:0x007ff874040398> (NameError)
from /Users/Ben/.rvm/gems/ruby-2.1.5@caredox/gems/excon-0.44.1/lib/excon/socket.rb:61:in `rescue in readline'

Sample Call (note the .cer and .key files are both in Base64 PEM format and work with WGET)
client = Savon.client(log_level: :debug,
                            ssl_verify_mode: :none,
                            ssl_cert_file: (Rails.root + '../security/integrations/wi_iis/wi-signed.cer').to_s,
                            ssl_cert_key_file: (Rails.root + '../security/integrations/wi_iis/int.key').to_s,
                            wsdl: "https://wir.dhswir.org/CDC/VaccinationService?wsdl",
                            endpoint: "https://wir.dhswir.org/CDC/VaccinationService",
                            open_timeout: 30,
                            read_timeout: 30)

Also note we are doing ssl_verify_mode none and settings Excon.defaults[:ssl_verify_peer] = false for now as the test system endpoing doesn't have valid ssl cert (root signer missing in chain, I think unrelated though)

Any ideas?

**Comment by bjm88** [comment]
FYI I also confirmed if I swap in a different http adapter for Savon, via

client = Savon.client(log_level: :debug,
                            ssl_verify_mode: :none,
                            adapter: :httpclient,

Everything went through fine.

**Comment by geemus** [comment]
Hey, I think that error has been fixed. The error there indicates that you are running 0.44.1, not 0.45.1. Please let me know if bumping doesn't get you past that issue.
