### ISSUE TITLE
Undefined local variable error

### ISSUE THREAD

**Issue by KellyMahan** [excon/excon#505]
Error isn't defined at this location. For some reason when using large images with dragonfly it errors out here.

in dragonfly with s3 storage thumb("1200x1200>") works just fine
but thumb("1600x1600>") throws the error below

https://github.com/excon/excon/commit/8f741167125bb6fe744e534d1d80c358ca0de657

**Comment by KellyMahan** [comment]
pull request https://github.com/excon/excon/pull/506

**Comment by KellyMahan** [comment]
After referencing the gem from my repository with the "fix" this is the stack trace i get.

Excon::Errors::SocketError - Bad address (Errno::EFAULT):
  .rbenv/versions/2.1.2/lib/ruby/2.1.0/openssl/buffering.rb:383:in `syswrite_nonblock'
  .rbenv/versions/2.1.2/lib/ruby/2.1.0/openssl/buffering.rb:383:in `write_nonblock'
   () .gems/bundler/gems/excon-71007862fcc4/lib/excon/socket.rb:243:in `block in write_nonblock'
   () /.gems/bundler/gems/excon-71007862fcc4/lib/excon/socket.rb:238:in `loop'
   () .gems/bundler/gems/excon-71007862fcc4/lib/excon/socket.rb:238:in `write_nonblock'
   () .gems/bundler/gems/excon-71007862fcc4/lib/excon/socket.rb:78:in `write'
   () .gems/bundler/gems/excon-71007862fcc4/lib/excon/connection.rb:152:in `request_call'
   () .gems/bundler/gems/excon-71007862fcc4/lib/excon/middlewares/mock.rb:47:in `request_call'
   () .gems/bundler/gems/excon-71007862fcc4/lib/excon/middlewares/instrumentor.rb:22:in `request_call'
   () .gems/bundler/gems/excon-71007862fcc4/lib/excon/middlewares/base.rb:15:in `request_call'
   () .gems/bundler/gems/excon-71007862fcc4/lib/excon/middlewares/base.rb:15:in `request_call'
   () .gems/bundler/gems/excon-71007862fcc4/lib/excon/middlewares/base.rb:15:in `request_call'
   () .gems/bundler/gems/excon-71007862fcc4/lib/excon/connection.rb:233:in `request'
   () .gems/bundler/gems/excon-71007862fcc4/lib/excon/middlewares/idempotent.rb:26:in `error_call'
   () .gems/bundler/gems/excon-71007862fcc4/lib/excon/middlewares/base.rb:10:in `error_call'
   () .gems/bundler/gems/excon-71007862fcc4/lib/excon/middlewares/base.rb:10:in `error_call'
   () .gems/bundler/gems/excon-71007862fcc4/lib/excon/connection.rb:256:in `rescue in request'
   () .gems/bundler/gems/excon-71007862fcc4/lib/excon/connection.rb:204:in `request'
   () .gems/bundler/gems/excon-71007862fcc4/lib/excon/middlewares/idempotent.rb:26:in `error_call'
   () .gems/bundler/gems/excon-71007862fcc4/lib/excon/middlewares/base.rb:10:in `error_call'
   () .gems/bundler/gems/excon-71007862fcc4/lib/excon/middlewares/base.rb:10:in `error_call'
   () .gems/bundler/gems/excon-71007862fcc4/lib/excon/connection.rb:256:in `rescue in request'
   () .gems/bundler/gems/excon-71007862fcc4/lib/excon/connection.rb:204:in `request'
   () .gems/bundler/gems/excon-71007862fcc4/lib/excon/middlewares/idempotent.rb:26:in `error_call'
   () .gems/bundler/gems/excon-71007862fcc4/lib/excon/middlewares/base.rb:10:in `error_call'
   () .gems/bundler/gems/excon-71007862fcc4/lib/excon/middlewares/base.rb:10:in `error_call'
   () .gems/bundler/gems/excon-71007862fcc4/lib/excon/connection.rb:256:in `rescue in request'
   () .gems/bundler/gems/excon-71007862fcc4/lib/excon/connection.rb:204:in `request'

**Comment by geemus** [comment]
closed by #506
