### ISSUE TITLE
Timeout issues probably related to an SSL certificate

### ISSUE THREAD

**Issue by ervinb** [excon/excon#507]
I'm trying to sync some files to S3 with `middleman-s3_sync` and it seems that `excon` is encountering some difficulties. I've put a `puts` on [line 121](https://github.com/excon/excon/blob/master/lib/excon/ssl_socket.rb#L121) in `ssl_socket.rb` to log the exception and the output is:

```
read would block
```

I've also `strace`d the process and here is some parts of the output which may be relevant:

- a certificate is missing from the system?
```
[pid 18246] stat("/usr/lib/ssl/certs/415660c1.0", {st_mode=S_IFREG|0644, st_size=834, ...}) = 0
[pid 18246] stat("/usr/lib/ssl/certs/415660c1.1", {st_mode=S_IFREG|0644, st_size=834, ...}) = 0

[pid 18246] stat("/usr/lib/ssl/certs/415660c1.2", 0x7fafb46fd770) = -1 ENOENT (No such file or directory)

[pid 18246] stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=118, ...}) = 0
[pid 18246] stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=118, ...}) = 0
```

- connection to S3 is established but the `read` system call loops (`fd = 8` is the connection to `s3-1-w.amazonaws.com`)

```
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=118, ...}) = 0
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=118, ...}) = 0
read(8, "\27\3\3@0", 5)                 = 5
read(8, ",\366O[Y\3014\363\322\26\205J\tJ\tS.\263\207\214h$\\\226\262\35\232o\233\326\177a"..., 16432) = 11771

read(8, 0x7fede8af71f3, 4661)   = -1 EAGAIN (Resource temporarily unavailable)

select(9, [8], NULL, NULL, {60, 0})     = 1 (in [8], left {59, 908601})
mprotect(0x7fede8b81000, 8192, PROT_READ|PROT_WRITE) = 0
read(8, "\10A\322\nM\243`\276\10\376\32\361g\250\17\273\264\207\307WA\363r\343\335\26\321\37\330 :\33"..., 4661) = 4661
mprotect(0x7fede8b83000, 12288, PROT_READ|PROT_WRITE) = 0
mprotect(0x7fede8b86000, 8192, PROT_READ|PROT_WRITE) = 0
```
If I understand correctly, `EAGAIN` happens because the socket (`fd = 8`) is open for writing but it's empty.

This loops for a while and sometimes the upload process actually begins but it's very slow.

Thanks!

**Comment by ervinb** [comment]
It turns out that there were more than 500K files in the `logs` folder on S3 and that's what choked the process.

**Comment by geemus** [comment]
@ervinb ah. Thanks for the update on what was going on here, I looked briefly at it yesterday but nothing obvious came to mind and I had a couple other things I was juggling before I could give it more time/focus. Glad to hear you've been able to resolve it in the meantime. Thanks!
