### ISSUE TITLE
Implement the concept of sessions

### ISSUE THREAD

**Issue by fbernier** [excon/excon#510]
It would be nice if the concept of sessions as explained [here](https://github.com/JoshMcKin/hot_tub#sessions-only) would be built-in in Excon. It would allow the Faraday adapter to be persistent by default after changing [this line](https://github.com/lostisland/faraday/blob/master/lib/faraday/adapter/excon.rb#L52)

What do you think? I could make some work on that if you agree.

**Comment by geemus** [comment]
Hey, I'm not sure I really follow that example. Could you give me a bit more detail around what a use case for something like that might look like? Also, what do you mean about Faraday being persistent by default? I think some clarifications around both of those could help me understand what you are getting at here. Thanks!

**Comment by fbernier** [comment]
The use case I am thinking about is telling Faraday to use the excon adapter with the persistent: true option set and then tell [elasticsearch-transport](https://github.com/elastic/elasticsearch-ruby/tree/master/elasticsearch-transport#transport-implementations) to use this Faraday config.

From my understanding, since calls to Elasticsearch are made to the same hosts/ips, keeping a persistent connection to every nodes has speed benefits. The sessions would be a way to create an instance of excon which makes a persistent connection to every new hosts so it can reuse this connection for another call later on.

Maybe there is something I understanding wrong. If so, please tell me!

**Comment by geemus** [comment]
Ok. I think by default, if you create an excon connection and call request on it multiple times, they should share a connection (unless you call reset specifically and/or the responses do not specify keep-alive). The problem I've run into around that is that nobody seems to actually respect this/work properly. So I don't think it would require a change here (just a change in how faraday uses it). But, as I said, tough it would be easy to change, it would almost assuredly work intermittently/with errors. Does that help/make sense? Thanks.

**Comment by fbernier** [comment]
Thanks for the explanation. I had tried quickly making the changes to Faraday but without success. I jsut digged deeper into the Excon code and saw I can reuse an Excon connection instance and call the ```request``` method with a different path and querystring each time, which is what I was missing.

I'll give this a try soon.

**Comment by geemus** [comment]
Great, just let me know if you have further questions or there is anything
else I can help with.
