### ISSUE TITLE
Potential Feature: Allow cert objects as well as paths in ssl_socket

### ISSUE THREAD

**Issue by aselder** [excon/excon#511]
We use Faraday in our project and I'm trying switch out adapters from :net_http to :excon, and I'm having to do a lot of work.

Most relates to the fact that when using the net/http adapter, the client_cert expects an OpenSSL::X509::Certificate object while client_key expects an OpenSSL::PKey::RSA object. When using the excon adapter those same Faraday options need to be set to the file paths instead of the instantiated objects.

I proposed modifying ssl_socket to check to see if the option passed is an instantiated OpenSSL object before trying to read files assuming the objects are file names.

This should have no impact an existing users and facilitate easy adapter swapping when using Faraday.

I'm more that happy to do the work, just wanted to make sure people were receptive to the idea.

Let me know what you think.

**Comment by geemus** [comment]
First, just to clarify, there are a couple sets of options.

`certificate_path` && `private_key_path` expect file paths

`certificate` && `private_key` just expect the data as a string

In your case, could the adapter just output the strings to the second option? It seems like that might be a more light weight/simple solution, vs adding more complexity to some code that is already a bit ugly confusing here: https://github.com/excon/excon/blob/master/lib/excon/ssl_socket.rb#L67

What do you think? Thanks!

**Comment by aselder** [comment]
All of the net/http based adapters take client_cert and client_key parameters that are already instantiated X509 certificates  and PKey RSA objects. Even the certificate and private_key options in excon expect a string rather than an OpenSSL object.

I know this is mostly a Faraday issue, but my end goal is to use Faraday and switch adapters without having to modify the options passed to faraday. 

You're probably right, makes more sense to modify Faraday, it's just a much bigger task in a less responsive project :)

**Comment by geemus** [comment]
Fair point, I guess I'm just reticent to modify the interface if I can avoid it. Also, I guess it seems to me that the string or path version is easier for end users to interact with (vs needing to instantiate the objects themselves). Anyway, sounds like maybe faraday is (perhaps unfortunately) the better home for this at present, but do let me know if you have other questions or anything I can help with. Thanks!
