### ISSUE TITLE
An empty proxy environment variable disables excon

### ISSUE THREAD

**Issue by amos-stan** [excon/excon#512]
I got into a situation where set but empty http_proxy environment variable caused excon to fail.

How I got this?
We have empty http_proxy (and all combinations) environment variables in our TeamCity root project.
When I tried to use vagrant-aws from inside a teamcity job it failed, until I unset the environment variables.

I suggest that the code around https://github.com/excon/excon/blob/master/lib/excon/connection.rb#L414 will treat the environment variables as missing if they are empty.

I'll try to do this myself but I'm not quiet familiar with the tools used in the module so it might take time.

**Comment by geemus** [comment]
I've added some code to strip out empty proxies, thanks for the detailed report.

**Comment by amos-stan** [comment]
Thanks!
