### ISSUE TITLE
 hostname does not match the server certificate (HTTPI::SSLError)

### ISSUE THREAD

**Issue by Shirl15** [excon/excon#515]
When I'm trying to connect to a WSDL( I'm writing a client to connect to a WSDL), I'm getting following error:
Ruby2.1.0/lib/ruby/gems/2.1.0/gems/httpi-2.4.1/lib/httpi/adapter/net_http.rb:46:in `rescue in request': hostname does not match the server certificate  (HTTPI::SSLError)

Ruby Version :2.1, Windows 7 64 bit OS. Following are the options i tried
1. I tried changing source to http://rubygems.org/ instead of https://rubygems.org/ as suggested in some posts..
2. I updated gem version to 2.2.3 
3. Added Cacert.pem

Exists on Ruby 2.0 Version also
Could some one let me know to resolve this error?

**Comment by geemus** [comment]
From the stack trace it appears this is coming from an adapter to net_http, rather than excon, so I don't think there is anything I can change here to help. Also, unfortunately, I don't know how to really help with that off hand. Hope you can find more info though.
