### ISSUE TITLE
Response header parser: Problems parsing two cookies with expire date (aka a header value with a comma)

### ISSUE THREAD

**Issue by derSascha** [excon/excon#517]
I got some trouble parsing cookies with excon. Consider the following server response:
```
Set-Cookie: session=XY; Expires=Wed, 09 Jun 2021 10:18:14 GMT
Set-Cookie: lang=en-US; Expires=Wed, 09 Jun 2021 10:18:14 GMT
```
Excon now joins the two lines with a comma in [response.rb](https://github.com/excon/excon/blob/master/lib/excon/response.rb#L172):
```
session=XY; Expires=Wed, 09 Jun 2021 10:18:14 GMT, lang=en-US; Expires=Wed, 09 Jun 2021 10:18:14 GMT
```
The expire dates in the cookies are now troublesome... Any suggestions how to split this cookies? Seems like the ```join(', ')``` is bad idea here.

**Comment by geemus** [comment]
I think this relates to how RFCs define headers, but I don't recall specifics.

@dpiddy do you perhaps have thoughts/comments here? I think you first added this behavior, so I don't want to mess with it without weighing in.

**Comment by derSascha** [comment]
Yes, the examples are from the [RFC](http://tools.ietf.org/html/rfc6265#page-8).

In my understanding is the response parser is the first middleware => another middleware is not solution.

I don't really understand what magic the Excon::Header class has, but fixing the problem there might be an idea:
  - write all elements into the header class (as single elements instead of concat string)
  - read works like before (using join in the header class)
  - and a new reader allows fetching the header lines as array

**Comment by geemus** [comment]
Hmm, looks like the newer HTTP RFCs actually deprecate multi-line headers, which might simplify the situation here a bit:

> Historically, HTTP header field values could be extended over
> multiple lines by preceding each extra line with at least one space
> or horizontal tab (obs-fold).  This specification deprecates such
> line folding except within the message/http media type
> (Section 8.3.1).  A sender MUST NOT generate a message that includes
> line folding (i.e., that has any field-value that contains a match to
> the obs-fold rule) unless the message is intended for packaging
> within the message/http media type.

Also, from the same RFC:

> Note: In practice, the "Set-Cookie" header field ([RFC6265]) often
> appears multiple times in a response message and does not use the
> list syntax, violating the above requirements on multiple header
> fields with the same name.  Since it cannot be combined into a
> single field-value, recipients ought to handle "Set-Cookie" as a
> special case while processing header fields.  (See Appendix A.2.3
> of [Kri2001] for details.)

I'll try to revisit soon, just wanted to keep my notes on how to approach here so I don't lose my train of thought. I think the above means we can strip out a lot of the magic from the header stuff, which may simplify. Then we definitely need to change cookies to be a special case that somehow ends up in a list, I may need to give a bit more thought to what specifically that will look like though.

**Comment by geemus** [comment]
Sorry for the huge delay. I think #550 offers a fix, could you take a look and see what you think?
