### ISSUE TITLE
Unusual encoding for a feed

### ISSUE THREAD

**Issue by mahemoff** [excon/excon#519]
Any idea why this feed is processed differently by excon compared to open-uri?

> url = http://insertmoin.de/podcast/

> open(url).read[0,100]
"<?xml version=\"1.0\" encoding=\"UTF-8\"?>        <rss version=
\"2.0\"\n            xmlns:content=\"http://p"

> Excon.new(url).request(method: 'GET').body[0,100]
"\x1F\x8B\b\x00\x00\x00\x00\x00\x00\x03\xED\xBD\xDBr\xDBH\x96.|=
\xFB)\xB2\xD8\x11\x1D\xAE\x18%\xC5\x93N\xAC\xEA\xAA_\x96d\xC9e\x
CB\xD6\x88\xB2\xDDS;v0\x92D\x92@\x11\av& Z\xBA\x9A\x8B\xFD\x18\x
FD\xFF\xA5\x1D\xE1\x9B\xFD\x02\xBE\xF2\x95\xF8&\xF3$\xFFZ+\x01\x
1E$\xD1\x96@\xCA-\x90\xA8\x19\xB7$\x12\xC8Ld\xAE"

**Comment by geemus** [comment]
My guess would be that it is gzip or compress encoded. By default excon gives back raw responses, though you can mount the decompress middleware to expand/unzip it. You can probably confirm by checking the encoding value in the headers though.

**Comment by mahemoff** [comment]
That did it, thanks. I'm just surprised it didn't come up before.

I went with this:

    case res.status
      when 200, 304
        body =
          if res[:headers]['Content-Encoding']=='gzip'
            Zlib::GzipReader.new(StringIO.new(res.body)).read
          else
            res.body
          end
      when 404
        ...

**Comment by geemus** [comment]
Cool, yeah, I would expect it more often also. Usually most servers will only give you back gzip/compress if you ask for it though (which you certainly can and might even want to), but this server maybe always gives it back, even though it technically shouldn't do so. It's always a bit of a tradeoff depending on size of request and type of request. ie it is less data over the wire, but how much less depends on the type of data and how compressable it is. Plus, though it might then be faster to transfer, you have to pay the cost in time of encoding/decoding it (which in small requests or things that don't compress well, can mean it is slower than if you didn't. Anyway, glad this is now sorted out for you.

**Comment by mahemoff** [comment]
Ah you must be right, I was assuming gzip was being requested automatically, which I think other http client libs do, but I agree is better not to by default. I should actually experiment with requesting it then.

**Comment by geemus** [comment]
Yeah, I've considered having it as default, but there are a lot of qualifications about when you might or might not want to use it. I think if you use the middleware I mentioned it will also set the request headers appropriately, fwiw. I figure it is maybe easier/better if it is something you can easily opt-in to, vs something that might be somewhat awkward to opt-out of.

**Comment by mahemoff** [comment]
It might be worth including an example in the README on how to get the defaults typically applied in other http clients? The other notable one being `:omit_default_port => true`. Also acts as a troubleshooter.

**Comment by geemus** [comment]
Good call, I'd certainly also welcome any PRs in that realm. Thanks!

**Comment by mahemoff** [comment]
That's an attempt it, would be interested to know if there are any other settings like that.

**Comment by geemus** [comment]
Those are the only ones that come immediately to mind for me, thanks!
