### ISSUE TITLE
Possible to disable SSL verification via ENV variable

### ISSUE THREAD

**Issue by wadetandy** [excon/excon#521]
When encountering an SSL certificate verification error, the error is "Unable to verify certificate, please set `Excon.defaults[:ssl_ca_path] = path_to_certs`, `ENV['SSL_CERT_DIR'] = path_to_certs`, `Excon.defaults[:ssl_ca_file] = path_to_file`, `ENV['SSL_CERT_FILE'] = path_to_file`, `Excon.defaults[:ssl_verify_callback] = callback` (see OpenSSL::SSL::SSLContext#verify_callback), or `Excon.defaults[:ssl_verify_peer] = false` (less secure)."

The final option disables SSL verifcation entirely and solves my problem, but there is no way to enable this via an environment variable like the other options.  Is this something that could be added (`EXCON_SSL_VERIFY=false` or something)? Happy to do the work myself if I know it's something that will be accepted.

**Comment by geemus** [comment]
Providing an ENV override here sounds reasonable, if you'd like to take a shot at that, sounds great!
