### ISSUE TITLE
AWS EC2 API is throwing error during knife ec2 server create

### ISSUE THREAD

**Issue by ldunston** [excon/excon#525]
The AWS EC2 API is throwing this error:

ERROR: Excon::Errors::HTTPStatusError: Expected(200) <=> Actual(0 Unknown)

when running knife ec2 server create.  The remaining message appears to be valid XML...here is snippet:

excon.error.response
  :body          => "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<RunInstancesResponse xmlns=\"http://ec2.amazonaws.com/doc/2014-06-15/\">\n    <requestId>removed</requestId>\n    <reservationId>removed</reservationId>\n    <ownerId>removed</ownerId>\n    <groupSet/>\n    <instancesSet>\n        <item>\n            <instanceId>removed</instanceId>\n            <imageId>ami-48353b1a</imageId>\n            <instanceState>\n                <code>0</code>\n T....
  :headers       => {
    "Content-Type" => "text/xml;charset=UTF-8"
    "Date"         => "Wed, 19 Aug 2015 07:44:24 GMT"
    "Server"       => "AmazonEC2"
    "Vary"         => "Accept-Encoding"
  }
  :local_address => "removed"
  :local_port    => 55568
  :reason_phrase => "K"
  :remote_ip     => "removed"
  :status        => 0

The version of excon that I'm using is 0.45.4.  This was working yesterday (and has for months) so likely something changed on the AWS side.

**Comment by ldunston** [comment]
I should have added that server create isn't working for either EC2 classic or VPC.  Let me know if you'd like any more information on my environment.

**Comment by geemus** [comment]
@ldunston could you also ensure you have an updated version of fog and/or fog-aws?

**Comment by micpalmia** [comment]
same error here, I upgraded fog-aws from 0.0.8 to 0.7.6 and everything worked.

**Comment by maj0rhav0c** [comment]
I had this same issue as well. Deployments worked last week - no changes to my system, suddenly started having this error this week. It occurred using knife-ec2 for deployment from the ChefDK package, and is an issue with the excon gem in chefdk. To fix it, I ran: `chef gem install excon` - to upgrade it to 0.45.4 - based on [IRC #chef chat](https://botbot.me/freenode/chef/2015-08-21/?msg=28605368&page=6) (search for Excon).

**Comment by pierrei** [comment]
:+1: for running `gem install excon`. That fixed it for me!

**Comment by srasi1** [comment]
gem install excon

Yes, this fixed the issue for me as well..

**Comment by geemus** [comment]
Thanks, I'll call this closed then.
