### ISSUE TITLE
Decompress middleware fails when response body is empty

### ISSUE THREAD

**Issue by aesterline** [excon/excon#533]
When using the Decompress middleware, if the server responds with an empty body the middleware fails with the following error.

    not in gzip format (Zlib::GzipFile::Error)
    excon-0.45.3/lib/excon/middlewares/decompress.rb:24:in `initialize'
    excon-0.45.3/lib/excon/middlewares/decompress.rb:24:in `new'
    excon-0.45.3/lib/excon/middlewares/decompress.rb:24:in `response_call'

I notice several servers respond this way when you combine gzip compression and `If-None-Match` or `If-Modfied-Since`. I would be happy to submit a pull request that checks to make sure the response body isn't empty before attempting decompression.

Thoughts?

**Comment by geemus** [comment]
Sounds good, I just hadn't happened across that but can't say I'm surprised. I would welcome the associated PR, just let me know if you have questions or anything I can help with.

**Comment by aesterline** [comment]
I was able to write a test that reproduced the bug. Let me know how I can make this better. I was a little unsure if I wrote the test in the correct way.

**Comment by geemus** [comment]
I think the tests are probably good enough for the time being at least, thanks!
