### ISSUE TITLE
Ruby Timouts and Background Jobs

### ISSUE THREAD

**Issue by seanhandley** [excon/excon#537]
@geemus I might be way off here but I thought I'd ask anyhow.

Having read [this](http://www.mikeperham.com/2015/05/08/timeout-rubys-most-dangerous-api/), and having experienced long-standing stability issues with our app, I wondered if Excon's use of Timeout could lead to trouble in a threaded queue system like Sidekiq.

One of my app's features is to generate usage information based on OpenStack's metering service and I've been using background jobs with Fog to query the service (it can take up to 30 seconds to return data so it makes no sense to do it from within the Rails process).

As a result, I think a lot of timeouts are likely to happen in a given week and eventually (if Mike's blog is accurate) the usage of Ruby's Timeout library in Excon could lead to trouble.

So my question: Done much testing between Excon and Sidekiq? Any similar issues raised before (I can't find any...)?

**Comment by seanhandley** [comment]
Ah, never mind. Turned this up in my digging: https://github.com/excon/excon/issues/440

**Comment by geemus** [comment]
@seanhandley yeah, I don't have much direct experience, but it seems a few others have. So hopefully that can help pin it down and/or give you some people who might be able to answer questions more readily.
