### ISSUE TITLE
Basic auth username/password may be altered before base64 encoded if special characters are used

### ISSUE THREAD

**Issue by stephenchu** [excon/excon#538]
The basic auth username and password are both `Utils.unescape_form`-ed before being base64 encoded into the request header. The unescaping can get rid of special characters such as `%` and `+` in the password, which renders the authentication to never succeed.

I don't _think_ we should alter the original value of username and password. The Ruby implementation here treats them as-is as well [here](https://github.com/ruby/ruby/blob/ruby_2_2/lib/net/http/header.rb#L428-L430).

**Comment by bjhaid** [comment]
:+1:
