### ISSUE TITLE
Nil exception in response parsing

### ISSUE THREAD

**Issue by atombender** [excon/excon#545]
This happens to us occasionally:

```
Excon::Errors::SocketError: undefined method `bytesize' for nil:NilClass (NoMethodError)
/srv/dolphin/build/bundler/ruby/2.1.0/gems/excon-0.45.4/lib/excon/response.rb:135:in `parse'
/srv/dolphin/build/bundler/ruby/2.1.0/gems/excon-0.45.4/lib/excon/middlewares/response_parser.rb:6:in `response_call'
/srv/dolphin/build/bundler/ruby/2.1.0/gems/excon-0.45.4/lib/excon/connection.rb:372:in `response'
/srv/dolphin/build/bundler/ruby/2.1.0/gems/excon-0.45.4/lib/excon/connection.rb:236:in `request'
/srv/dolphin/build/bundler/ruby/2.1.0/gems/excon-0.45.4/lib/excon.rb:229:in `get'
```

`IO#read` can indeed return `nil` if the stream ends prematurely, but the code never checks for it.

**Comment by geemus** [comment]
@atombender thanks for the heads up. What do you think the proper behavior should be in that case? How often does it come up? Thanks!

**Comment by atombender** [comment]
Only come up a couple of times so far, and it's not something I can reproduce. I'm not sure — I think the absence of an exception means it should be handled as EOF.

**Comment by geemus** [comment]
Hmm. So I'm guessing maybe it should raise at that point? In most cases it would mean a premature/unexpected end of stream as you suggest.

**Comment by atombender** [comment]
Given that it has the content length, yes, indeed. I see that for [the other case](https://github.com/excon/excon/blob/master/lib/excon/response.rb#L158), when you don't have the length, you actually correctly expect `nil` on EOF.

**Comment by geemus** [comment]
@atombender I think this should be addressed by #549, could you check it out and let me know? Thanks!

**Comment by atombender** [comment]
Looks good to me.

**Comment by geemus** [comment]
Cool, thanks!
