### ISSUE TITLE
Host header for HTTP requests over UNIX sockets not empty

### ISSUE THREAD

**Issue by Papierkorb** [excon/excon#547]
Hello,

Today I noticed that with the latest Docker, the `docker-api` gem failed to communicate with the Docker daemon. It always returned a "400 Bad Request" response.

After some digging I found that on the HTTP gem it uses (`excon`) does not set the value for the `Host` header in the request is not *empty* for requests over UNIX sockets.

I reproduced the issue with the following set up on my Linux computer:

1. Use the *socat* tool to open a UNIX listen socket: `socat UNIX-LISTEN:foo.sock STDOUT`
2. Open irb or pry in another window, require 'excon' and do a GET request: `Excon.get 'unix:/foo.sock/whatever', socket: 'foo.sock'`  (Note: The example expects that both commands have the same working directory)

This gives the following output in the `socat` window:

    GET /foo.sock/whatever HTTP/1.1
    User-Agent: excon/0.45.4
    Host: foo.sock

Please note the value for the `Host` header is `foo.sock`. But according to the specification of HTTP it must be empty. Reference [RFC2616, Section 14.26](https://tools.ietf.org/html/rfc2616#section-14.23):

    A client MUST include a Host header field in all HTTP/1.1 request
    messages . If the requested URI does not include an Internet host
    name for the service being requested, then the Host header field MUST
    be given with an empty value.

Thanks for reading!

**Comment by geemus** [comment]
Hey, proposed fix in #548, could you try that and see if it works better? Thanks!
