### ISSUE TITLE
data/cacert.pem

### ISSUE THREAD

**Issue by johnbell84** [excon/excon#555]
Hi,

I think there may have been an accidental overwrite of data/cacert.pem in this commit:

https://github.com/excon/excon/commit/16b1327b2af57debac032c5d0e13245b7f77a773

The file used to contain various CA Root certs & now contains some HTML for an HTTP 301 message, which I assume is unintentional?

Thanks,

John

**Comment by geemus** [comment]
Yeah, I'll take a look, thanks.

**Comment by Paxa** [comment]
https://github.com/excon/excon/blob/16b1327b2af57debac032c5d0e13245b7f77a773/data/cacert.pem
```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://curl.haxx.se:80/ca/cacert.pem">here</a>.</p>
<hr>
<address>Apache Server at curl.haxx.se Port 80</address>
</body></html>
```
