### ISSUE TITLE
Excon should combine HTTP headers and body into a single `write()` call

### ISSUE THREAD

**Issue by nelhage** [excon/excon#556]
This is the same issue as #233, which was regressed by the fix to #266.

Excon currently suffers from the same issue as outlined in https://gocardless.com/blog/in-search-of-performance-how-we-shaved-200ms-off-every-post-request/; Because the HTTP headers and body are sent in separate packets, the combination of Nagle's algorithm and TCP delayed ACKs can add up to 200ms to request latency.

**Comment by geemus** [comment]
Closed by #559
