### ISSUE TITLE
Nested request within response_block IOError "closed stream"

### ISSUE THREAD

**Issue by nehalrp** [excon/excon#560]
When calling `Connection#request` from within the `response_block` of another call to `Connection#request`, the nested call causes the outer call to encounter an IOError (`closed stream`).  Note that this happens when using a **_different**_ `Connection` instance in the nested block.

We encountered this when using the [docker-api gem](https://github.com/swipely/docker-api) to query the docker API (against `/var/run/docker.sock`).  We stream docker events from the `/events` endpoint and then within the `response_block` make non-blocking requests against the `/containers/ID/json` endpoint.

We reproduced this using only the excon lib separate from the docker-api lib.

To reproduce with docker:

``` ruby
def request(path, &block)
  h = {
    method: :get,
    path: path,
    headers:{'Content-Type' => 'text/plain', 'User-Agent'=> 'asdf'},
    expects: (200..204).to_a << 304,
    idempotent: true
  }
  h[:response_block] = block if block_given?
  Excon.new('unix:///', socket: '/var/run/docker.sock').request(h)
end

request('/events') do |b|
  puts "OUTER"
  request('/containers/782b57ed156f4378e2f0588b5f5bf20418b8a8fc53e4874684a25cc867cd355d/json')
  puts "AFTER"
end
```

Backtrace:

```
/usr/local/rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/excon-0.48.0/lib/excon/socket.rb:168:in `read_nonblock': closed stream (IOError) (Excon::Errors::SocketError)
        from /usr/local/rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/excon-0.48.0/lib/excon/socket.rb:168:in `read_nonblock'
        from /usr/local/rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/excon-0.48.0/lib/excon/socket.rb:35:in `read'
        from /usr/local/rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/excon-0.48.0/lib/excon/response.rb:121:in `parse'
        from /usr/local/rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/excon-0.48.0/lib/excon/middlewares/response_parser.rb:6:in `response_call'
        from /usr/local/rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/docker-api-1.26.2/lib/excon/middlewares/hijack.rb:45:in `response_call'
        from /usr/local/rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/excon-0.48.0/lib/excon/connection.rb:389:in `response'
        from /usr/local/rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/excon-0.48.0/lib/excon/connection.rb:253:in `request'
        from /usr/local/rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/excon-0.48.0/lib/excon/middlewares/idempotent.rb:26:in `error_call'
        from /usr/local/rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/excon-0.48.0/lib/excon/middlewares/base.rb:10:in `error_call'
        from /usr/local/rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/excon-0.48.0/lib/excon/middlewares/base.rb:10:in `error_call'
        from /usr/local/rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/excon-0.48.0/lib/excon/middlewares/base.rb:10:in `error_call'
        from /usr/local/rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/excon-0.48.0/lib/excon/connection.rb:273:in `rescue in request'
        from /usr/local/rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/excon-0.48.0/lib/excon/connection.rb:221:in `request'
        from /usr/local/rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/excon-0.48.0/lib/excon/middlewares/idempotent.rb:26:in `error_call'
        from /usr/local/rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/excon-0.48.0/lib/excon/middlewares/base.rb:10:in `error_call'
        from /usr/local/rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/excon-0.48.0/lib/excon/middlewares/base.rb:10:in `error_call'
        from /usr/local/rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/excon-0.48.0/lib/excon/middlewares/base.rb:10:in `error_call'
        from /usr/local/rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/excon-0.48.0/lib/excon/connection.rb:273:in `rescue in request'
        from /usr/local/rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/excon-0.48.0/lib/excon/connection.rb:221:in `request'
        from /usr/local/rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/excon-0.48.0/lib/excon/middlewares/idempotent.rb:26:in `error_call'
        from /usr/local/rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/excon-0.48.0/lib/excon/middlewares/base.rb:10:in `error_call'
        from /usr/local/rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/excon-0.48.0/lib/excon/middlewares/base.rb:10:in `error_call'
        from /usr/local/rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/excon-0.48.0/lib/excon/middlewares/base.rb:10:in `error_call'
        from /usr/local/rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/excon-0.48.0/lib/excon/connection.rb:273:in `rescue in request'
        from /usr/local/rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/excon-0.48.0/lib/excon/connection.rb:221:in `request'
        from /usr/local/rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/docker-api-1.26.2/lib/docker/connection.rb:40:in `request'
        from /usr/local/rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/docker-api-1.26.2/lib/docker/connection.rb:65:in `block (2 levels) in <class:Connection>'
        from /usr/local/rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/docker-api-1.26.2/lib/docker/event.rb:20:in `stream'
```

@roberthoner

**Comment by nehalrp** [comment]
By the way, sometimes the issue resolve itself when it's retried by the `Idempotent` middleware.  So to produce the error consistently, we lowered the `retries_remaining`.  However, in our application, it consistently fails even with the default of 4 attempts.

**Comment by geemus** [comment]
Hmm, I think this may be a unix socket specific thing, which is an area of the code that has seen less use/testing (and which I have less knowledge of). It should be setting up a new socket, so far as ruby is concerned anyway, when you create a new connection here. I suspect since both refer to the same unix socket reference, it may not play out that way though (but again I don't know much about unix sockets). Do you have more experience/knowledge there? I suspect the culprit may be in https://github.com/excon/excon/blob/master/lib/excon/unix_socket.rb somewhere, but nothing jumps out for me.

**Comment by roberthoner** [comment]
Yeah, based on our review of the code, no resources including the ruby socket are shared, which makes it particularly odd.  We don't have any particular unix socket experience either.  Perhaps something is shared at the ruby or OS level, which seems dirty, but I don't know enough to rule it out.

**Comment by geemus** [comment]
Yeah, my suspicion was that it might be that since we refer to the same file location for the socket in both cases, it is being reused even though we instantiate new ruby objects. Unfortunately I don't know enough about unix sockets to make much more of an assertion than that.

@tlunter as the originator of this code, any chance you have a greater level of insight for us? Thanks!

**Comment by tlunter** [comment]
I don't honestly.  I think an obvious test is to make a long running request to the docker daemon, and then a short one during that request to prove that it's possible to make two requests at once (I'm sure this is possible given my use of docker and `docker run -it`).  @nehalrp have you had a chance to try different ruby versions? I'm curious if this is a bug in ruby somewhere.  When you said it, "sometimes the issue resolve itself when it's retried by the Idempotent middleware", do you mean sometimes it actually works?

**Comment by nehalrp** [comment]
1) Different ruby versions
Yes, we actually have tried it with 1.9.3 and 2.1.8 thinking it could be a ruby issue, but that did not make a difference.


2) Idempotent middleware
Yea, so in the focused reproduction scenario which I provided, when `retries_remaining` is left on the default of 4, it finishes successfully. However, when lowering this to 1, it fails. So it seems it takes few couple iterations for it to complete. However in our actual application where we are leveraging this logic, even the default of 4 always fails. We are wondering why this even fails even during it's first pass, let alone a few more.
