### ISSUE TITLE
JRuby S3 Upload - Broken Pipe exception

### ISSUE THREAD

**Issue by creddy** [excon/excon#562]
Using JRuby and CarrierWave to upload to S3 results in `Excon::Errors::SocketError: Broken pipe (IOError)`

After searching I found https://github.com/excon/excon/issues/345. Setting `Excon.defaults[:nonblock] = false` does indeed result in a successful upload. We have other gems using Excon and I'm wary of setting a global config. Issue #345 was closed due to inactivity. 

My hope with opening this issue is to provide information as needed, and follow up with any requests so that we may find a resolution. To that end:

[Here](https://github.com/creddy/excon-test) is my paired down code I used to reproduce the issue. 
##### Failure cases

[Here](https://gist.github.com/creddy/20e63c79d1560c263f48#file-jruby-1-7-23) is the Excon debug log when using JRuby 1.7.23 which throws the exception
[Here](https://gist.github.com/creddy/20e63c79d1560c263f48#file-jruby-9-0-5-0) is the Excon debug log when using JRuby 9.0.5.0 which throws the exception
[Here](https://gist.github.com/creddy/20e63c79d1560c263f48#file-jruby-9-0-5-0-excon-master-f86765e4e5e81493e1cd3ff6d97a8c0c882be5e3) is the Excon debug log when using JRuby 9.0.5.0 and Excon Master at (f86765e4e5e81493e1cd3ff6d97a8c0c882be5e3) which throws the exception
##### Success cases

[Here](https://gist.github.com/creddy/20e63c79d1560c263f48#file-jruby-1-7-23-excon-defaults-nonblock-false) is the Excon debug log when using JRuby 1.7.23 and `Excon.defaults[:nonblock] = false` which succeeds
[Here](https://gist.github.com/creddy/20e63c79d1560c263f48#file-ruby-2-3-0) is the Excon debug log when using Ruby 2.3.0 which succeeds

**Comment by geemus** [comment]
Sorry to hear you are having issues here. Are the requests to an https server? I wonder if it might have something to do with some of the timeout issues that also seemed to go away with nonblock off which were fixed on master (but not yet released). Could you try against master and see if you have any better luck? Not really sure how/why jruby would be acting differently here...

**Comment by creddy** [comment]
Indeed, I'm attempting to upload to S3 over https. 

I ran the test against f86765e4e5e81493e1cd3ff6d97a8c0c882be5e3 and unfortunately I see the same error.

**Comment by geemus** [comment]
Is this a long running process? Is it possible there is a delay (for whatever reason, processing stuff maybe) between opening the connection and writing to it? It would probably need to be 30 seconds or more though for me to expect something like this. It also looks like it just-works in newer jruby? I notice in the failure case it seems to fail right away (and then retry multiple times), which also seems a bit weird.

**Comment by creddy** [comment]
The whole test takes about 10 seconds including JVM boot time, and takes about 6 seconds from start of upload to the time the exception is thrown. 

Good point about newer JRuby. I've added Excon logs for JRuby 9.0.5.0 (I can also try JRuby head if you'd like) as well as the log for JRuby 9.0.5.0 and Excon master to the issue above.

**Comment by geemus** [comment]
@creddy thanks for the extra details. I haven't had a chance to really dig in further or find anything just yet, but hope to revisit.

**Comment by geemus** [comment]
Hey, I seem to have forgotten/lost track of this. Are there any further updates or things we need to do here? Thanks!

**Comment by creddy** [comment]
Hello @geemus. I just tried again with the latest JRuby 9.1.6.0 and I still see this issue. 

#### Ruby 2.3.3

```
➜  excon-test [2.3.3] (master) rake
Ruby description: ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin16]
➜  excon-test [2.3.3] (master)
```

#### JRuby 9.1.6.0

```
➜  excon-test [jruby-9.1.6.0] (master) rake
Ruby description: jruby 9.1.6.0 (2.3.1) 2016-11-09 0150a76 Java HotSpot(TM) 64-Bit Server VM 25.74-b02 on 1.8.0_74-b02 [darwin-x86_64]
rake aborted!
Excon::Errors::SocketError: Broken pipe (IOError)
org/jruby/ext/openssl/SSLSocket.java:867:in `syswrite_nonblock'
test.rb:19:in `<main>'
/SAPDevelop/Projects/external/excon-test/Rakefile:1:in `block in (root)'
/SAPDevelop/Projects/external/excon-test/Rakefile:9:in `block in (root)'
IOError: Broken pipe
org/jruby/ext/openssl/SSLSocket.java:867:in `syswrite_nonblock'
test.rb:19:in `<main>'
/SAPDevelop/Projects/external/excon-test/Rakefile:1:in `block in (root)'
/SAPDevelop/Projects/external/excon-test/Rakefile:9:in `block in (root)'
Tasks: TOP => default => test
(See full trace by running task with --trace)
```

**Comment by geemus** [comment]
Hmm. I'm not sure how to better work on this. I wonder if it is actually an issue with jruby itself? I haven't done enough in/with it to know what else to look at.
