### ISSUE TITLE
Redirects are using :get for requests instead of :head

### ISSUE THREAD

**Issue by IceDragon200** [excon/excon#564]
In most cases, servers return all the needed data in their header, instead of using a [get request](https://github.com/excon/excon/blob/master/lib/excon/middlewares/redirect_follower.rb#L31) (and potentially pulling large amounts of data in that will be [thrown out anyway](https://github.com/excon/excon/blob/master/lib/excon/middlewares/redirect_follower.rb#L32)), shouldn't this a `:head` instead of `:get`?

**Comment by geemus** [comment]
The idea is that here a request has already occurred and the response was a redirect, so you make a GET to the final location. I think that is inline with the expectations set out in the relevant RFCs. HEAD would provide further info if there is yet-another-redirect, but I wouldn't expect that to be the normal case. Ideally most cases would be following a single redirect to the final location.

**Comment by IceDragon200** [comment]
@geemus Ah, I was using the redirect middleware to get the final path of a request, which I then pass into a downloader to retrieve the data.
Would it be possible to allow users to configure the redirect request method?

Something like:
```ruby
# defaults to :get
datum[:redirect_method] = :head 
```

**Comment by geemus** [comment]
Possibly, though the faster/easier solution, at least for now, may be for you to create your own middleware (starting at least as a copy of this) that follows the desired behavior? We could look at what those changes to this might look like and discuss, but yeah, just doing it on your end is probably quickest way to start.

**Comment by IceDragon200** [comment]
@geemus Yep, I've made my own middleware locally, just thought I'd pass the idea by :)

**Comment by geemus** [comment]
Great, thanks for the input!

**Comment by geemus** [comment]
I think this was enough of a special case that I'm satisfied with a custom-middleware to solve it. Closing this for now, but we can revisit if we find out there is a broader need. Thanks!
