### ISSUE TITLE
Excon::Hypermedia library

### ISSUE THREAD

**Issue by JeanMertz** [excon/excon#568]
I've just pushed the first version of the `excon-hypermedia` library:

https://github.com/JeanMertz/excon-hypermedia

As mentioned in https://github.com/excon/excon/issues/567, it's a very small library on top of Excon, and needs a lot more work before it can be used as a replacement for the likes of [HyperResource](https://github.com/gamache/hyperresource) and [HyperClient](https://github.com/codegram/hyperclient).

Still, I think `excon-hypermedia`'s strength is that it uses all the default Excon objects/logics, and simply adds some "smarts" on top of it.

I just wanted to share this with you, maybe you want to eventually merge this into Excon (although I don't think there's a big need), or maybe you have some ideas/suggestions.

**Comment by geemus** [comment]
Cool, just let me know if you have questions/suggestions. As you suggest, I imagine a lot of this living on it's own and building on top of excon is a great approach (at least to start). In time we can consider if some or all of it might have a home within the main gem, but in the meantime we should certainly at least link to it (see the other issue on excon-addressable for more concrete thoughts on that). Thanks!

**Comment by geemus** [comment]
I think now that we added the links to the README there isn't anything else to be done here, but let me know if I missed something. Thanks!
