### ISSUE TITLE
1.0 release

### ISSUE THREAD

**Issue by zimbatm** [excon/excon#570]
Any plans on releasing version 1.0 ?

Excon is pretty stable and it would be nice to benefit from semver (if you follow it) by marking the current release as stable.

**Comment by geemus** [comment]
Not particularly concrete plans at present. I do my best to maintain/operate it as stable even now (treating it pretty much like it is already 1.0), but actually calling it that would communicate a lot more. My hesitation has been that it seems like if there are breaking changes to make, now would be the time to do it (pre-1.0). But as those changes seem continually to not happen, and as 2.0 could just as easily be cut to communicate that, perhaps I should just pull the trigger.

**Comment by zimbatm** [comment]
I think it's time to let the baby fly :)

Excon is the best ruby http library and I've used them all. Bringing it to
1.0 is a good signal for the rest of the community.

**Comment by sandstrom** [comment]
One breaking change that I'd be happy to see is the one you outline here: https://github.com/excon/excon/issues/384#issuecomment-42683405

**Comment by geemus** [comment]
@sandstrom yeah, I would almost assuredly drop default port (or at least switch the default to be omitting). Dropping old ruby support would definitely make our lives easier as well, though I'm not sure what the right cut-off is (guess we'll have to make that judgement call at the time we make the release).

**Comment by geemus** [comment]
Pinning, just need to carve out some time.

**Comment by geemus** [comment]
Closing as dup of #295
