### ISSUE TITLE
test freezing

### ISSUE THREAD

**Issue by bh-i** [excon/excon#574]
when running test, it is freezing at  *Excon redirecting with cookie preserved*

**Comment by geemus** [comment]
They seem to be working ok for me locally and appear to have finished on the last run on travis. Could you elaborate on how you are running tests, what ruby you are using, and which OS? It may also be possible if you have run tests multiple times and/or `ctrl-c` out of things that something got left behind (so checking `ps` and cleaning up things and/or restarting the machine may help).

**Comment by bh-i** [comment]
I was packaging excon for debian [dependency of gitlab]
I am using debian unstable, ruby version:ruby 2.3. I used gem2deb tool for building. 
The test case tests/middlewares/capture_cookies_tests.rb was getting freezed. So I commented out the following lines, 

*Shindo.tests("Excon redirecting with cookie preserved") do*
 *env_init*

Then it was fine. Dont know the reason

**Comment by geemus** [comment]
Hmm, thanks for the extra details. I reviewed that test vs other ones and unfortunately nothing in particular is jumping out at me as a likely culprit/issue. If you find more info or are able to pin it down more tightly, do let me know. `env_init` as noted here should be fine (I think) as it is used in a lot of the other tests also, so I suspect it must be something deeper into that test set.

**Comment by bh-i** [comment]
Sorry @geemus , I think problem was with my versions of ruby gems . 
This issue can be closed

**Comment by geemus** [comment]
No worries, thanks for the update.
