### ISSUE TITLE
Support for Ruby 3.0 frozen strings

### ISSUE THREAD

**Issue by kitop** [excon/excon#585]
In Ruby 3.0 string literals will be frozen by default. Right now, in Ruby 2.3 that can be opted in by running with `--enable-frozen-string-literal` or via magic comments.

This blog contains more info: https://wyeworks.com/blog/2015/12/1/immutable-strings-in-ruby-2-dot-3

Is this something `excon` worries about? I was running some test suites with frozen strings enabled and threw an error in `excon`.

I'm more than happy to provide a PR if this is something the maintainers care about. What I have in mind is to add magic comments to _all_ of the files, and fix tests accordingly. If a string is returned to the user, it can cause some trouble if it's frozen and the user modifies it. This would also be something to check.
There might be a very small performance hit, but at the same time most of the strings used are being re-used as they are HTTP headers, so some GC should be reduced because of that.

**Comment by geemus** [comment]
I would be open to getting this fixed. Seems likely to be inevitable anyway (and hopefully the performance isn't too negatively impacted). Happy to discuss.

**Comment by starbelly** [comment]
Not a maintainer, just some guy : ) I dig it. I'm always in favor of getting ready for the future, especially when it doesn't impact the past (legacy).

**Comment by kitop** [comment]
Will start working on this and send a PR as soon as something's ready, to continue discussion.
Thanks!

**Comment by geemus** [comment]
Sounds great, thanks!

On Fri, Jul 15, 2016 at 2:32 PM, Esteban Pastorino <notifications@github.com

**Comment by geemus** [comment]
This was taken care of by #586, just forgot to close this after.
