### ISSUE TITLE
Excon::Error::Socket: getaddrinfo: No address associated with hostname (SocketError)

### ISSUE THREAD

**Issue by peter-umb** [excon/excon#590]
Rails 4.2.0
Ruby 2.2.2
Amazon AWS S3
fog-aws 0.10.0
Excon 0.51.0

Around 99% of the time we have no issues. The issue usually only happens during times when usage is high but I noticed it happen when there were almost no users as well. The line that throws the error:

     # excon/lib/excon/socket.rb
     # line 100 inside the connection method.
     addrinfo = ::Socket.getaddrinfo(*args)

The error happens everywhere in the application. It does not seem to matter if I am requesting another url or one of the routes for our site.

I used Rails loggers to capture the arguments being passed in and there is seemingly no difference between a pass and a fail.

I came across several forums that lead me to believe an update was needed to the excon gem. I upgraded the Excon gem from 0.45.4 to 0.51.0. In addition to that I also updated the Fog gem from 1.36.0 to 1.38.0.

After upgrading the error went from "getaddrinfo: Name or service not known (SocketError)" to "Excon::Error::Socket: getaddrinfo: No address associated with hostname (SocketError)"

**Comment by starbelly** [comment]
@peter-umb I've run into this problem before, with other software besides excon. For me it was always an ipv6 issue. I would either try disabling ipv6 if possible. If not, do you have an ipv6 host name in your /etc/hosts file? (assuming this is *nix).

**Comment by peter-umb** [comment]
# /etc/hosts
127.0.0.1       localhost
127.0.1.1       09348-23409-3294393

**Comment by starbelly** [comment]
@peter-umb Is ipv6 enabled though?

**Comment by peter-umb** [comment]
It would seem that is not enabled. The result of "lsmod | grep ipv6" returned nothing. Is there another way to check?

**Comment by starbelly** [comment]
@peter-umb Yeah, that should definitely tell you if it's loaded in the kernel. I'd also check the results of ifconfig though, if ipv6 is enabled you'll have an ipv6 address. ipv6 aside... 

 Check out this post: 

 https://forums.gentoo.org/viewtopic.php?p=519288

**Comment by peter-umb** [comment]
ifconfig does indeed have an ipv6 address.

**Comment by peter-umb** [comment]
Is there a way to test your theory with out disabling ipv6? I have a feeling doing so would mess up my load balancer which I do not have access to. :(

**Comment by starbelly** [comment]
@peter-umb Yeah, you can run hostname (e.g., hostname -d, hostname -i, hostname -d ) or run various `dig`s or nslookup, or even just ping. I would do this an infinite loop, since it sounds intermittent. Something like `while true; do ping foo.bar; nslookup foo.bar; sleep 3; done` You could also try giving your ipv6 address a hostname in /etc/hosts.

**Comment by peter-umb** [comment]
Wonderful suggestion. I will test.

**Comment by peter-umb** [comment]
No luck getting it to break in the suggested manner. I have logged several of the failed arguments and the ones that fail have an appended "-us-west-1" in the url. This leads me to believe everything is fine with Excon and the error may reside with amazon. I will keep plugging away at this but in the mean time I will close this issue.

**Comment by geemus** [comment]
Sorry to hear it didn't play out, hope you can figure something out and let us know if there is anything else we can help with.

**Comment by lenovouser** [comment]
I am getting this too. `ping` and `curl` works just fine on the hostname 😢

**Comment by geemus** [comment]
You might also try with options set for `omit_default_port: true`. Often if ping/curl work and excon doesn't, this can be the culprit.

**Comment by peter-umb** [comment]
Sorry for the late reply - Where do you set the omit_default_port? Our application never specifically invokes the Excon gem. It is loaded as a dependency. Is there a way to globally set all Excon connections to omit the default port?

**Comment by peter-umb** [comment]
It looks like Excon gets called from Fog. Do you suggest forking the gems that use Excon and updating the connection calls to include omit_default_port? Stack trace of recent error:

…undle/ruby/2.2.0/gems/excon-0.54.0/lib/excon/
socket.rb: 101:in `getaddrinfo'
…undle/ruby/2.2.0/gems/excon-0.54.0/lib/excon/
socket.rb: 101:in `connect'
…e/ruby/2.2.0/gems/excon-0.54.0/lib/excon/
ssl_socket.rb: 153:in `connect'
…undle/ruby/2.2.0/gems/excon-0.54.0/lib/excon/
socket.rb:  29:in `initialize'
…e/ruby/2.2.0/gems/excon-0.54.0/lib/excon/
ssl_socket.rb:   9:in `initialize'
…e/ruby/2.2.0/gems/excon-0.54.0/lib/excon/
connection.rb: 403:in `new'
…e/ruby/2.2.0/gems/excon-0.54.0/lib/excon/
connection.rb: 403:in `socket'
…e/ruby/2.2.0/gems/excon-0.54.0/lib/excon/
connection.rb: 100:in `request_call'
…/2.2.0/gems/excon-0.54.0/lib/excon/middlewares/
mock.rb:  48:in `request_call'
…ems/excon-0.54.0/lib/excon/middlewares/
instrumentor.rb:  26:in `request_call'
…/2.2.0/gems/excon-0.54.0/lib/excon/middlewares/
base.rb:  16:in `request_call'
…/2.2.0/gems/excon-0.54.0/lib/excon/middlewares/
base.rb:  16:in `request_call'
…/2.2.0/gems/excon-0.54.0/lib/excon/middlewares/
base.rb:  16:in `request_call'
…e/ruby/2.2.0/gems/excon-0.54.0/lib/excon/connection.rb: 249:in `request'
…/gems/excon-0.54.0/lib/excon/middlewares/
idempotent.rb:  27:in `error_call'
…/2.2.0/gems/excon-0.54.0/lib/excon/middlewares/
base.rb:  11:in `error_call'
…/2.2.0/gems/excon-0.54.0/lib/excon/middlewares/
base.rb:  11:in `error_call'
…e/ruby/2.2.0/gems/excon-0.54.0/lib/excon/connection.rb: 272:in `rescue in request'
…e/ruby/2.2.0/gems/excon-0.54.0/lib/excon/connection.rb: 215:in `request'
…/gems/excon-0.54.0/lib/excon/middlewares/idempotent.rb:  27:in `error_call'
…/2.2.0/gems/excon-0.54.0/lib/excon/middlewares/
base.rb:  11:in `error_call'
…/2.2.0/gems/excon-0.54.0/lib/excon/middlewares/base.rb:  11:in `error_call'
…e/ruby/2.2.0/gems/excon-0.54.0/lib/excon/connection.rb: 272:in `rescue in request'
…e/ruby/2.2.0/gems/excon-0.54.0/lib/excon/connection.rb: 215:in `request'
…/gems/excon-0.54.0/lib/excon/middlewares/idempotent.rb:  27:in `error_call'
…/2.2.0/gems/excon-0.54.0/lib/excon/middlewares/
base.rb:  11:in `error_call'
…/2.2.0/gems/excon-0.54.0/lib/excon/middlewares/
base.rb:  11:in `error_call'
…e/ruby/2.2.0/gems/excon-0.54.0/lib/excon/connection.rb: 272:in `rescue in request'
…e/ruby/2.2.0/gems/excon-0.54.0/lib/excon/connection.rb: 215:in `request'
…/2.2.0/gems/fog-core-1.43.0/lib/fog/core/connection.rb:  81:in `request'
…uby/2.2.0/gems/fog-xml-0.1.2/lib/fog/xml/
connection.rb:   9:in `request'
…/ruby/2.2.0/gems/fog-aws-0.10.0/lib/fog/aws/
storage.rb: 611:in `_request'
…/ruby/2.2.0/gems/fog-aws-0.10.0/lib/fog/aws/
storage.rb: 606:in `request'
…-aws-0.10.0/lib/fog/aws/requests/storage/
get_object.rb:  57:in `get_object'
…onfly-s3_data_store-1.2/lib/dragonfly/s3_data_store.rb:  62:in `block in read'
…onfly-s3_data_store-1.2/lib/dragonfly/s3_data_store.rb: 173:in `rescue in rescuing_socket_errors'
…onfly-s3_data_store-1.2/lib/dragonfly/s3_data_store.rb: 170:in `rescuing_socket_errors'
…onfly-s3_data_store-1.2/lib/dragonfly/s3_data_store.rb:  62:in `read'
…/2.2.0/gems/dragonfly-1.1.1/lib/dragonfly/job/
fetch.rb:  13:in `apply'
…e/ruby/2.2.0/gems/dragonfly-1.1.1/lib/dragonfly/job.rb: 119:in `block in apply'
…e/ruby/2.2.0/gems/dragonfly-1.1.1/lib/dragonfly/
job.rb: 119:in `each'
…e/ruby/2.2.0/gems/dragonfly-1.1.1/lib/dragonfly/job.rb: 119:in `apply'
…y/2.2.0/gems/dragonfly-1.1.1/lib/dragonfly/response.rb:  19:in `to_response'
…uby/2.2.0/gems/dragonfly-1.1.1/lib/dragonfly/server.rb:  59:in `block in call'
…uby/2.2.0/gems/dragonfly-1.1.1/lib/dragonfly/
server.rb:  55:in `catch'
…uby/2.2.0/gems/dragonfly-1.1.1/lib/dragonfly/server.rb:  55:in `call'
…2.2.0/gems/dragonfly-1.1.1/lib/dragonfly/middleware.rb:  12:in `call'
…dle/ruby/2.2.0/gems/warden-1.2.7/lib/warden/manager.rb:  36:in `block in call'
…dle/ruby/2.2.0/gems/warden-1.2.7/lib/warden/manager.rb:  35:in `catch'
…dle/ruby/2.2.0/gems/warden-1.2.7/lib/warden/
manager.rb:  35:in `call'
…red/bundle/ruby/2.2.0/gems/rack-1.6.5/lib/rack/etag.rb:  24:in `call'
…/ruby/2.2.0/gems/rack-1.6.5/lib/rack/conditionalget.rb:  25:in `call'
…red/bundle/ruby/2.2.0/gems/rack-1.6.5/lib/rack/
head.rb:  13:in `call'
…2.0/gems/remotipart-1.0.5/lib/remotipart/middleware.rb:  30:in `call'
…-4.2.8/lib/action_dispatch/middleware/params_parser.rb:  27:in `call'
…tionpack-4.2.8/lib/action_dispatch/middleware/
flash.rb: 260:in `call'
…/2.2.0/gems/rack-1.6.5/lib/rack/session/abstract/id.rb: 225:in `context'
…/2.2.0/gems/rack-1.6.5/lib/rack/session/abstract/
id.rb: 220:in `call'
…onpack-4.2.8/lib/action_dispatch/middleware/cookies.rb: 560:in `call'
…ms/activerecord-4.2.8/lib/active_record/query_cache.rb:  36:in `call'
…record/connection_adapters/abstract/connection_pool.rb: 653:in `call'
…pack-4.2.8/lib/action_dispatch/middleware/callbacks.rb:  29:in `block in call'
…ms/activesupport-4.2.8/lib/active_support/callbacks.rb:  88:in `__run_callbacks__'
…ms/activesupport-4.2.8/lib/active_support/callbacks.rb: 778:in `_run_call_callbacks'
…ms/activesupport-4.2.8/lib/active_support/callbacks.rb:  81:in `run_callbacks'
…pack-4.2.8/lib/action_dispatch/middleware/callbacks.rb:  27:in `call'
…pack-4.2.8/lib/action_dispatch/middleware/remote_ip.rb:  78:in `call'
…2.8/lib/action_dispatch/middleware/debug_exceptions.rb:  17:in `call'
….2.8/lib/action_dispatch/middleware/show_exceptions.rb:  30:in `call'
…uby/2.2.0/gems/railties-4.2.8/lib/rails/rack/logger.rb:  38:in `call_app'
…uby/2.2.0/gems/railties-4.2.8/lib/rails/rack/logger.rb:  20:in `block in call'
…tivesupport-4.2.8/lib/active_support/tagged_logging.rb:  68:in `block in tagged'
…tivesupport-4.2.8/lib/active_support/tagged_logging.rb:  26:in `tagged'
…tivesupport-4.2.8/lib/active_support/tagged_logging.rb:  68:in `tagged'
…uby/2.2.0/gems/railties-4.2.8/lib/rails/rack/logger.rb:  20:in `call'
…ses/20170321091242/config/initializers/quiet_assets.rb:   8:in `call_with_quiet_assets'
…ack-4.2.8/lib/action_dispatch/middleware/request_id.rb:  21:in `call'
…/ruby/2.2.0/gems/rack-1.6.5/lib/rack/methodoverride.rb:  22:in `call'
…0/gems/dragonfly-1.1.1/lib/dragonfly/cookie_monster.rb:   9:in `call'
…/bundle/ruby/2.2.0/gems/rack-1.6.5/lib/rack/runtime.rb:  18:in `call'
…ctive_support/cache/strategy/local_cache_middleware.rb:  28:in `call'
…bundle/ruby/2.2.0/gems/rack-1.6.5/lib/rack/sendfile.rb: 113:in `call'
…dle/ruby/2.2.0/gems/railties-4.2.8/lib/rails/engine.rb: 518:in `call'
…uby/2.2.0/gems/railties-4.2.8/lib/rails/application.rb: 165:in `call'
…le/ruby/2.2.0/gems/railties-4.2.8/lib/rails/railtie.rb: 194:in `public_send'
…le/ruby/2.2.0/gems/railties-4.2.8/lib/rails/railtie.rb: 194:in `method_missing'
…lib/phusion_passenger/rack/thread_handler_extension.rb:  97:in `process_request'
…ib/phusion_passenger/request_handler/thread_handler.rb: 152:in `accept_and_process_next_request'
…ib/phusion_passenger/request_handler/thread_handler.rb: 113:in `main_loop'
…c/ruby_supportlib/phusion_passenger/request_handler.rb: 416:in `block (3 levels) in start_threads'
…r-5.1.1/src/ruby_supportlib/phusion_passenger/utils.rb: 113:in `block in create_thread_and_abort_on_exception'

**Comment by geemus** [comment]
Hey, I believe you should just be able to add a one-liner, prior to any connections being initialized like this:

`Excon.defaults[:omit_default_port] = true`

That will override the default value used, which means it will be omitted unless the library explicitly sets it (and I'm fairly sure fog does not). The only other caveat, as mentioned above, is that this needs to occur PRIOR to connection initialization or it won't take effect. More info here: https://github.com/excon/excon#options

**Comment by peter-umb** [comment]
Do you think I could put this in to the dragonfly initializer?

**Comment by geemus** [comment]
I'm not familiar with dragonfly, but probably. If you can set it before you pass in credentials for fog, you should be safe.

**Comment by peter-umb** [comment]
Funny story - I had implemented this fix 2 nights ago in the Dragonfly initializer. When I came in to work Tuesday morning my log was filled with getaddrinfo errors. After cycling the NGINX servers everything seemed to work fine. Wednesday morning, same thing. A large event with many getaddrinfo errors filled my logs. Feeling frustrated I followed up with my question, "Do you think I could put this in to the dragonfly initializer?" and let the line ride another day after your reply. So today I received an email from a colleague outlining a bug pushed to libc6 by the linux maintainers that caused the 'new' getaddrinfo problem. (https://www.theregister.co.uk/2017/03/23/unbuntu_splats_titsup_bug_spread_in_update/) After the fix to libc6 no more errors. It will take a couple of days of clear logs to confirm this is fixed but it looks promising so far. What luck. Thank you for the help!

**Comment by geemus** [comment]
Cool, glad to hear that it sounds like you are on track to have it sorted.

**Comment by jogaco** [comment]
> Hey, I believe you should just be able to add a one-liner, prior to any connections being initialized like this:
> 
> `Excon.defaults[:omit_default_port] = true`
> 
> That will override the default value used, which means it will be omitted unless the library explicitly sets it (and I'm fairly sure fog does not). The only other caveat, as mentioned above, is that this needs to occur PRIOR to connection initialization or it won't take effect. More info here: https://github.com/excon/excon#options

That was really helpful. After uploading about 100K images, I started getting this error and this solved it for now

**Comment by geemus** [comment]
@jogaco great, thanks for letting us know it was helpful. I think it's highly likely that we will eventually change the default to avoid this problem, but I've been reticent to do it as it might in some cases be a breaking change. ie if/when we do a 1.0 it will likely be in the changes, but probably not before then out of an abundance of caution.

**Comment by ciriousjoker** [comment]
For me, disabling ipv6 in mac os solved the issue, where before it was consistently broken.

In my case, the error message was different though:

> no address for api.github.com (resolv::resolverror)

**Comment by geemus** [comment]
@ciriousjoker - Thanks for the heads up, good to know that is another way it can manifest (and hopefully it may help anybody else that runs into it that way too).
