### ISSUE TITLE
Parallel requests support

### ISSUE THREAD

**Issue by colin-jack** [excon/excon#595]
I wondered if there are plans to support parallel requests?

For context I am thinking of something equivalent to the hydra support covered in the typhoeus documentation.

**Comment by geemus** [comment]
Nothing explicitly planned, though I believe this is thread-safe, so one could manage such a setup themselves. Could you describe the kind of use case you have in mind and maybe a rough sketch of what you imagine the interface might look like?

**Comment by djberg96** [comment]
Why not use pipelining?

**Comment by geemus** [comment]
Leaving this as a DIY feature, rather than integrating, due to lack of interest. Happy to revisit if we hear otherwise though.
