### ISSUE TITLE
Allow ssl assets to be strings of already read content

### ISSUE THREAD

**Issue by hekaldama** [excon/excon#597]
Excon should allow ssl assets to be strings that have already been read into the program. This is particularly useful when these assets are obtained from secure storage via remote APIs and are already in memory (therefore no longer needing to be `File.read`).

PR to follow.

**Comment by geemus** [comment]
Sounds reasonable, let me know if you have any questions or need help.

**Comment by hekaldama** [comment]
@geemus thanks! I am currently running into `OpenSSL::SSL::SSLContext.new.ca_file` seeming to only support a file and not a already loaded file. Any ideas on that one? Was going to ask a ruby core dev about it when he gets in.

**Comment by hekaldama** [comment]
@geemus seems like it will take some changes to the core in the C code. Do you still want a PR for this even if it is only for the certificate and private key? It will still be helpful if people are using `ssl_verify_peer: false`. LMK

**Comment by geemus** [comment]
Sounds alright. Going to close this for now since 1. we can't fix part of it and 2. the part we can fix we can discuss directly on the relevant PR.
