### ISSUE TITLE
excon failed to connect to host: ipv4 is reachable and ipv6 addr is not reachable

### ISSUE THREAD

**Issue by NiCkEl5** [excon/excon#603]
I have problem when exconn is trying to connect to a host that has ipv4 and ipv6 enable but if ipv6 is not reachable the exconn crashes why is that if the ipv4 address is reachable, is there a way to avoid this?

here is the exception

/usr/local/rvm/gems/ruby-2.1.2@extra_info/gems/excon-0.54.0/lib/excon/socket.rb:123:in `connect_nonblock': Network is unreachable - connect(2) for [2610:a0:16:4::fff8]:443 (Errno::ENETUNREACH) (Excon::Error::Socket)

here is the addrinfo variable value in the connect procedure that shows the values for both ip

[["AF_INET", 443, "XXX.XXX.XX.XXX", "XXX.XXX.XX.XXX", 2, 1, 6], ["AF_INET6", 443, "XXXX:aX:XX:X::fff8", "XXXX:a0:XX:X::fffX", 10, 1, 6]]

**Comment by geemus** [comment]
Hmm. I think it should iterate over all of the values from addrinfo, and try each until one works without error. It should capture errors along the way and then only raise if it runs out of addresses. So I wouldn't expect ipv4/ipv6 to make much of a difference, and would only expect this if both addresses were not working. You can find the code here: https://github.com/excon/excon/blob/master/lib/excon/socket.rb#L103

Were these addresses working from other contexts?

**Comment by NiCkEl5** [comment]
the ipv4 was working and the ipv6 not

**Comment by geemus** [comment]
More specifically, was it working with clients other than excon? Just wondering if there are examples I could look at to see what I might be doing differently.

**Comment by NiCkEl5** [comment]
We didn't test with any other gem, one thing I forgot to mention we are using excon through savon gem

**Comment by geemus** [comment]
Ah, afraid I don't have much experience with savon, though I wouldn't expect anything there to manifest in quite this way it might be possible. Given that it uses httpi, it seems like you could potentially swap clients relatively easily. I'd recommend trying with other stuff if possible to see if that gives you any better luck. I'm not sure how much it would help me pin it down or not, but knowing whether or not I'm unique in failing on this would be helpful.
