### ISSUE TITLE
Body encoding is lost during request

### ISSUE THREAD

**Issue by chrismwendt** [excon/excon#606]
> Excon wraps the `body` of a request with a `StringIO` instance. This allows Excon to [read the body in chunks](https://github.com/excon/excon/blob/master/lib/excon/connection.rb#L166) and send those chunks in the HTTP request. Excon calls `StringIO#binmode` to force binary encoding such that the chunks are not affected by multibyte UTF-8 characters. The problem is that the encoding of the underlying String is also changed by this `binmode` call.

From https://github.com/github/elastomer-client/issues/138

Specifically, the culprit is this `binmode` call: https://github.com/excon/excon/blob/1344c0c4e8fb6ffb26b680867395d693ee57fc07/lib/excon/connection.rb#L156

**Comment by geemus** [comment]
@chrismwendt thanks for the heads up. I suspect a `#dup` would be the probable fix, to ensure we get binmode without modifying the original string? I'm somewhat reticent to do that generally (it's feasible the body string could be quite large, so dup-ing seems potentially dangerous). It may be better to just dup in elastomer, at least if you have a better sense of the size of body you are dealing with to understand the relative safety. Does that make sense? Thoughts?

**Comment by chrismwendt** [comment]
Could excon remember the encoding and set it back to the original after the request? That would avoid duplicating the string.

**Comment by geemus** [comment]
Fair point. I seem to recall some difficulty in getting strings to report their encodings for this purpose across ruby versions, but I could misremember. Would you be interested in working on that to help us out? Thanks!

**Comment by mltsy** [comment]
I just got an error `Encoding::UndefinedConversionError` for a character in a request body (`\xE2`) that I believe is related to this, when trying to use the request body in JSON output.  Could Excon get the character encoding from the content-type header (e.g. from `charset=utf8` if present), and if not present then assume it's `utf8`?  I suppose if this work has already been done, it would make sense to just pull it from the string.  What versions of Ruby are you trying to support?

**Comment by geemus** [comment]
We have historically tried to support everything back through 1.8. I know at some point we will need/want to only do much newer stuff, but that is where we are today (which has a lot to do with why we were not able to find a good working solution as it changed across versions a good deal). We could drop support for older versions, but might want to accompany that with a major release to clearly communicate the breaking change.

**Comment by mltsy** [comment]
Ahh!  Yeah, I agree.  Might be worth starting a 1.0 milestone, just to file some of these issues under?  (And also add any other MVP features or fixes you'd deem desirable for a 1.0 release? Or at least take stock of any potential breaking changes in the current issue list)

**Comment by geemus** [comment]
Sounds good. I setup such a milestone a while back, probably missing some things but here it is: https://github.com/excon/excon/milestone/1

**Comment by mltsy** [comment]
Woah.  AAahhh, that doesn't look so baaad :wink:

I bet some of those things might not even be requirements for 1.0.  (Like as long as they're non-breaking changes, they could be added in 1.1, for instance).  But yeah, a lot of them do seem to be breaking changes or important features :)

What would be great is if there were a pre-1.0 version number that could indicate a breaking change so you wouldn't have to release 1.0 just to indicate that... but... well actually, I suppose there's always `1.0.0-alpha.1` :smile: That could be a nice way to start incorporating some of these features into releases, while indicating that future 1.0 releases may not be compatible with the current release!

**Comment by mltsy** [comment]
Actually, you could even use `1.0.0-alpha.0.1` so that you have the ability to indicate breaking changes within the alpha/rc releases.

**Comment by geemus** [comment]
True. I've been reticent to get into a state where I have to (potentially) maintain both mainline and rc releases until I feel like I'm really ready to march toward 1.0. Should definitely bite the bullet at some point though...

**Comment by jfiorato** [comment]
This appears to be an issue introduced in Ruby 2.3.1. According to the source of ruby versions 1.8.6 up until 2.3.0, `StringIO#binmode` was just a stub, and only ever returned the unaltered `StringIO` object.

https://github.com/excon/excon/issues/668

**Comment by geemus** [comment]
closed by #669
