### ISSUE TITLE
HTTP/1.0 and HTTP/0.9 support..

### ISSUE THREAD

**Issue by decal** [excon/excon#612]
I saw this gem described as "Usable, fast, simple Ruby HTTP 1.1" in the documentation at [File: README -- Documentation for excon (0.54.0)](http://www.rubydoc.info/gems/excon/0.54.0) That being said, would you consider accepting my commits if I forked the repository and added support for `HTTP/1.0` and `HTTP/0.9`? I'd also like to make the action line in the HTTP request more flexible in general, cause I'd like to use an invalid HTTP version as a means to perform functional testing. Thoughts?

**Comment by geemus** [comment]
Maybe, certainly happy to discuss. Are there changes beyond the request line needed? I forget the specific differences, so having some idea of the scope would be helpful. Thanks!

**Comment by sandstrom** [comment]
Wouldn't it make more sense to spend time on http/2 (if http version support should be extended)

**Comment by geemus** [comment]
@sandstrom probably, I would be more interested in that direction personally anyway.
