### ISSUE TITLE
Mitm vulnerability

### ISSUE THREAD

**Issue by abarriga** [excon/excon#618]
Please take a look of this:

https://www.sourceclear.com/registry/security/man-in-the-middle-mitm-/ruby/sid-3363/fix

**Comment by geemus** [comment]
Thanks for the heads up. I've now released v0.55.0 with the fixes, which I think should resolve this?

**Comment by abarriga** [comment]
Wow, fixed so fast! Iit's ok in the new version, closeing the issue. Thanks

**Comment by geemus** [comment]
Sure thing, I considered pushing a release right after the patch, but just got distracted/forgot...
