### ISSUE TITLE
DNS issues when making a connection

### ISSUE THREAD

**Issue by chanks** [excon/excon#619]
Sorry for the generic issue title, but I'm kind of new to DNS and I'm not sure how to describe this better. The fundamental problem is that trying to retrieve the URL `https://blog.fortrabbit.com/mastering-http-caching` via `Excon.get()` returns a 404 with an error page complaining about an invalid domain, though that page is accessible (with the appropriate content) via Chrome, curl, RestClient (which is based on Net::HTTP), Faraday using its Net::HTTP adapter, etc.

Currently when I use `dig` to inspect that domain I'm getting:

```
; <<>> DiG 9.9.5-3ubuntu0.10-Ubuntu <<>> blog.fortrabbit.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 46343
;; flags: qr rd ra; QUERY: 1, ANSWER: 5, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4000
;; QUESTION SECTION:
;blog.fortrabbit.com.		IN	A

;; ANSWER SECTION:
blog.fortrabbit.com.	493	IN	CNAME	blog-frbit.frb.io.
blog-frbit.frb.io.	193	IN	CNAME	blog-frbit.eu2.frbit.net.
blog-frbit.eu2.frbit.net. 19	IN	CNAME	lb-eu2-0003ux-1980802718.eu-west-1.elb.amazonaws.com.
lb-eu2-0003ux-1980802718.eu-west-1.elb.amazonaws.com. 59 IN A 52.208.9.28
lb-eu2-0003ux-1980802718.eu-west-1.elb.amazonaws.com. 59 IN A 34.250.216.234

;; Query time: 540 msec
;; SERVER: 127.0.1.1#53(127.0.1.1)
;; WHEN: Mon Feb 27 14:32:22 EST 2017
;; MSG SIZE  rcvd: 212
```

I was stepping through Excon's logic and saw that it was handling the DNS info on its own, and I wonder if it's handling the above A records correctly?

Edit: This is on the newest version, 0.55.0, by the way.

**Comment by koenrh** [comment]
I don't think this has anything to do with Excon or DNS. It looks like a bug in the service (that is behind Amazon's ELB) that maps host names to apps. Notice how the difference in responses when you leave out the port number from the `Host` request header:

```bash
$ curl -I -H 'Host: blog.fortrabbit.com:443' https://blog.fortrabbit.com/mastering-http-caching

HTTP/1.1 404 Not Found
Content-Type: text/html; charset=utf-8
```

```
$ curl -I -H 'Host: blog.fortrabbit.com' https://blog.fortrabbit.com/mastering-http-caching

HTTP/1.1 200 OK
Date: Mon, 27 Feb 2017 20:47:34 GMT
Server: Apache 2.x
Cache-Control: no-cache
Content-Type: text/html; charset=UTF-8
```

Excon includes the port number in the `Host` request header, which, according to the [relevant RFC](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.23), is perfectly valid.

**Comment by geemus** [comment]
@koenrh great catch, that is super helpful.

@chanks You can actually opt-out of the port with `omit_default_port: true`, which sounds like it might fix things for you. That may be the best bet for the moment (we have long discussed making port omission the default, but are waiting for a major release just in case). In any event, please let us know how it works out so we can close this or help further as necessary.

**Comment by chanks** [comment]
@geemus That solved my issue! Thanks so much to you and @koenrh for the quick diagnosis.
