### ISSUE TITLE
Excon::Error::Socket: end of file reached (EOFError)

### ISSUE THREAD

**Issue by angelacode** [excon/excon#620]
I am using a ruby gem called `neography` which appears to use `excon` as the http client.

When I am using the neography client from irb, I almost always get this error the first time I hit the API to a hosted Graphene DB.

```
@neo.get_node_properties(node2).keys
Excon::Error::Socket: end of file reached (EOFError)
```

Is this an issue with the grapheneDB or is there a way I can avoid always hitting this error?

**Comment by geemus** [comment]
It may be that the response from the server itself is malformed. I would only expect this sort of error if excon was trying to finish reading the request and it unexpectedly ended, which should only occur if the response misreported how much data it contained in some way.
