### ISSUE TITLE
Inaccurate excon.response time 

### ISSUE THREAD

**Issue by alan** [excon/excon#621]
I've been looking at why the time reported by a client using excon (request + response events) is significantly different from the log times of the server. I think I've tracked it down to the way that the excon middleware stack is ordered.

The way the middleware stack is setup means it only measures the `mock` and the actual `request_call` or `response_call` methods on the `connection.rb` file are measured. This is the output from inspecting the stack:

```text
#<Excon::Middleware::ResponseParser:0x007fd849a64d10
 @stack=
  #<Excon::Middleware::Expects:0x007fd849a64d88
   @stack=
    #<Excon::Middleware::Idempotent:0x007fd849a64db0
     @stack=
      #<Excon::Middleware::Instrumentor:0x007fd849a64dd8
       @stack=
        #<Excon::Middleware::Mock:0x007fd849a64e00
         @stack=
          #<Excon::Connection:7fd849a66fe8 @data=[...]>>>>>>
```

The issue is that the `ResponseParser` middleware seems to be reading the actual response from the server, so by the time it goes through to the connection code `response_call` timing is almost 0ms.

I've timed each middleware separately and the `ResponseParser` time matches the difference between the excon instrumentation and the actual time taken. I haven't looked at the `ResponseParser` to understand why it seems to read the response.

I see 2 potential solutions to this, one is to move the instrumentation out of the middleware and instrumenting explicitly when calling the stack in the `connection.rb` class, and the other solution would be to reorder the middleware so that the `Instrumentor` is always called as the first thing.

My personal preference would be the first option as it avoids mistakes when setting up a different middleware stacks per connection.

**Comment by alan** [comment]
This is the workaround I've put in place: https://github.com/ministryofjustice/prison-visits-2/pull/802/commits/ffc49b3b09c8fd741d43f99eaf6f79f340c75b58

With this in place I now the timings reported between the client and the server make sense.

An issue I found when implemented the workaround was that the `Instrumentor` expects to have the response for the instrumentation event, but when the instrumentation is the first middleware the response is nil and causes a nil error in `ActiveSupport::Notifications`

**Comment by geemus** [comment]
Thanks for the detailed report, and I'm glad you have a workaround. I don't have the bandwidth to try and fix this more properly/directly at the moment, but hope to revisit in the not too distant future.

**Comment by delner** [comment]
+1 to this issue. I'd like to measure the start time, finish time, and total response time of a request using this built-in instrumentation for [Datadog tracing](https://github.com/DataDog/dd-trace-rb/pull/211) but the lack of this currently makes it implausible.

**Comment by geemus** [comment]
I think moving it first makes good sense (though it does break since it currently expects the response to be available). I'm reticent to stop including the response datum for those that might expect it though, which makes it difficult for me to change the included instrumentor to fix this at present. Implementing a custom one is probably a good solution for the time being if you need this. I suspect I may eventually provide a new (probably at least initially opt-in) version of instrumentor with this and maybe some other breaking changes, but it is not likely to occur particularly soon.
