### ISSUE TITLE
client_cert_data is not a valid connection key

### ISSUE THREAD

**Issue by llimllib** [excon/excon#626]
Your documentation recommends using client_cert_data:

```
connection = Excon.new('https://example.com',
                       client_cert_data: client_cert_data,
                       client_key_data: client_key_data)
```

But if you do so, you get a warning from https://github.com/excon/excon/blob/master/lib/excon/connection.rb#L373 because neither `client_cert_data` nor `client_key_data` are in `VALID_CONNECTION_KEYS`: https://github.com/excon/excon/blob/master/lib/excon/constants.rb#L64

* It _seems_ that nothing will be affected by this, as the invalid keys aren't dropped. Is that correct?
* Would you like me to PR an update to `VALID_CONNECTION_KEYS` that adds `client_cert_data` and `client_key_data`?

edit:

Those keys do appear to be used here: https://github.com/excon/excon/blob/master/lib/excon/ssl_socket.rb#L68

**Comment by geemus** [comment]
Hello, thanks for the details and question.

* Yes, I believe that is just a warning and things should still be used.
* It seems likely that these keys NOT being included was simply an oversite, a PR to add them sounds great.
