### ISSUE TITLE
No way to access response headers during streaming

### ISSUE THREAD

**Issue by m-o-e** [excon/excon#628]
```
Excon.get(url, :response_block => lambda { |c,r,t| 
   puts "How do we get the response headers here?"
})
```

It seems the response object only becomes available _after_
streaming is finished. This is too late when the stream-processing
depends on the header values (e.g. `Content-type`).

The headers must be made available before the first
invocation of `:response_block` and must be accessible
from inside the block.

**Comment by geemus** [comment]
Sorry for the delay in response, I've been on a trip for the last week.

Could you detail your use case for me a bit more? I understand technically what you are suggesting, but I think a bit more context might help me understand how we might best approach this. Thanks!

**Comment by m-o-e** [comment]
Sorry for the delay on my end as well, been caught up with other things.

My use-case was a streaming proxy (now implemented using Typhoeus):

1. Receive HTTP request from client 
1. Begin upstream HTTP request
1. [Stream](http://roda.jeremyevans.net/rdoc/classes/Roda/RodaPlugins/Streaming.html) response to client

I couldn't find a way to implement this with excon (at least not using the public API surface)
because, as describe above, the response HTTP headers only become available after
streaming is finished.

**Comment by geemus** [comment]
Thanks for the clarification. I would confirm that this is not presently available. It could be added, but it would take some core changes. Roughly, I could imagine something like:

1. Add `:response_headers_block` or something similar, which receives `[header-key, header-value]` as they are parsed.
2. (probably) add `:response_body_block` as alias to `:response_block` to be more explicit.
3. (maybe) deprecate and eventually remove `:response_block` to streamline.

Does that sound like it would accommodate what you need? I doubt I'll get to it soon (especially as it sounds like you found another solution), but it would be great to have a plan outlined for when I am able to revisit. Thanks!

**Comment by m-o-e** [comment]
Yep, that's almost exactly the Typhoeus API.

For reference:

```
              tr = Typhoeus::Request.new( ... )
              tr.on_headers do |th|
                 ...
              end
              tr.on_body do |tb|
                 ...
              end
```

And `on_headers` is guaranteed to fire before
the first invocation of `on_body`.

I agree it's probably a rare use-case and not an urgent item.
Would be nice to see it added at some point in the future, whenever you get around to it. :+1:

**Comment by geemus** [comment]
@m-o-e cool, thanks for taking the time to clarify and discuss. Hopefully I'll get a chance to look at it for the sake of completeness (and I can certainly imagine cases where it would be useful). I just have many things to juggle and haven't heard this request often enough to prioritize it just yet. Thanks!

**Comment by semaperepelitsa** [comment]
I was also trying this in Excon with no luck. I ended up using Net::HTTP instead (using request_get & read_body).

```ruby
http = Net::HTTP.new(host, 80)
http.start do
  http.request_get(url, headers) do |res|
    p res.content_type
    p res["x-some-header"]
    File.open("#{target_path}.part", "wb") do |f|
      res.read_body do |chunk|
        f.write(chunk)
      end
    end
    File.rename("#{target_path}.part", target_path)
  end
end
```

**Comment by geemus** [comment]
@semaperepelitsa thanks for the detailed report.

We would have to make a new interface to allow for this, and haven't really seen a lot of people asking for it so far. For now I would tend to recommend just using Net::HTTP for this case, as shown above, especially since it seems like a fairly exceptional case in terms of usage. If I'm missing something and you think this is something that could or should be used more regularly, I'm certainly open to discussing the possibility of adding an interface like this in the future.

**Comment by kke** [comment]
I see at least two pretty "regular" use-cases:

1. To determine the response content-type
2. To determine if the request was a success or not. The response_block, I believe, is also called when the response is an error.

**Comment by geemus** [comment]
@kke good callouts, thanks for sharing these. Are you running into this problem now?

**Comment by kke** [comment]
Yes, in the referenced issue. I think something like `error_proc:` might solve that without breaking backwards compatibility. A breaking change could yield something more than just the chunk and sizes to the `response_block`.

**Comment by geemus** [comment]
Oops, sorry. I saw the comment, but missed the link. Could you tell me a bit more about what you had in mind for `error_proc`? ie what would be defined as an error or not? What would be passed to the corresponding block? A sketch of it would be handy, maybe a fake readme, so to speak, of what you think it might look like and an example or two?

**Comment by kke** [comment]
Like the regular requests, it would respect the expected status codes and raise if the response is not one of those instead of calling the response block like it does now. I can't think why something would render a stream and return a non-ok status, but maybe someone can.

**Comment by alecernas** [comment]
hello, did it make it to any newest version?

**Comment by geemus** [comment]
@alecernas unfortunately no, we've had some discussions, but never settled on a clear design or implementation.

**Comment by alecernas** [comment]
Thanks for your reply :)
