### ISSUE TITLE
Close socket on Excon::Error::Socket

### ISSUE THREAD

**Issue by stereobooster** [excon/excon#632]
## Why?
Unicorn has nice feature [`check_client_connection`](https://github.com/defunkt/unicorn/commit/5c700fc2cf398848ddcf71a2aa3f0f2a6563e87b) which will prevent unicorn from processing request if client already disconected, but unicorn will not know that client disconected if you do not close socket.

**UPD**
Tried to implement it, but can not close socket. Maybe connected to https://www.ruby-forum.com/topic/201994

**Comment by geemus** [comment]
I saw your comment on timeouts, are there other things that you think should close the connection as well? I think we just didn't before as an oversight, so we could certainly try to fix it. I don't think the issue you mention should be a problem per se, there can be some delay between closing and it going away at OS, but it sounds like this is intentional (and likely would be better than not closing at all). What do you think?

**Comment by stereobooster** [comment]
The problem is: I have ruby client (excon) and ruby server (unicorn). If I set timeout at client level, client script finishes fast, but requests still executed in unicorn. I added closes connection, but unicorn still executes requests. It can happen that ruby just detach itself from socket and not closing it. Still looking into it. Will try to craft test script. Maybe you will spot what I'm doing wrong.

**Comment by geemus** [comment]
Sounds good, not sure I will have any more luck than you, but hopefully we'll at least be on the same page. Thanks!

**Comment by stereobooster** [comment]
@geemus example https://github.com/stereobooster/ruby-server-experiment/tree/master/unicorn-excon

**Comment by stereobooster** [comment]
Update: this code is not testable on MacOS. Searching for solution. Maybe will try on linux. One of the reasons that MacOS doesn't provide `TCP_Info`. But why? BSD and Linux have it. Writing to socket early (to detect dropped client) seems doesn't work either.

**Comment by starbelly** [comment]
@stereobooster  If you look at the spec folder, you'll see where unicorn is used.... yes this still isn't complete, been MIA (i.e., too busy).

**Comment by starbelly** [comment]
spec/excon/test/server_spec.rb 

10   context 'when the web server is unicorn' do
 11     context 'bound to a tcp socket' do
 12       it_should_behave_like "a excon test server", :unicorn, 'streaming.ru'
 13     end

**Comment by stereobooster** [comment]
I was able to test on linux. And yes excon closes socket on timeout, so no bug. It's just I'm not sure where closing of socket happens.

**Comment by geemus** [comment]
@stereobooster k, thanks for the update.
