### ISSUE TITLE
Headers hash causes error

### ISSUE THREAD

**Issue by mahemoff** [excon/excon#633]
I found a URL that keeps returning 403 if headers hash is provided. I even found this happens when it's empty. It seems there's a side effect of specifying headers this way.

I'm wondering how an empty `headers` hash could affect the result here:

```
url = 'http://www.jamiepiperato.com/wp-content/uploads/powerpress/A_PODCAST_HOSTED_BY_JAMIE_PIPERATO.jpg'
Excon.get(url).status # 200
Excon.get(url, headers: {}).status # 403
```

**Comment by geemus** [comment]
I dug into this with `EXCON_DEBUG` and there is one key difference between the two. Excon normally adds some default headers (in the first case), notably a `User-Agent` value. It is set up to presume that these defaults could be replaced though, so the empty hash there actually ends up NOT sending `User-Agent` at all, which (in so far as I can tell) is the cause of the 403. If you add an explicit `User-Agent` value back in you will probably have better luck, but let me know if you still have questions or concerns.
