### ISSUE TITLE
Test suite does not play well with an already-set `http_proxy` env var

### ISSUE THREAD

**Issue by mpalmer** [excon/excon#642]
While running the test suite with `rake tests`, I noticed a bunch of spurious failures relating to an IP address not being correct, for example:

    + !!(response.headers['Server'] =~ /^WEBrick/)
            response.headers['Custom'] + returns "Foo: bar"
            response.remote_ip - returns "127.0.0.1"
              expected => "127.0.0.1"
              returned => "192.168.121.1"
            Action? [c,q,r,?]?

I recognise that IP as the one which is set in my `http_proxy` env var.  Sure enough, unsetting the proxy (`http_proxy= rake tests`) works, whilst setting a different (non-existent) address results in failure:

    $ http_proxy=http://192.0.2.42:3128/ rake tests
  
      Excon thread safety
        thread_safe_sockets configuration
          thread_safe_sockets default + returns true
          with thread_safe_sockets set false + returns false
    - long_thread
        connect_write timeout reached (Excon::Error::Timeout)
          /XXX/forks/excon/git/lib/excon/socket.rb:267:in `select_with_timeout'
          /XXX/forks/excon/git/lib/excon/socket.rb:131:in `rescue in block in connect'
          /XXX/forks/excon/git/lib/excon/socket.rb:112:in `block in connect'
          /XXX/forks/excon/git/lib/excon/socket.rb:103:in `each'
          /XXX/forks/excon/git/lib/excon/socket.rb:103:in `connect'
          /XXX/forks/excon/git/lib/excon/socket.rb:29:in `initialize'
          /XXX/forks/excon/git/lib/excon/connection.rb:406:in `new'
          /XXX/forks/excon/git/lib/excon/connection.rb:406:in `socket'
          /XXX/forks/excon/git/lib/excon/connection.rb:101:in `request_call'
          /XXX/forks/excon/git/lib/excon/middlewares/mock.rb:48:in `request_call'
          /XXX/forks/excon/git/lib/excon/middlewares/instrumentor.rb:26:in `request_call'
          /XXX/forks/excon/git/lib/excon/middlewares/base.rb:16:in `request_call'
          /XXX/forks/excon/git/lib/excon/middlewares/base.rb:16:in `request_call'
          /XXX/forks/excon/git/lib/excon/middlewares/base.rb:16:in `request_call'
          /XXX/forks/excon/git/lib/excon/connection.rb:250:in `request'
          tests/thread_safety_tests.rb:19:in `block (3 levels) in <top (required)>'
        Action? [c,q,r,?]? 

Presumably the test suite (or even the `Rakefile`) could just unset `ENV['http_proxy']` before running, but perhaps there's a more idiomatic way of achieving a similar result.

**Comment by geemus** [comment]
Hey, thanks for the detailed report. I don't happen to use proxies much in my setup, so probably just coincidental that I hadn't stumbled across this. I imagine unsetting in test helper would make the most sense (that way it would work whether you ran tests specifically/directly or through Rake). If you have capacity to throw together a PR that would be great, otherwise I'll try to get back to it in the not too distant future.

**Comment by mpalmer** [comment]
PR sent.  Turns out there's already some support for env var munging, and most parts of the test suite are using it; just one commonly used test fragment didn't have it.  Added that one line and *poof*! everything's fine.

You can verify the fix by running `http_proxy=http://192.0.2.42:3128/ rake tests` before and after; before, it'll error out with a timeout or connrefused (depending on your firewalling), after it'll be blissfully unaware of any issues.

**Comment by geemus** [comment]
Sounds good, thanks!
