### ISSUE TITLE
debug_request and debug_response don't appear to be working

### ISSUE THREAD

**Issue by djberg96** [excon/excon#645]
excon 0.59
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]

Either I'm missing something obvious, or `:debug_response` and `:debug_request` aren't working:

```
require 'excon'
connection = Excon.new('http://www.google.com', :debug_request => true, :debug_response => true)

# No output
response = connection.get
```

However, if I set `ENV['EXCON_DEBUG'] = "true"` then I get debug output.

What have I missed?

On a semi-related note, how would I log to a Logger instance?

**Comment by geemus** [comment]
Hey, great question. `EXCON_DEBUG` sets `debug_response` and `debug_request`, but also sets the instrumentor (this is the key part you are missing). You can see where that all happens here: https://github.com/excon/excon/blob/3e2c79353cb6c0e3992e68bdd354c83b63f44777/lib/excon/connection.rb#L71

It is very possible that the docs are not up to date enough to make that clear though, in which case I'd certainly welcome PRs and/or feedback on how we can make that clearer.

As you might gather, it is the instrumentor that is actually outputting things. The standard instrumentor shows an example of how this works (and is what `EXCON_DEBUG` uses). You should be able to learn more in the docs here: https://github.com/excon/excon#instrumentation. And then you could write a new instrumentor to use that outputted to logger as you desire. For reference, the implementation of the standard instrumentor is here: https://github.com/excon/excon/blob/master/lib/excon/standard_instrumentor.rb

Hope that helps, but do let me know if I can further clarify or assist. Thanks!

**Comment by djberg96** [comment]
@geemus Ok, it looks like just `:debug` behaves as expected. The README sort of suggests otherwise with this:

```
# Output debug info, similar to ENV['EXCON_DEBUG']
connection = Excon.new('http://geemus.com/', :debug_request => true, :debug_response => true)
```
And I'm still not sure what the significance of those options are.

Regarding the instrumentation, I think I see how it works now thanks, but it feels heavy handed. I just want to pass a Logger object to a `:log` option and watch the requests and/or responses get logged to it. Any sort of filtering would be on the logger object already.

Consider it a feature request. :)

**Comment by geemus** [comment]
Thanks for the update. To clarify those options, they dictate what will appear (or not) in the text of the error that is raised. See:

https://github.com/excon/excon/blob/d3aeb66834f2081dc77cb3181a66fd088376e86a/lib/excon/error.rb#L169-L177

So you could rescue and put the error message to log potentially to see that info.

Instrumentor can feel a bit heavy handed, for sure. I'll keep the log possibility in mind.

Maybe we should just change that part of readme to use `:debug` then? That does seem like it would be clearer. Would you be up for a quick PR? Adding some info on what debug request/response do also would be bonus.

Thanks!
