### ISSUE TITLE
[RFE] batch requests for pipelining

### ISSUE THREAD

**Issue by djberg96** [excon/excon#646]
In some experiments with pipelining large numbers of requests to Microsoft Azure, I would hit timeout errors if I sent too many simultaneous requests. Setting the timeout value may or may not help because sometimes I don't know exactly how many requests I'll be sending, so I'm not sure what I should set the timeout value to, nor what I would do about it anyway if it does timeout.

For example, to get every offer for every publisher for Azure marketplace images, I create a request for each publisher. But, I don't know in advance how many publishers there are going to be. As it turns out, it's now over 500, and that's too much for most connections. The current code looks something like this:

```
publishers.each do |publisher|
  offer_path = File.join(publisher['id'], 'artifacttypes/vmimage/offers')
  path_requests << {:method => :get, :path => offer_path, :query => query}
end

# Ok, now get all offers for all publishers
responses = connection.requests(path_requests)
```
So, what I end up doing is creating batches of 50 or so requests at a time via `each_slice`, and collect all the responses to a single array, and then proceed from there.

While I can certainly do this manually, I thought it would be nice to have a baked-in way to do this, either by allowing a second (integer) argument to the `requests` method, or by creating a `requests_in_batches` method that defaults to, say, 50 requests at a time by default. So, then my code above would just change to:

```
responses = connection.requests_in_batches(path_requests)       # use default of 50
# responses = connection.requests_in_batches(path_requests, 40) # or, set my own value
```

And it would work with a much lower risk of timing out.

**Comment by geemus** [comment]
Thanks for the detailed request. I can certainly see how that might be helpful as a feature. I'll consider it for future enhancement. Thanks!

**Comment by djberg96** [comment]
@geemus Thanks, I should be able to get a PR soon, perhaps this weekend, and you can review it then. It shouldn't be too complicated.

**Comment by geemus** [comment]
Great, thanks! (was traveling last week, so still playing catchup a bit).
