### ISSUE TITLE
[Question]: How to track response time / duration with instrumentation

### ISSUE THREAD

**Issue by Skarlso** [excon/excon#648]
Hey folks. Could anyone help me out here please? 

I saw that there was an issue saying that this should be now possible with instrumentation. I took a stab at this, but I'm unsure that it is a good solution. It looks like this:

```ruby
require 'excon'

module Whatever
  class SimpleInstrumentor
    class << self
      def instrument(name, params = {}, &block)
        @@start_time ||= params[:start_time]
        statsd ||= Statsd.new
        case name
        when /error/, /retry/
          statsd.increment(name)
          end_time = Time.now - @@start_time
          statsd.count("#{name}-latency", end_time)
        when /response/
          name = name.gsub(/\.response/, '.success')
          statsd.increment(name)
          end_time = Time.now - @@start_time
          statsd.count("#{name}-latency", end_time)
        end
        yield if block_given?
      end
    end
  end
end
```

I'm using statd to track errors retries and successes. I think that part is okay, but I'm also interested in latency tracking. And this is my stab at it.

I'm unsure if the response would be even the same response. ( the one which started the thread. ).

StartTime is coming from the request. Where I'm constructing the request and than sending it. So it's in the `params` section.

**Comment by Skarlso** [comment]
StartTime is coming from the request. Where I'm constructing the request and than sending it. So it's in the `params` section.

**Comment by Skarlso** [comment]
Somebody? Anybody?

**Comment by Skarlso** [comment]
@geemus ?

**Comment by geemus** [comment]
Sorry for the delay, I was traveling last week and now I'm struggling to play catchup.

I would expect that response to be within the same request context, so I think you should be good there. I might suggest adding a `when /request/` block to actually set the start time for the best accuracy. That way it should get set when the request is happening and compared when request is reached. I will note though, that you might potentially want to have that block also reset start_time on retry? Just depends if you want start of attempts to success or just start of final attempt to success for stats.

Does that clarify sufficiently?

**Comment by Skarlso** [comment]
Heey!! Thanks for the reply. :))

I was trying start_time in /request/ but that ended up in oddities when it wasn't set or was inaccurate. So, starting it when I'm constructing the request ended up as being consistent. I'm not sure why though. But meh. :D 

Cool, so I'm on the right direction with this. Awesome. I just thought that there might be something I'm missing, or that this IS in fact how I'm supposed to do it. :)

Thanks!

**Comment by geemus** [comment]
@Skarlso yeah, the other alternative would be to do this directly in a middleware (instead of in an instrumentor which is driven by the instrumentation middleware). You would likely have to duplicate some things though. Part of the inconsistency you are seeing might just be where in the chain the middleware fits (which I hadn't really considered). So starting at the beginning would probably be more consistent as you suggest. Just let me know if you have further questions or concerns, but otherwise I'll consider this closed for now. Thanks!

**Comment by Skarlso** [comment]
Thanks very much!
