### ISSUE TITLE
Host header not being included in the http request by default

### ISSUE THREAD

**Issue by dvrajan** [excon/excon#659]
Hi,

We noticed that Excon is not adding an `Host` header unless explicitly mentioned as below 
```
Excon.post(url,
          :body => body,
          :headers => {"Host" => host})
```

However [RFC7230](https://tools.ietf.org/html/rfc7230#section-5.4) states that
"A client MUST send a Host header field in all HTTP/1.1 request messages."

Is there a reason for Excon not doing this? Otherwise I can contribute for this.

**Comment by geemus** [comment]
Sorry for delays, was AFK over the holidays. Thanks for checking in on this, I'm pretty sure I must have just overlooked this.

It's surprising to me that we never ran into issue with it before, are you seeing errors related to it?

If you'd like to add contribute a fix, that would be great. I think it should be pretty straightforward to do, but just let me know if you have any questions along the way.

Thanks!
wes

**Comment by rafaelss** [comment]
I got this error for the request below:

```
irb(main):003:0> Excon.get("http://viacep.com.br/ws/13970906/json")
Traceback (most recent call last):
       10: from /Users/rafael/.rubies/ruby-2.5.0/bin/irb:11:in `<main>'
        9: from (irb):3
        8: from /Users/rafael/.gem/ruby/2.5.0/gems/excon-0.55.0/lib/excon.rb:239:in `get'
        7: from /Users/rafael/.gem/ruby/2.5.0/gems/excon-0.55.0/lib/excon/connection.rb:252:in `request'
        6: from /Users/rafael/.gem/ruby/2.5.0/gems/excon-0.55.0/lib/excon/connection.rb:388:in `response'
        5: from /Users/rafael/.gem/ruby/2.5.0/gems/excon-0.55.0/lib/excon/middlewares/response_parser.rb:7:in `response_call'
        4: from /Users/rafael/.gem/ruby/2.5.0/gems/excon-0.55.0/lib/excon/response.rb:63:in `parse'
        3: from /Users/rafael/.gem/ruby/2.5.0/gems/excon-0.55.0/lib/excon/socket.rb:46:in `readline'
        2: from <internal:prelude>:74:in `read_nonblock'
        1: from <internal:prelude>:74:in `__read_nonblock'
Excon::Error::Socket (end of file reached (EOFError))
```

**Comment by geemus** [comment]
Hey, I dug a bit deeper here and it looks as though it ought to get set for non-UNIX schemes here: https://github.com/excon/excon/blob/master/lib/excon/connection.rb#L236. It looks like that has been in place for quite some time also.

@rafaelss are you certain the issue is related to a missing Host header or is it something else? You might try calling with `omit_default_port: true`, as this sometimes clears up unexpected things.
