### ISSUE TITLE
Treat Errno::ECONNRESET as connect timeout

### ISSUE THREAD

**Issue by zentetsukenz** [excon/excon#660]
Since remote server just politely send back `RST` packet before dropping the connection. I think we should also handle this error, Errno::ECONNRESET, and wrap it in `Excon::Error` with `connection_reset` message. What do you think?

Add more info. I found this error while ssl_socket is trying to connect to peer here https://github.com/excon/excon/blob/master/lib/excon/ssl_socket.rb#L117

**Comment by geemus** [comment]
That sounds pretty reasonable to me. Would you be up for working on a pull request to add this? Thanks!

**Comment by zentetsukenz** [comment]
@geemus yes, I will open PR as soon as possible

**Comment by geemus** [comment]
Great, no rush, just let me know if I can provide further assistance. Thanks!

**Comment by zentetsukenz** [comment]
@geemus sorry for late reply. After I've been digging into the code, I think Excon had already done its job by wrapping the connection reset error inside `Excon::Error::Socket` class, which I think is already make sense.

Sorry, I miss this error while I debugged on my application side. So, closing the issue.

btw, the tests are super awesome.

**Comment by geemus** [comment]
No problem, thanks for the detailed update. Just let me know if you find out there is more we should do after all. Thanks!
