### ISSUE TITLE
Some odd behavior with trailing slashes when mixed with queries

### ISSUE THREAD

**Issue by djberg96** [excon/excon#662]
I'm working with the Azure REST API, and I'm making a connection like so:

```
resource_url = 'https://management.azure.com/'

# Assume I successfully acquired the token earlier
headers = {
  'Authorization' => "Bearer #{token}",
  'Content-Type'  => 'application/json',
  'Accept'        => 'application/json'
}

options = {
  :persistent       => true,
  :headers          => headers,
  :ssl_verify_peer  => true,
  :ssl_version      => 'TLSv1',
}

connection = Excon.new(resource_url, options)
```
So far, so good. From this point I'm trying to get a list of storage accounts. However, I get different results depending on whether or not the path has a trailing slash:
```
path = "/subscriptions/xxx/providers/Microsoft.Storage/storageAccounts/" # <- here
query = {"api-version" => "2017-10-01"}

response = connection.get(:path => path, :query => query)
raise "Oops: #{response.status}" if response.status > 299 # No error, though

hash = JSON.parse(response.body)
p hash['value'].size # 2 or 195, depending
```
For some reason, the presence of that trailing slash has a significant impact on the number or results returned.

What Azure does for pagination is return a "nextLink" URL which includes something called a skip token. If you want the remaining results, you make more calls using that URL.
```
https://management.azure.com/subscriptions/xxx/providers/Microsoft.Storage/storageAccounts/?api-version=2017-10-01&%24skiptoken=zZZdb4
```
However, when I parse out the path it includes the trailing slash, which is leading to this behavior.
```
uri = Addressable::URI.parse(hash['nextLink'])
p uri.path # "/subscriptions/xxx/providers/Microsoft.Storage/storageAccounts/"
```
At the moment, I'm *manually* chopping out trailing slashes to get it to work right. What I'm wondering is what would cause this, and is there a way to normally the URL's?

**Comment by geemus** [comment]
Hmm. We insert a slash at the beginning if it is missing, but otherwise just pass through paths. 

Theoretically, I didn't think trailing slashes were supposed to be semantically meaningful, but of course theory isn't going to help you here. You may want to report the issue to Azure, if you haven't already, as they may be able to provide more insight (or fix the issue).

I'm afraid I'm not aware, off hand, of a way to do anything other than manually chopping. I'm glad you were able to figure out that was where the discrepancy was coming from at least. Seems pretty bizarre...

**Comment by djberg96** [comment]
Ok, I think this is an issue on the Azure side. Closing.

**Comment by geemus** [comment]
Thanks for the update, if you end up finding out more info that changes your mind about who should be responsible here, just let me know. That said, my interpretation from what I've read here would tend to agree with you. Thanks!
