### ISSUE TITLE
Reuse connection but reconnect on socket errors

### ISSUE THREAD

**Issue by sadovnik** [excon/excon#667]
Hello!

I want to use Excon in persistent connection mode but reconnect every time a socket error happens.

For this purpose, I came up with middleware like this:

```ruby
class Excon::Middlewares::ResetConnectionOnSocketErrors < Excon::Middleware::Base
  def error_call(datum)
    return @stack.error_call(datum) unless valid_reset_case?(datum)

    connection = datum.delete(:connection)
    connection.request(datum)
  end

  private

  def valid_reset_case?(datum)
    datum[:persistent] && datum[:error].is_a?(Excon::Error::Socket)
  end
end
```

1. Is it a proper way of implementing such behaviour?
2. What do you think about adding such behaviour as an option?

**Comment by geemus** [comment]
This seems rather similar to the `idempotent` option, which will retry socket and status errors a limited number of times, see [README#options](https://github.com/excon/excon#options) and [middleware](https://github.com/excon/excon/blob/master/lib/excon/middlewares/idempotent.rb). Is it possible this might already meet your needs?

**Comment by sadovnik** [comment]
@geemus `idempotent` also retries on `Excon::Errors::Timeout` and `Excon::Errors::HTTPStatusError` which is not what I'm looking for. Customising `idempotent` option just feels wrong.

Making an abstract `Retryable` middleware and extend more specific middlewares from it might be a good option.

What do you think?

**Comment by geemus** [comment]
Yeah, that makes sense. From what I understand, your proposed middleware is probably a reasonable way to do it. That said, could you explain in a bit more detail your use case for retrying just socket errors? I think that might help me better advise you. Thanks!
