### ISSUE TITLE
Excon::FORCE_ENC used by Excon::Connection breaks chunked uploads when using frozen strings.

### ISSUE THREAD

**Issue by boof** [excon/excon#670]
Hello,

we encountered an issue using Excon (using fog/openstack) with Ruby 2.5.1 and immutable strings (`# frozen_string_literal: true`).

Excon determines `FORCE_ENC` to be true if String supports `#force_encoding`, but it will modify the string. This only happens when you use chunked uploads because Excon tries to ensure data is binary. Strings are immutable in our app and will be immutable in Ruby 3 (https://bugs.ruby-lang.org/issues/11473) so it'll be nice to support it in a way it doesn't break (eg. check if it's already binary or force encoding unless frozen).

I currently solved this issue by defining `Excon::Connection::FORCE_ENC` over `Excon::FORCE_ENC` `Excon::Connection` doesn't try to force encode the string.

Best Regards

**Comment by geemus** [comment]
@boof - Thanks for the detailed report.

For the fix, do you think it will be sufficient to change the guard to check something like: `if FORCE_ENC && !string.frozen?`?

My concern is that if you are then using multibyte encodings on a frozen string, that other things will break when it's trying to write the request out. I think that in cases where it isn't already binary, we may need to dup and then force encode to ensure it is in the expected format (I'm a bit concerned about the amount of additional memory this may use in some cases, so I'd prefer to not just make it always do this unless it needs to).

Does that all make sense? What do you think?

**Comment by boof** [comment]
First I'd check if the string is maybe binary encoded and state in the documentation that it might make sense to encode the string already in binary before returning them.

Second I'd probably try to force encoding unless the string is frozen.

Last I'd copy code the string and if the mem usage grows to big (we're talking about 1mb chunks by default) I hope the dev notices. It's also possible to simple raise an error hinting the dev in the right direction.

I'm sadly not very familiar with the whole streaming/chunking multibyte strings topic, but I'm sure there are ways to deal with that issue, maybe it even doesn't matter at all. Did you experience any issues chunking multibyte string already?

**Comment by geemus** [comment]
@boof sorry for the delays, have been a bit swamped. ^ that should skip encoding if it's already binary, does that solve the problem for you? I know we could do dup+encode to more generally solve this, but it's also a bit more dangerous in terms of memory use/etc, so I'd prefer to do a more minimal change (especially if it solves the immediate problem) to start. Does that make sense? Just wanted to check in to see if this is sufficient for now or if you would still need the hack you mention. Thanks!

**Comment by boof** [comment]
We removed our hack and latest vanilla excon is now working with binary frozen strings.

**Comment by geemus** [comment]
@boof thanks for the update, glad to hear that fixes it for you.
