### ISSUE TITLE
Problem with authenticating proxy and special characters in password

### ISSUE THREAD

**Issue by djberg96** [excon/excon#678]
I'm having trouble authenticating against a local proxy server I'm running if I put a special character in the password. Here's the server:

```
# proxy_server.rb
require 'webrick'
require 'webrick/httpproxy'
require 'logger'
require 'openssl'
require 'cgi'

cert_name = [ %w[CN localhost] ]
realm     = 'Proxy Realm'
username  = 'admin'
password  = CGI.escape('p@ssxxx123')

digest_file = File.expand_path('../htdigest', __FILE__)

htdigest = WEBrick::HTTPAuth::Htdigest.new(digest_file)
htdigest.set_passwd(realm, username, password)
htdigest.flush

authenticator = WEBrick::HTTPAuth::DigestAuth.new(
  :Realm  => realm,
  :UserDB => htdigest
)

passwd_file = File.expand_path('../htpasswd', __FILE__)

htpasswd = WEBrick::HTTPAuth::Htpasswd.new(passwd_file)
htpasswd.set_passwd(realm, username, password)
htpasswd.flush

authenticator = WEBrick::HTTPAuth::ProxyBasicAuth.new(
  :Realm => 'Proxy Realm',
  :UserDB => htpasswd
)

logger = Logger.new($stderr)
logger.level = Logger::DEBUG

proxy = WEBrick::HTTPProxyServer.new(
  :Port => 8080,
  :Logger => logger,
  :SSLEnable => true,
  :SSLCertName => cert_name,
  :SSLVerifyClient => OpenSSL::SSL::VERIFY_NONE,
  :ProxyAuthProc => authenticator.method(:authenticate).to_proc
)

trap('INT'){ proxy.shutdown }
trap('TERM'){ proxy.shutdown }

proxy.start
```

And here's my simple excon client script:

```
# excon_client.rb
require 'excon'
require 'cgi'

username = 'admin'
password = CGI.escape('p@ssxxx123')
port = 8080
url = 'http://www.google.com'

proxy = "http://#{username}:#{password}@localhost:#{port}"

puts "PROXY: #{proxy}"

# Proxy auth failure
response = Excon.get(url, :proxy => proxy)
p response.body
```

If I change the password to something plain (in both the server and client) then it works fine. I've tried tinkering with setting the username and password separately, but to no avail.

Any ideas?

**Comment by geemus** [comment]
We actually just merged a PR updating the readme that might be relevant: https://github.com/excon/excon/pull/677/files

Basically, you might need to pre-escape your username/password to ensure they get encoded properly. Do let me know if that doesn't solve the issue though and we can try other things.

**Comment by djberg96** [comment]
@geemus I am already escaping the password via CGI.escape.

**Comment by geemus** [comment]
@djberg96 sorry, yes, I overlooked specifics. I think I found the issue, will try to explain:

Excon receives the escaped password, but then unescapes and re-encodes into a header using base64. At this point the proxy would receive the unescaped version of the password. The proxy server code you include above, however, expects that the password would still be escaped. If I leave the client the same, but remove the `CGI.escape` in the proxy server setup, everything seems to work.

Does that make sense? And is that workable? Just let me know if I missed something. Also, fwiw, while working on this I noticed that `Proxy-Authorization` does not get redacted from inspects, which we may want to fix at some point (filed as #679).

Hope that helps, but do let me know if I misunderstand or missed something. Thanks!

**Comment by djberg96** [comment]
Hm, I still can't get it to work. If I remove `CGI.escape` from the server and try to run the excon client code I get a proxy auth error.

**Comment by djberg96** [comment]
Agreed that Proxy-Authorization should be redacted. 👍

**Comment by geemus** [comment]
Glad to hear it worked, thanks for the updates. I consolidated the existing redaction code (it was duplicated across 3 locations before) into utils while investigating this, so hopefully it will be fairly easy to add Proxy-Authorization redaction (and then we'll just want to ensure it's in the tests too). I'd love a PR if you have time, otherwise I will probably return to it at some point, just maybe not soon. Thanks!
