### ISSUE TITLE
Connect timeout does not work when nonblock=false and connection protocol is HTTPS 

### ISSUE THREAD

**Issue by mattheworiordan** [excon/excon#682]
The Faraday adapter for Excon, sets `nonblock` to false always when HTTPS/TLS is used. See https://github.com/lostisland/faraday/blob/master/lib/faraday/adapter/excon.rb#L22-L24.

This is due to issues that were seen with JRuby:

* https://github.com/geemus/excon/issues/106
* https://github.com/jruby/jruby-ossl/issues/19

When `nonblock` is false, Excon appears to consistently ignore the timeouts. See example below with nonblock true on the first run, and false on the second (note that the connection it's making is to a weird ISP endpoint that is not TLS terminated, hence the odd behaviour.  The actual endpoint behaviour though is irrelevant given the timeouts should be honoured).

```
[2] pry(main)> require 'excon'
=> true
[3] pry(main)> conn = Excon.new('https://host.does.not.exist/', :debug_request => true, :debug_response => true, read_timeout: 5, write_timeout: 5, connect_timeout: 3)
=> #<Excon::Connection:7fd87028ab90 @data={:chunk_size=>1048576, :ciphers=>"ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA:!DSS", :connect_timeout=>3, :debug_request=>true, :debug_response=>true, :headers=>{"User-Agent"=>"excon/0.62.0"}, :idempotent=>false, :instrumentor_name=>"excon", :middlewares=>[Excon::Middleware::ResponseParser, Excon::Middleware::Expects, Excon::Middleware::Idempotent, Excon::Middleware::Instrumentor, Excon::Middleware::Mock], :mock=>false, :nonblock=>true, :omit_default_port=>false, :persistent=>false, :read_timeout=>5, :retry_limit=>4, :ssl_verify_peer=>true, :ssl_uri_schemes=>["https"], :stubs=>:global, :tcp_nodelay=>false, :thread_safe_sockets=>true, :uri_parser=>URI, :versions=>"excon/0.62.0 (x86_64-darwin17) ruby/2.4.4", :write_timeout=>5, :host=>"host.does.not.exist", :hostname=>"host.does.not.exist", :path=>"/", :port=>443, :query=>nil, :scheme=>"https"} @socket_key="https://host.does.not.exist:443" @_excon_sockets={70283780429680=>{}}>
[4] pry(main)> require 'benchmark'
=> true

[6] pry(main)> puts Benchmark.measure { begin; conn.post; rescue => e; puts e.inspect; end }
#<Excon::Error::Timeout: connect_write timeout reached>
  0.000000   0.000000   0.000000 (  3.021948)

[7] pry(main)> conn = Excon.new('https://host.does.not.exist/', :debug_request => true, :debug_response => true, read_timeout: 5, write_timeout: 5, connect_timeout: 3, nonblock: false)
=> #<Excon::Connection:7fd870669090 @data={:chunk_size=>1048576, :ciphers=>"ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA:!DSS", :connect_timeout=>3, :debug_request=>true, :debug_response=>true, :headers=>{"User-Agent"=>"excon/0.62.0"}, :idempotent=>false, :instrumentor_name=>"excon", :middlewares=>[Excon::Middleware::ResponseParser, Excon::Middleware::Expects, Excon::Middleware::Idempotent, Excon::Middleware::Instrumentor, Excon::Middleware::Mock], :mock=>false, :nonblock=>false, :omit_default_port=>false, :persistent=>false, :read_timeout=>5, :retry_limit=>4, :ssl_verify_peer=>true, :ssl_uri_schemes=>["https"], :stubs=>:global, :tcp_nodelay=>false, :thread_safe_sockets=>true, :uri_parser=>URI, :versions=>"excon/0.62.0 (x86_64-darwin17) ruby/2.4.4", :write_timeout=>5, :host=>"host.does.not.exist", :hostname=>"host.does.not.exist", :path=>"/", :port=>443, :query=>nil, :scheme=>"https"} @socket_key="https://host.does.not.exist:443" @_excon_sockets={70283780429680=>{}}>

[8] pry(main)> puts Benchmark.measure { begin; conn.post; rescue => e; puts e.inspect; end }
#<Excon::Error::Socket: Operation timed out - connect(2) for 92.242.132.24:443 (Errno::ETIMEDOUT)>
  0.000000   0.000000   0.000000 ( 75.583855)
```

The nonblock true code raise an exception in 3s as expected, nonblock false raises an exception in 75s.

Version info:

```
$ ruby -v
ruby 2.4.4p296 (2018-03-28 revision 63013) [x86_64-darwin17]

$ gem list | grep excon
excon (0.62.0)
```

**Comment by geemus** [comment]
Hmm. I guess we have tests around ensuring read times out (https://github.com/excon/excon/blob/master/tests/timeout_tests.rb), but apparently not connect. I suspect since nonblock is the default, block doesn't get exercised as much.

The handling of things looks somewhat similar though, so I'm not totally certain where things are falling through the cracks. We could potentially try to use Timeout.timeout more liberally, instead of just relying on raised errors. But I've seen/heard many cautionary tales about it behaving unexpectedly.

Do you have thoughts on explicitly fixing this, or do you think working around it (as per the linked issues), is the better solution for now? Thanks!

**Comment by mattheworiordan** [comment]
>  We could potentially try to use Timeout.timeout more liberally, instead of just relying on raised errors. But I've seen/heard many cautionary tales about it behaving unexpectedly.

Well we use Timeout, but cautiously indeed.  It's not evil, it's just something you need to understand deeply to use reliably.

> Do you have thoughts on explicitly fixing this, or do you think working around it (as per the linked issues), is the better solution for now? Thanks!

My concern with the workaround is that in Java environments, it too will have unexpected side effects.  I will probably detect the JRuby envs and not set that option, but it feels quite hacky and brittle.

Thanks for your reply.

**Comment by geemus** [comment]
Yeah, I know that I do not understand timeout well enough to feel confident getting it to reliable. Agreed that the jruby switching also feels weird, but perhaps it is reasonable if it is easy and reliable.

**Comment by mattheworiordan** [comment]
Well mr stale bot, I am afraid this issue is still an issue.

**Comment by geemus** [comment]
@mattheworiordan thanks for clarifying and keeping this alive. What should our next step be? Would you want to work on getting a version of your workaround in as a patch?
