### ISSUE TITLE
Docs formatting is broken

### ISSUE THREAD

**Issue by kke** [excon/excon#698]
There are multiple occurences of something like this:

![image](https://user-images.githubusercontent.com/224971/57525958-cf01b500-7334-11e9-8984-e40a1ac1c5bc.png)

![image](https://user-images.githubusercontent.com/224971/57526096-1be58b80-7335-11e9-919d-41a068fb1a99.png)

I believe this is because of the indentation:

https://github.com/excon/excon/blob/master/lib/excon.rb#L115-L118

I think it needs to be `# @param`, not `#    @param`.

**Comment by geemus** [comment]
Thanks for the heads up. Where are you viewing rendered docs? (want to make sure we are looking at the same thing). Also, would you be interested in helping us fix this? Thanks!

**Comment by kke** [comment]
https://www.rubydoc.info/github/excon/excon

Also seems to happen if you run yardoc locally.

Confirmed the indentation to be the culprit.

Going to make a PR.

**Comment by geemus** [comment]
Thanks for confirming/clarifying. I figured it was probably something like that, but didn't want to assume incorrectly. I'm way too close to the implementation, so I rarely look at the docs (or just look in the code), so I was totally unaware of the formatting issue. Glad to see it fixed!
