### ISSUE TITLE
Allow specify socket remote host indepedent of SNI hostname

### ISSUE THREAD

**Issue by allenwu1973** [excon/excon#701]
Hi,

Thanks for this great project.
I'm trying to implement a SSRF filter middleware for excon, but I find it's quite hard to implement with the middleware interface, without patching excon's object.

I think there's two way a SSRF filter could be implemented
* Obtain the IP after the socket is initialized, before the request is sent.
* Resolve IP first, check the IP, and connect to the resolved IP

There's no hook for the first case.
In the second case, I can't set openssl's socket (SNI) hostname independent from the underlying socket hostname.

Could you add a hook or a datum to allow alter the parameters that is used to create the tcp socket? Thanks!

**Comment by geemus** [comment]
I'm not particularly familiar with SSRF filtering techniques, so help get me up to speed. Taking a step back from implementation specifics, what would the overall flow look like and where would you need to do something (and what would that thing be)? I think that level of detail will help a lot in terms of me being able to think through solutions. Thanks!

**Comment by allenwu1973** [comment]
Thank you for your reply.

To protect from SSRF, genereally means to ensure
* The URL the user provided isn't pointing to localhost or internal network
* "Time of check to time of use" attack isn't possible.
  (eg. When you resolve the domain, it's pointing to a external IP, but when the socket is created, it's pointing to 127.0.0.1)

So I think the flow would be:

1. Excon calls the middleware before creating the socket
2. the middleware resolves the hostname to IP
3. the middleware checks the resolved IP
4. if 3 pass, the middleware ask Excon to connect to the resolved IP,
   (rather than using the user given hostname and resolve the second time)
   
If I understood correctly,
this flow is currentlly possible by chaning datum[:hostname] in middleware, but SNI will be wrong.

**Comment by geemus** [comment]
I wonder if we should think about just making this a built in feature (with an option that can be used to disable, but perhaps it should be on by default). What do you think?

If I understand correctly, the key difference is really step 3 (checking the resolved IP) to ensure it doesn't resolve to localhost or internal. I think though, that it should allow localhost or internal if that was explicitly specified? So we would just want to raise an error if resolution resulted in a localhost or internal address AND this does not match the originally specified value?

I ask as there are probably some test/development use cases where localhost might actually be intended that I wouldn't want to rule out altogether. Does that make sense?

**Comment by allenwu1973** [comment]
> I wonder if we should think about just making this a built in feature (with an option that can be used to disable, but perhaps it should be on by default). What do you think?

That would be very nice!

> If I understand correctly, the key difference is really step 3 (checking the resolved IP) to ensure it doesn't resolve to localhost or internal. I think though, that it should allow localhost or internal if that was explicitly specified? So we would just want to raise an error if resolution resulted in a localhost or internal address AND this does not match the originally specified value?

Yes, exactly.
Another way is to let user specify a lambda, and let user decide which IP to allow.

> I ask as there are probably some test/development use cases where localhost might actually be intended that I wouldn't want to rule out altogether. Does that make sense?

Makes sense.
I think this feature is only interesting for people who let untrusted user specify which url to connect, 
so make it opt-out instead of opt-in is also OK. 

Thanks!

**Comment by geemus** [comment]
Taking a step back, I was thinking maybe we should start with something in the datum (which is likely to be interesting/useful regardless). We could probably use middlewares then if desired to prototype/test this out. This seems faster and less risky than making a change to default behavior (which might still make sense once we have proven it out).

Does that make sense?

There is a remote_ip attribute on the socket itself, but that doesn't appear to be written to datum. Would adding that `:remote_ip` value to the datum make sense and be sufficient for our use? If we rely on middleware, I think the connection would still occur, but we could prevent the request. Is that good enough, or is it important to not even connect?

Thanks!

**Comment by allenwu1973** [comment]
Sorry for the late response.
Yes, remote_ip in datum would be sufficient.

I think prevent the request is good enough for SSRF.
Though it would be nicer if we can have another hook besides request_call (eg. connected, so one before, one after connection), that way we can prevent people from probing hosts in private network.

Thanks

**Comment by geemus** [comment]
Here is my first pass at adding it to datum: https://github.com/excon/excon/commit/9852f514b0274f89cea5f3317ffdd6b31f1ee219

I think blocking the connect could make sense also, but would be more if/when we add it to the default stuff (as adding a new connect chain is more complicated). Does that make sense?

Let me know if that seems to be what you need to get started, thanks!
