### ISSUE TITLE
Decompress and Redirect Follower

### ISSUE THREAD

**Issue by estebanbouza** [excon/excon#707]
When using both middlewares, I get what seems like an endless loop & stack level too deep error. 
- Version 0.67
- Using within a Sidekiq / ActiveJob job

Any clues? Does the order of middlewares matter? 

```ruby
      excon_opts = { 
        ssl_verify_peer: opts[:verify_ssl] || false,
        proxy: opts[:proxy_url] || opts[:proxy],
        middlewares: (Excon.defaults[:middlewares] << Excon::Middleware::Decompress << Excon::Middleware::RedirectFollower),
        headers: opts[:headers],
      }
      response = Excon.get url, excon_opts
```

Output

```
4d32-a98c-afde78a6046c) from Sidekiq(myjob) in 1254.31ms: Excon::Error::Socket (Connection refused - connect(2) for 10.0.19.129:24000 (Errno::ECONNREFUSED)):
/usr/local/lib/ruby/2.6.0/socket.rb:1213:in `__connect_nonblock'
/usr/local/lib/ruby/2.6.0/socket.rb:1213:in `connect_nonblock'
/usr/local/bundle/gems/excon-0.67.0/lib/excon/socket.rb:152:in `rescue in block in connect'
/usr/local/bundle/gems/excon-0.67.0/lib/excon/socket.rb:131:in `block in connect'
/usr/local/bundle/gems/excon-0.67.0/lib/excon/socket.rb:121:in `each'
/usr/local/bundle/gems/excon-0.67.0/lib/excon/socket.rb:121:in `connect'
/usr/local/bundle/gems/excon-0.67.0/lib/excon/ssl_socket.rb:162:in `connect'
/usr/local/bundle/gems/excon-0.67.0/lib/excon/socket.rb:47:in `initialize'
/usr/local/bundle/gems/excon-0.67.0/lib/excon/ssl_socket.rb:10:in `initialize'
/usr/local/bundle/gems/excon-0.67.0/lib/excon/connection.rb:455:in `new'
/usr/local/bundle/gems/excon-0.67.0/lib/excon/connection.rb:455:in `socket'
/usr/local/bundle/gems/excon-0.67.0/lib/excon/connection.rb:116:in `request_call'
/usr/local/bundle/gems/excon-0.67.0/lib/excon/middlewares/redirect_follower.rb:15:in `request_call'
/usr/local/bundle/gems/excon-0.67.0/lib/excon/middlewares/decompress.rb:12:in `request_call'
/usr/local/bundle/gems/excon-0.67.0/lib/excon/middlewares/redirect_follower.rb:15:in `request_call'
/usr/local/bundle/gems/excon-0.67.0/lib/excon/middlewares/decompress.rb:12:in `request_call'
/usr/local/bundle/gems/excon-0.67.0/lib/excon/middlewares/redirect_follower.rb:15:in `request_call'
/usr/local/bundle/gems/excon-0.67.0/lib/excon/middlewares/decompress.rb:12:in `request_call'
/usr/local/bundle/gems/excon-0.67.0/lib/excon/middlewares/redirect_follower.rb:15:in `request_call'
/usr/local/bundle/gems/excon-0.67.0/lib/excon/middlewares/decompress.rb:12:in `request_call'
/usr/local/bundle/gems/excon-0.67.0/lib/excon/middlewares/redirect_follower.rb:15:in `request_call'
/usr/local/bundle/gems/excon-0.67.0/lib/excon/middlewares/decompress.rb:12:in `request_call'
/usr/local/bundle/gems/excon-0.67.0/lib/excon/middlewares/redirect_follower.rb:15:in `request_call'
/usr/local/bundle/gems/excon-0.67.0/lib/excon/middlewares/decompress.rb:12:in `request_call'
/usr/local/bundle/gems/excon-0.67.0/lib/excon/middlewares/redirect_follower.rb:15:in `request_call'
/usr/local/bundle/gems/excon-0.67.0/lib/excon/middlewares/decompress.rb:12:in `request_call'
/usr/local/bundle/gems/excon-0.67.0/lib/excon/middlewares/redirect_follower.rb:15:in `request_call'
```

**Comment by estebanbouza** [comment]
Pinging @geemus since you seem to have developed the redirect follower limits.

**Comment by geemus** [comment]
I wouldn't suspect this behavior from an interaction between those middlewares in particular, and similarly don't think the order should matter all that much (redirect first might be slightly more performant, to avoid decompressing if you are just going to follow a redirect anyway).

My suspicion would instead be that the link you are trying to follow really is a redirect loop, though there is no way for me to know for sure. The redirect follower limits are fairly new, in the grand scheme of things, so there may be bugs there which we haven't caught yet (in which case fixing this would give us a more helpful error, but at the end of the day if the link leads to a loop you may still have issues).

Does that help and make sense?

**Comment by estebanbouza** [comment]
Thanks for the quick response! I believe I've narrowed down the issue. Facts:

- I'm using a proxy `10.0.19.129:24000`
- The proxy port is not responding `Excon::Error::Socket (Connection refused - connect(2) for 10.0.19.129:24000 (Errno::ECONNREFUSED))`
- Removed Decompress middleware: `        middlewares: (Excon.defaults[:middlewares]  << Excon::Middleware::RedirectFollower)`

I still observe a huge amount of stacktrace calls of redirect follower calling itself. My suspicion then it's that:

- Excon does not handle correctly the failure of a proxy
- There's an issue with Redirect Follower if the proxy isn't responding. 

I'll add more details if I keep finding.

**Comment by geemus** [comment]
Ah, thanks for the extra detail. Yeah, I know I haven't done much testing of redirect+proxy, so I think that is probably a good thing to be suspicious of.

**Comment by estebanbouza** [comment]
The issue was in my code:

```ruby
middlewares: (Excon.defaults[:middlewares] << Excon::Middleware::Decompress << Excon::Middleware::RedirectFollower),
```

Whenever executed, it adds 2 new middlewares to Exconn. After a while running on sidekiq, there are thousands of middlewares added and makes the whole thing crash due to Stack Level Too Deep.

Closing this. Thanks @geemus !

**Comment by geemus** [comment]
Ah, yeah that would do it. Thanks for the update and glad you were able to pin down the issue.
