### ISSUE TITLE
Raise error on non success responses

### ISSUE THREAD

**Issue by assapir** [excon/excon#713]
Is it possible to automatically raise the right error (from 'Excon::Error` module) when the return status is not successful?

**Comment by geemus** [comment]
You can use `expects: [200]` to say, for instance that you expect a 200 response. This will otherwise raise an error based on the actual status code returned. You can list more than one status also if needed. Does that provide what you need, or am I misunderstanding?

**Comment by meijin007** [comment]
The problem with `expects` that the error message is very not informative.
Also, is that throwing `Excon::Error`?

**Comment by geemus** [comment]
What kind of information would you prefer? Could you give a specific example?

Yes, it uses Excon::Error. This derives from StandardError, so it should behave mostly as you would expect, but also has some specifics added that help with this particular context.

**Comment by meijin007** [comment]
Is it possible then to throw based on the error sub class? Like throw only in `server` or `client` types?
Thanks!

**Comment by geemus** [comment]
Hmm. Maybe by using a longer list of acceptable responses in the expects. Do you have a specific example of what you are trying to do? I think that might help me give better advice. Thanks!

**Comment by assapir** [comment]
No, that sound good, I was handle to do what I was thinking. Thanks!

**Comment by geemus** [comment]
Great, thanks for the update.
