### ISSUE TITLE
Support AddTrust Root Expiration

### ISSUE THREAD

**Issue by aYukiSekiguchi** [excon/excon#717]
AddTrust Root was expired
https://support.sectigo.com/articles/Knowledge/Sectigo-AddTrust-External-CA-Root-Expiring-May-30-2020

IIUC, excon has its own root certs, so excon can't handle the expiration correctly.
On Ubuntu 16.04:
```ruby
#!/usr/bin/env ruby
require 'rubygems'
require 'excon'

con = Excon.new('https://www.access-company.com/')
p con.request(method: :get, path: "")
```

result:
```
/usr/local/asdf/installs/ruby/2.4.4/lib/ruby/gems/2.4.0/gems/excon-0.73.0/lib/excon/ssl_socket.rb:128:in `connect_nonblock': SSL_connect returned=1 errno=0 state=error: certificate verify failed (OpenSSL::SSL::SSLError) Unable to verify certificate. This may be an issue with the remote host or with Excon. Excon has certificates bundled, but these can be customized: (Excon::Error::Certificate)

            `Excon.defaults[:ssl_ca_path] = path_to_certs`
            `ENV['SSL_CERT_DIR'] = path_to_certs`
            `Excon.defaults[:ssl_ca_file] = path_to_file`
            `ENV['SSL_CERT_FILE'] = path_to_file`
...
```

curl has the same problem. However, after the following fix curl works well, but excon doesn't work.
https://www.reddit.com/r/linux/comments/gshh70/sectigo_root_ca_expiring_may_not_be_handled_well/

Specifying system's root certs fixes the verification error in excon.
```
SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt ruby test.rb
```

It looks like there is a problem in root certs of excon.

**Comment by aYukiSekiguchi** [comment]
Older OpenSSL has a bug, so this depends on OS version, but I could reproduced on the latest Ubuntu 16.04 + excon 0.73.0
https://calnetweb.berkeley.edu/calnet-technologists/incommon-sectigo-certificate-service/addtrust-external-root-expiration-may-2020

**Comment by geemus** [comment]
Thanks for the heads up. We use the same certs as curl (which are extracted from mozilla). I was hoping they would update so that I wouldn't have to deviate and maintain the change over time, but if they both have workarounds already, maybe I will have to address this more directly. I'll try to take another look next week and see about fixing it if it hasn't resolved upstream.

**Comment by geemus** [comment]
@aYukiSekiguchi I think this should now be fixed on master. It still pulls the certs from curl/mozilla as before, but processes them to comment out AddTrust. From my reading this should not have a negative impact and also resolve the issue you encountered. I ran the sample script you listed and didn't get an error, but could you confirm that this fixes the problem for you also? Thanks!

**Comment by aYukiSekiguchi** [comment]
Great. It works!
Thank you for quick fix.

**Comment by geemus** [comment]
Fix now released as part of 0.74.0.

**Comment by aYukiSekiguchi** [comment]
FYI:
macOS 10.15.5 has the old AddTrust cert in `/etc/ssl/cert.pem`. (Therefore, `curl` has this problem.)

The old AddTrust cert is used by excon 0.74.0 on macOS because excon sets the default path in addition to its bundled cert file:
https://github.com/excon/excon/blob/v0.74.0/lib/excon/ssl_socket.rb#L55
```ruby
          ssl_context.cert_store.set_default_paths
```

Removing the above line or manually specify the bundled cert will fix this cert problem:
```
SSL_CERT_FILE=~/.asdf/installs/ruby/2.4.4/lib/ruby/gems/2.4.0/gems/excon-0.74.0/data/cacert.pem ./test.rb
```

**Comment by geemus** [comment]
@aYukiSekiguchi Thanks for the heads up.
