### ISSUE TITLE
Ruby 3.x compatibility

### ISSUE THREAD

**Issue by djberg96** [excon/excon#730]
With the release of 3.0 on Christmas, and 3.1 on the way, I thought I would try to run the specs and see how it went. However, it would seem that excon is currently held up by dependencies:

```
Bundler found conflicting requirements for the Ruby version:
  In Gemfile:
    Ruby x86_64-darwin-19

    puma x86_64-darwin-19 was resolved to 5.1.1, which depends on
      nio4r (~> 2.0) x86_64-darwin-19 was resolved to 2.5.4, which depends on
        Ruby (>= 2.4) x86_64-darwin-19

    puma x86_64-darwin-19 was resolved to 5.1.1, which depends on
      Ruby (>= 2.2) x86_64-darwin-19

    rubysl (~> 2.0) x86_64-darwin-19 was resolved to 2.2.0, which depends on
      rubysl-fcntl (~> 2.0) was resolved to 2.0.4, which depends on
        Ruby (~> 2.0)

    sinatra-contrib x86_64-darwin-19 was resolved to 2.1.0, which depends on
      Ruby (>= 2.3.0) x86_64-darwin-19

    unicorn x86_64-darwin-19 was resolved to 5.8.0, which depends on
      Ruby (>= 1.9.3) x86_64-darwin-19
```

**Comment by geemus** [comment]
@djberg96 Thanks for the heads up, will try to find some time to work through updating these soon. I'd also welcome your help if you have the time and/or inclination.

**Comment by geemus** [comment]
@djberg96 I tried to poke at this a bit, without much luck. It seems as though rubysl is locked to an earlier version of ruby, and is required for rubinius. I think/thought it shouldn't be trying to use it for non rubinius builds though, which should prevent this particular problem I would think. I gave up after a bit of failing. Do you have any further experience or insights you might share on what I could be missing?

**Comment by djberg96** [comment]
I'm afraid I don't have answers for you at this point. Maybe the ruby-sl stuff is behind yet and just needs time? Not sure.

**Comment by geemus** [comment]
Yeah, I wondered if it was just lagging. I can try some other things if it continues to lag, but will probably let it be for a little while longer in the hopes it becomes easier.

**Comment by djberg96** [comment]
I think this is still happening.

**Comment by geemus** [comment]
@djberg96 I believe you are correct. I'll add the `pinned` label to avoid this being marked stale again. At least for now we do have v3 testing happening (with a timeout, which it is still consistently hitting). So we can at least be aware if it resolves on it's own, which I had hoped for. It may require deeper digging though.

**Comment by geemus** [comment]
This seems now to have resolved (guessing with something in the 3.0.1 release, though I'm not sure what exactly).

**Comment by djberg96** [comment]
@geemus They must've gotten the standard library issue worked out. Running the specs locally again with 3.0.1 it worked fine. Thanks!

**Comment by geemus** [comment]
Yeah, I finally had a little time to look into it, got 3.0.1 all setup locally and everything passed, so then I double checked and saw it was working in actions too.
