### ISSUE TITLE
API request sending only in development

### ISSUE THREAD

**Issue by RailsCod3rFuture** [excon/excon#734]
Our app is behind cloudflare and runs on https -- But, I can only send requests successfully in the development environment. Does anyone know why this is happening?

**Comment by geemus** [comment]
Do you have any logs or other specific details about how the requests are failing? This could potentially be found by turning setting the environment variable `EXCON_DEBUG` to true (among some other options). I'm afraid without a bit more detail it's hard to know what is going wrong here.

**Comment by RailsCod3rFuture** [comment]
I think the call silently failed due to validations on the fields.

**Comment by geemus** [comment]
Thanks for the update, hope you are able to get it sorted out.
