### ISSUE TITLE
How to get the full request url after making the request?

### ISSUE THREAD

**Issue by patatero** [excon/excon#757]
Is there a way to get the full url that was built inside an Excon request? I'm trying to write a better error message inside Sidekiq but the only ones that I can get are `response.host` and `response.path`. No way to get the queries or the full request url.

```ruby
class FetchThingWorker
  include Sidekiq::Worker

  def perform
    response = Excon.get(
      'https://httpstat.us/500',
      query: { sleep: 5000 },
      headers: { 'Accept' => 'application/json' }
    )

    if response.status == 200
      puts response.body
    else
      raise "Failed request with status #{response.status}, url: #{response.host}#{response.path}, body: #{response.body}"
    end
  end
end
```

**Comment by geemus** [comment]
Good question. Reviewing the code, it doesn't look like we store these values on to the response, so they wouldn't be available readily (as you suggest). The query data does get passed into the response though (in `Response#parse`), so it is certainly something we could add. I guess it hasn't been requested (at least not that I can recall).

As an aside, you might consider trying `:expects => 200` in the initial request, which will raise if the status isn't 200 and might simplify your code a little. If I recall correctly, excon errors DO have the entire request datum available as well. So you might be able to access that via `error.request[:query]` or similar.

That doesn't exactly get what you asked for, but might serve the same purpose. I can certainly imagine how adding more of that information to the response could be useful as well though. Does that all make sense?

**Comment by patatero** [comment]
I'm not sure how to use `error.request[:query]`

```ruby
irb(main):003:1* response = Excon.get(
irb(main):004:1*       'https://httpstat.us/500',
irb(main):005:1*       query: { sleep: 1000 },
irb(main):006:1*       headers: { 'Accept' => 'application/json' },
irb(main):007:1*       expects: 200
irb(main):008:0> )
/Users/myname/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/excon-0.85.0/lib/excon/middlewares/expects.rb:13:in `response_call': Expected(200) <=> Actual(500 InternalServerError) (Excon::Error::InternalServerError)
irb(main):009:0> response
=> nil
irb(main):010:0> response.error
(irb):10:in `<main>': undefined method `error' for nil:NilClass (NoMethodError)
irb(main):011:0> error.request[:query]
(irb):11:in `<main>': undefined local variable or method `error' for main:Object (NameError)
```

or like this?

```ruby
irb(main):001:1* begin
irb(main):002:2*   response = Excon.get(
irb(main):003:2*     'https://httpstat.us/500',
irb(main):004:2*     query: { sleep: 1000 },
irb(main):005:2*     headers: { 'Accept' => 'application/json' },
irb(main):006:2*     expects: 200
irb(main):007:1*   )
irb(main):008:1* rescue StandardError => error
irb(main):009:1*   raise "Failed request with status #{error.request[:status]}, url: #{error.request[:host]}#{error.request[:path]}, params: #{error.request[:query]}, body: #{error.response[:body]}"
irb(main):010:1* else
irb(main):011:1*   puts response.body
irb(main):012:0> end
(irb):9:in `rescue in <main>': Failed request with status , url: httpstat.us/500, params: {:sleep=>1000}, body: {"code": 500, "description": "Internal Server Error"} (RuntimeError)
/Users/myname/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/excon-0.85.0/lib/excon/middlewares/expects.rb:13:in `response_call': Expected(200) <=> Actual(500 InternalServerError) (Excon::Error::InternalServerError)
```

**Comment by geemus** [comment]
Hey, sorry for the ambiguity. Yes, I would expect to rescue an error and then refer to the error object to do this (like the second example). I think you could then do something like this to get the full path: `Excon::Utils.request_uri(error.request)` (that should hopefully combine host + path + query for you as you wanted).

**Comment by geemus** [comment]
You might also want to rescue more narrowly, so something like `rescue Excon::Errors::StatusError => error`, to prevent accidentally catching an unrelated error.

**Comment by patatero** [comment]
I tried `rescue Excon::Errors::StatusError => error` but I got the error:

```(irb):8:in `rescue in <main>': uninitialized constant Excon::Errors::StatusError (NameError)
Did you mean?  Excon::Errors::HTTPStatusError```

So I tried `rescue Excon::Errors::HTTPStatusError => error` with `Excon::Utils.request_uri(error.request)` and they did work: 

```ruby
def perform
  begin
    response = Excon.get(
      'https://httpstat.us/500',
      query: { sleep: 1000 },
      headers: ApiProvider1.headers,
      expects: 200
    )
  rescue Excon::Errors::HTTPStatusError => error
    raise "Failed request with status #{error.response[:status]}, url: #{Excon::Utils.request_uri(error.request)}, body: #{error.response[:body]}"
  else
    puts response.body
  end
end
```

Thanks man.

**Comment by geemus** [comment]
Oops, sorry about being off on the particular error name, glad it was easy to figure out. Sounds good. I'll call this closed for now (though it might make sense at some point to add some of that other data to the response itself).
