### ISSUE TITLE
Does not work with async gem

### ISSUE THREAD

**Issue by morgoth** [excon/excon#781]
Please, see the discussion on https://github.com/socketry/async/discussions/155

Is there any design reason for what is found here https://github.com/socketry/async/discussions/155#discussioncomment-2316113

**Comment by geemus** [comment]
Responded on that. Going to close this for now to focus the conversation there (and we can reopen issues and/or pull requests here as needed). Thanks.

**Comment by geemus** [comment]
I believe #782 should fix this, or at least the obvious portion we had discovered so far.

Are you able to confirm and/or help me with some code to reproduce/test?
