### ISSUE TITLE
Mention retry_errors in README

### ISSUE THREAD

**Issue by fwolfst** [excon/excon#790]
Feature implemented in https://github.com/excon/excon/pull/690 lacks documentation.
Since the "examples" block in the README was pretty long, it might make sense to extract "Timeouts and retries". See attached PR.

**Comment by geemus** [comment]
Looks good overall, but doesn't look like it's been turned into a pull request yet. Could you tie the fixes to a PR to simplify the process for me? Thanks!

**Comment by fwolfst** [comment]
> Looks good overall, but doesn't look like it's been turned into a pull request yet. Could you tie the fixes to a PR to simplify the process for me? Thanks!

👍 
Ideally the doc would cover a case where only a specific (e.g. 500) Http error is retried, because that is probably the most common usecase, but I ran out of time. Given PR should already be an improvement.

**Comment by geemus** [comment]
Yep, no worries, progress is always appreciated. Thanks for the help!
