### ISSUE TITLE
Simple GET fails with read timeout 

### ISSUE THREAD

**Issue by vanboom** [excon/excon#821]
We are attempting to GET from a simple API that takes an authentication token, e.g. 
```ruby
headers = {'api-token' => 'x12345678'}
Excon.get(
  url: 'https://my.api.url.here',
  headers: headers
)
```
This code used to work until recently so we are hunting for reasons.   Excon fails with a read timeout no matter what the time out values are.  

```
Excon::Error::Timeout: read timeout reached
Caused by:
OpenSSL::SSL::SSLErrorWaitReadable: read would block
```

So we tested with Faraday...

```ruby
Faraday.new(url, headers: headers).get
```
And Faraday works!  The read takes about 5 seconds to complete.

We are using ruby 2.5.0 compiled with openssl 1.0.2n.   Attempted with Excon 0.88.0, 0.93.0, 0.92.4, 0.99.0 and all have the same behavior.  

Appreciate any guidance or advice - thank you for an amazing gem (Excon).

**Comment by geemus** [comment]
One thing to try would be setting the `omit_default_port` option to true. In my experience this has often been the culprit behind what otherwise seems inexplicable (especially when other gems/clients work fine). I wouldn't expect this to have changed, but if the server config changed it might not allow something with an explicit port any more.

Outside of that, it sounds like you tried a few versions. Is there anything else you may have changed that might relate to making this not work although it had in the past?

**Comment by vanboom** [comment]
Thanks for the tip -- unfortunately `omit_default_port: true` had no effect.  I cannot think of anything else that may have changed in the code base.  I went back and  checked out a prior commit from Jan 2023 that worked with Excon 0.92.4 so possibly something has changed on the API server so we have opened a request with them.   It's really odd that Faraday is working with the same URL and headers.  I would be happy to debug further to help out this gem if you have any other suggestions, Excon has worked beautifully until now.

**Comment by vanboom** [comment]
A ha!  I noticed that the Faraday headers included a "User-Agent" value, so I added one to the Excon headers and the GET worked!

**Comment by geemus** [comment]
Glad you were able to find a fix, some servers definitely require that. Though I would expect it to be automatically set in excon as well, you can see that here: https://github.com/excon/excon/blob/1e0c0ee3e975b2470262c6c882dccc752382e03c/lib/excon/constants.rb#L145. Is it possible you were overriding the defaults for excon in a way that might have overwritten this?

**Comment by vanboom** [comment]
Thanks @geemus, yes, we were setting the headers manually to include an authorization token so now we see that including the `headers` parameter overrides the defaults.  Thanks again!

**Comment by geemus** [comment]
@vanboom ah, yeah that makes sense. You could potentially do something like: `headers: DEFAULTS['headers'].merge!(my_headers)`, but just adding this one particular header is probably more than sufficient for this.
