### ISSUE TITLE
Add support to set a DNS resolver timeout

### ISSUE THREAD

**Issue by bruno-b-martins** [excon/excon#829]
Hey there 👋 

I'm trying to fix an issue in a process of ours where the DNS resolver hangs for too long when resolving an internal hostname.
We still resolve the internal hostname with a retry mechanism, but the retry mechanism only kicks in after ~60 seconds.
That's basically how long it took until we receive the error message triggered by https://github.com/excon/excon/blob/master/lib/excon/socket.rb#L167:
> Excon::Error::Socket (no address for internal.hostname.com (Resolv::ResolvError))

Since we have the `Resolv::ResolvError` in there, I'm guessing that's where it hangs.
To add a shorter timeout in Resolv we need to use `Resolv::DNS#timeouts` (https://ruby-doc.org/3.2.2/stdlibs/resolv/Resolv/DNS.html#method-i-timeouts-3D).

I'll create a PR to apply that change ☝️ and I appreciate any feedback you have to give me.
Navigating through the `Connection` class, its `socket` method and all available socket classes was a bit confusing as a first time contributor 😅

**Comment by geemus** [comment]
Without a reproduction case to play with, it's hard for me to know what the right fix for that particular problem, is, but I did provide some support on the linked PR. Hopefully with that you'll be able to test and see if that helps with this problem. Just let me know if you have questions or I can help further.

**Comment by bruno-b-martins** [comment]
#830 just implemented this, so I'm closing the issue now.

Thanks for the help and until next time 👋
