### ISSUE TITLE
Default retry behaviour includes HTTP 4xx client errors

### ISSUE THREAD

**Issue by rahim** [excon/excon#833]
See https://github.com/fog/fog-aws/issues/690 for background on how I stumbled on this. I opened a PR in fog-aws to configure round this, but it feels like something that might be better addressed here.

https://github.com/excon/excon/pull/690 added the ability to configure which errors were retried.

Excon sets the following for `retry_errors` https://github.com/excon/excon/blob/85556aeb4af10e94f876a8cbdb764f0377fa0d3a/lib/excon/constants.rb#L19-L23

`Client`, `Success`, `Redirection`, `Informational` and `Server` are all descendants of `Excon::Error::HTTPStatus`. https://github.com/excon/excon/blob/85556aeb4af10e94f876a8cbdb764f0377fa0d3a/lib/excon/error.rb#L68-L125

Incomplete tree for some additional context:
```
StandardError
└──Excon::Error
   ├──Warning
   ├──Socket
   │  └──Certificate
   ├──InvalidHeaderKey
   ├──InvalidHeaderValue
   ├──Timeout
   ├──ResponseParse
   ├──ProxyConnectionError
   ├──ProxyParse
   ├──TooManyRedirects
   └──HttpStatus
      ├──Informational
      ├──Success
      │  ├──OK
      │  ├──Created
      │  ├──Accepted
      │  └──[...]
      ├──Redirection
      ├──Client
      │  ├──BadRequest
      │  ├──Unauthorized
      │  ├──PaymentRequired
      │  ├──Forbidden
      │  ├──NotFound
      │  ├──MethodNotAllowed
      │  ├──NotAcceptable
      │  ├──ProxyAuthenticationRequired
      │  ├──RequestTimeout
      │  ├──Conflict
      │  ├──Gone
      │  └──[...]
      └──Server
         ├──InternalServerError
         ├──BadGateway
         ├──ServiceUnavailable
         └──GatewayTimeout
```   

In terms of descendants of `HttpStatus` I struggle to think of situations where retrying anything other than `Excon::Error::Server` and perhaps `Excon::RequestTimeout` and `Excon::TooManyRequests` could be useful. Blanketing the failures is certainly the conservative choice here though, there's surely scenarios I've just not had the imagination to think up.

When `retry_interval` is 0 (as is the case in Excon's default configuration), these choices tend to have minimal impact because repeat queries are typically so fast, but when the interval is increased waiting on retries for scenarios we have no reason to believe would change becomes a cost.

My suggestion is that we set

```
  DEFAULT_RETRY_ERRORS = [
    Excon::Error::Timeout,
    Excon::Error::Socket,
    Excon::Error::Server
  ]
```

Possibly also including `Excon::RequestTimeout` and `Excon::TooManyRequests`.

I'm happy to open a PR if there's agreement this is a reasonable approach.

**Comment by geemus** [comment]
Hey, I mentioned this on one of the fog-aws issues, but I think the main potential use case that I can recall is to smooth eventual consistency. ie a NotFound is retried, with some delay, making it so the end user doesn't have to necessarily deal with that themselves. (or at least I believe that was my intention back then).

To your points though, there are a few problems with this.

1. Although this behavior might be helpful, the implementation is much broader than this and likely retries many things that would always fail, wasting time and effort. So even if we decided to keep this behavior, we would might want to narrow it to only apply to the not found case.
2. The not found/eventual consistency case is not actually that common in the wild I don't think. Some of how this is probably reflects that this was originally just a portion of fog, which initially only supported AWS (where eventual consistency was definitely something you have to regularly contend with). Most things are not aws though, and so it might warrant different defaults in the general case vs the aws case.
3. The appropriate intervals for the eventual consistency case and other cases may be quite different. ie it may make sense for no delay in some cases, but for eventual consistency and TooManyRequests something like exponential backoff might be more appropriate. Maybe that means these should be broken out or treated differently.

It's possible that the right approach might be to separate out the eventual consistency stuff and handle that specifically in fog-aws (and not here where it's rarely applicable). That could also give us more flexibility/leverage to make it configurable.

What do you think?

**Comment by rahim** [comment]
> It's possible that the right approach might be to separate out the eventual consistency stuff and handle that specifically in fog-aws (and not here where it's rarely applicable). That could also give us more flexibility/leverage to make it configurable.
>
> What do you think?

That sounds a promising path - I'd been starting to think along similar lines – that trying to cover off the eventual consistency case as the default behaviour in a HTTP library feels like overstretching.

Default retry of _anything_ is somewhat surprising when compared with other HTTP libraries, to my knowledge, all of net-http/httparty/faraday/curl/python-requests/js-fetch/axios require some form of explicit opt-in to get any retry.

At the fog service level, where waiting on eventual consistency is something that might be desirable, it feels like something that would benefit from specific affordances that call out exactly what's going on.

A good comparison is the [AWS Ruby SDK's waiters](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/using-waiters.html) pattern:

```ruby
ec2 = Aws::EC2::Client.new
ec2.wait_until(:instance_running, instance_ids:['i-12345678'])
```

**Comment by geemus** [comment]
@rahim yeah, in fog there is the somewhat similar `Fog.wait_for` though it isn't always used. I also agree that removing the client errors from retries sounds like a good fix in general (and even more so given our discussion in fog-aws about the state of everything).

I don't think there should be any retries by default though. The middleware is loaded by default, but I believe the actual retry is based on the truthiness of `:idempotent`, which defaults to false (see: https://github.com/excon/excon/blob/master/lib/excon/constants.rb#L151). So in that regard, I guess it's inline with other libraries, though I'm not sure they have a similar notion of idempotence and retries at all. Does that make sense?

**Comment by rahim** [comment]
> I don't think there should be any retries by default though. The middleware is loaded by default, but I believe the actual retry is based on the truthiness of :idempotent, which defaults to false

Ah, thank you - that was a detail I'd missed.

When I was reviewing the various fog retry behaviours it sounds like I ought to have been grepping for where that idempotent flag got set too.

**Comment by geemus** [comment]
No worries, it's pretty easy to overlook I think.
