### ISSUE TITLE
There is not always data to read from socket when `Errno::EPIPE` is raised (on macOS?)

### ISSUE THREAD

**Issue by walro** [excon/excon#873]
In #761, Excon started to read the server response from the socket. However, there are cases where a `Errno::EPIPE` is raised and the socket is not readable. I have only been able to reproduce it under macOS (currently 14.7.1) and apologies in advance for the clunky repro:

```
# on Ruby 3.3.5 and Excon 1.2.0
$ ruby -rexcon -e 'p RUBY_VERSION;p Excon::VERSION'
"3.3.5"
"1.2.0"

# start a webserver
$ ruby -run -e httpd . -p 8000

# make a persistent connection and sleep for a while before making a new request, during the sleep restart the webserver in the step above
$ ruby -rexcon -e 'conn = Excon.new("http://localhost:8000", persistent: true); conn.get; sleep 70; conn.get(idempotent: true)'
<internal:io>:63:in `read_nonblock': Connection reset by peer (Errno::ECONNRESET)
  from <...>/3.3.5/lib/ruby/gems/3.3.0/gems/excon-1.2.0/lib/excon/socket.rb:249:in `read_nonblock'
  from <...>/3.3.5/lib/ruby/gems/3.3.0/gems/excon-1.2.0/lib/excon/socket.rb:67:in `read'
  from <...>/3.3.5/lib/ruby/gems/3.3.0/gems/excon-1.2.0/lib/excon/connection.rb:197:in `rescue in request_call'
  from <...>/3.3.5/lib/ruby/gems/3.3.0/gems/excon-1.2.0/lib/excon/connection.rb:115:in `request_call'
  from <...>/3.3.5/lib/ruby/gems/3.3.0/gems/excon-1.2.0/lib/excon/middlewares/mock.rb:57:in `request_call'
  from <...>/3.3.5/lib/ruby/gems/3.3.0/gems/excon-1.2.0/lib/excon/middlewares/instrumentor.rb:34:in `request_call'
  from <...>/3.3.5/lib/ruby/gems/3.3.0/gems/excon-1.2.0/lib/excon/middlewares/idempotent.rb:19:in `request_call'
  from <...>/3.3.5/lib/ruby/gems/3.3.0/gems/excon-1.2.0/lib/excon/middlewares/base.rb:22:in `request_call'
  from <...>/3.3.5/lib/ruby/gems/3.3.0/gems/excon-1.2.0/lib/excon/middlewares/decompress.rb:14:in `request_call'
  from <...>/3.3.5/lib/ruby/gems/3.3.0/gems/excon-1.2.0/lib/excon/middlewares/base.rb:22:in `request_call'
  from <...>/3.3.5/lib/ruby/gems/3.3.0/gems/excon-1.2.0/lib/excon/connection.rb:293:in `request'
  from <...>/3.3.5/lib/ruby/gems/3.3.0/gems/excon-1.2.0/lib/excon/connection.rb:379:in `get'
  from -e:1:in `<main>'
<internal:io>:121:in `write_nonblock': Broken pipe (Errno::EPIPE)
  from <...>/3.3.5/lib/ruby/gems/3.3.0/gems/excon-1.2.0/lib/excon/socket.rb:321:in `block in write_nonblock'
  from <internal:kernel>:187:in `loop'
  from <...>/3.3.5/lib/ruby/gems/3.3.0/gems/excon-1.2.0/lib/excon/socket.rb:316:in `write_nonblock'
  from <...>/3.3.5/lib/ruby/gems/3.3.0/gems/excon-1.2.0/lib/excon/socket.rb:106:in `write'
  from <...>/3.3.5/lib/ruby/gems/3.3.0/gems/excon-1.2.0/lib/excon/connection.rb:167:in `request_call'
  from <...>/3.3.5/lib/ruby/gems/3.3.0/gems/excon-1.2.0/lib/excon/middlewares/mock.rb:57:in `request_call'
  from <...>/3.3.5/lib/ruby/gems/3.3.0/gems/excon-1.2.0/lib/excon/middlewares/instrumentor.rb:34:in `request_call'
  from <...>/3.3.5/lib/ruby/gems/3.3.0/gems/excon-1.2.0/lib/excon/middlewares/idempotent.rb:19:in `request_call'
  from <...>/3.3.5/lib/ruby/gems/3.3.0/gems/excon-1.2.0/lib/excon/middlewares/base.rb:22:in `request_call'
  from <...>/3.3.5/lib/ruby/gems/3.3.0/gems/excon-1.2.0/lib/excon/middlewares/decompress.rb:14:in `request_call'
  from <...>/3.3.5/lib/ruby/gems/3.3.0/gems/excon-1.2.0/lib/excon/middlewares/base.rb:22:in `request_call'
  from <...>/3.3.5/lib/ruby/gems/3.3.0/gems/excon-1.2.0/lib/excon/connection.rb:293:in `request'
  from <...>/3.3.5/lib/ruby/gems/3.3.0/gems/excon-1.2.0/lib/excon/connection.rb:379:in `get'
  from -e:1:in `<main>'

# paths edited for brevity
```

Following the stack and one can see that it tries to read from the socket at https://github.com/excon/excon/blob/v1.2.0/lib/excon/connection.rb#L197, causing the `Errno::ECONNRESET` to be raised, but not wrapped as a `Excon::Error::Socket` as intended. Ultimately leading to the "idempotent retry" to never happen.

I have found that the needed sleep is at least 60 seconds in order for this to happen. I first thought it was related to the timeout settings, I tried to decrease them but it does not seem to change anything.

Interestingly enough, under Linux I get a `EOFError` rather than `Errno::EPIPE` as the first raised error in the same scenario, and then retries works just fine. Moreover we have only observed this in local development (under macOS), production runs on Linux where we have never seen this happen, further making me believe this is isolated to macOS.

I can also add that if using `https`, the final raised error will be `OpenSSL::SSL::SSLError` (rather than `Errno::ECONNRESET`). I would assume this is because it uses `Excon::SSLSocket` instead of `Excon::Socket`.

I am not familiar with Excon to see what the proper solution would be, a `rescue` for the raise at https://github.com/excon/excon/blob/v1.2.0/lib/excon/connection.rb#L197 would be simple, but perhaps this should be caught at a deeper level.

Let me know if you need more input and thanks for the gem!

**Comment by geemus** [comment]
@walro thanks for the detailed report and sorry to hear you are running in to this.

I think probably a rescue that uses `raise_socket_error` there would make sense (ie it would fall back to the same behavior as the else in the existing clause). Would you be up for taking a pass at that and confirming it solves the problem for you? (I only have linux machines readily available to me locally, so it's not the easiest to test/replicate).

**Comment by walro** [comment]
#874 does the trick for me at least, let me know if anything needs to be adjusted.
